"""Tests for `harness/swe/slowtier.py` — the recorded, resumable slow-tier
ledger (round 341, SWE-loop D).

Deliberately NOT named `test_swe_*.py`: `harness/tests/conftest.py` marks
every file with that prefix `swe_slow`, and a module whose whole purpose is
to make the slow tier visible to the FAST health check must itself run in
the fast tier. Every test here injects a fake runner and a fake clock —
nothing shells out to pytest, nothing reads the real whence checkout except
the two tests that say so in their names.
"""
import json
import os
import sys

sys.path.insert(0, os.path.dirname(os.path.dirname(os.path.abspath(__file__))))

import swe.slowtier as ST


# ------------------------------------------------------------------ digest --

def test_digest_is_stable_and_content_sensitive(tmp_path):
    root = tmp_path / "co"
    (root / "whence").mkdir(parents=True)
    (root / "whence" / "interp.py").write_text("x = 1\n")
    (root / "whence" / "parser.py").write_text("y = 2\n")
    d1 = ST.checkout_digest(str(root))
    assert d1 == ST.checkout_digest(str(root))          # stable
    (root / "whence" / "interp.py").write_text("x = 2\n")
    assert ST.checkout_digest(str(root)) != d1          # content-sensitive


def test_digest_ignores_bytecode_caches_and_documentation(tmp_path):
    """A digest that moved every time the suite RAN would mark every result
    stale immediately — self-defeating. `__pycache__`/`.pytest_cache` are
    regenerated by merely running the tests, and a SPEC.md edit cannot
    move a line number in a `.py` source.

    Round 361 renamed this from `..._and_non_python`: the digest now covers
    `.lang` too (`_SOURCE_EXTS`), so the excluded set is documentation and
    caches, not "everything that is not Python". Nothing this test asserts
    changed."""
    root = tmp_path / "co"
    (root / "whence").mkdir(parents=True)
    (root / "whence" / "interp.py").write_text("x = 1\n")
    d = ST.checkout_digest(str(root))
    (root / "whence" / "__pycache__").mkdir()
    (root / "whence" / "__pycache__" / "interp.cpython-311.pyc").write_bytes(b"\x00bytecode")
    (root / ".pytest_cache").mkdir()
    (root / ".pytest_cache" / "junk.py").write_text("noise = 1\n")
    (root / "SPEC.md").write_text("# a doc edit\n")
    (root / ".venv").mkdir()
    (root / ".venv" / "lib.py").write_text("vendored = 1\n")
    assert ST.checkout_digest(str(root)) == d


def test_digest_notices_a_renamed_file(tmp_path):
    """Path names are folded in, not just contents — moving a module is a
    change that shifts what a scratch copy contains."""
    root = tmp_path / "co"
    root.mkdir()
    (root / "a.py").write_text("v = 1\n")
    d = ST.checkout_digest(str(root))
    os.rename(str(root / "a.py"), str(root / "b.py"))
    assert ST.checkout_digest(str(root)) != d


# ------------------------------------------------------------------ ledger --

def test_slow_tier_files_matches_conftests_own_rule():
    """`conftest.pytest_collection_modifyitems` marks exactly
    `basename.startswith("test_swe_")`. If that rule ever changes, this
    module's whole notion of 'the tier' silently drifts from pytest's."""
    src = open(os.path.join(os.path.dirname(os.path.abspath(__file__)),
                            "conftest.py"), encoding="utf-8").read()
    assert 'startswith("test_swe_")' in src
    files = ST.slow_tier_files()
    assert files and all(f.startswith("test_swe_") and f.endswith(".py") for f in files)
    assert "test_slowtier.py" not in files          # this file is fast-tier


def test_latest_by_file_takes_the_newest_entry(tmp_path):
    p = str(tmp_path / "l.jsonl")
    ST.append_entry(p, {"file": "test_swe_a.py", "outcome": "failed", "finished_at": 10})
    ST.append_entry(p, {"file": "test_swe_a.py", "outcome": "passed", "finished_at": 20})
    ST.append_entry(p, {"file": "test_swe_b.py", "outcome": "failed", "finished_at": 15})
    best = ST.latest_by_file(ST.read_entries(p))
    assert best["test_swe_a.py"]["outcome"] == "passed"
    assert best["test_swe_b.py"]["outcome"] == "failed"


def test_a_torn_last_line_is_skipped_not_fatal(tmp_path):
    """A round killed mid-append (round 338/339 both died at max-turns)
    leaves a partial line. Absence of a record is handled by rule 1; a
    crash here would take the whole health check down with it."""
    p = str(tmp_path / "l.jsonl")
    ST.append_entry(p, {"file": "test_swe_a.py", "outcome": "passed", "finished_at": 1})
    with open(p, "a") as f:
        f.write('{"file": "test_swe_b.py", "outc')
    entries = ST.read_entries(p)
    assert len(entries) == 1 and entries[0]["file"] == "test_swe_a.py"


def test_read_entries_on_a_missing_ledger_is_empty_not_an_error(tmp_path):
    assert ST.read_entries(str(tmp_path / "nope.jsonl")) == []


# -------------------------------------------------------- the fail-closed --

def test_no_entry_is_unknown_never_pass():
    """Rule 1. The whole point: a tier nobody ran must not read as green,
    which is exactly how round 338's five failures stayed invisible."""
    assert ST.classify(None, "abc") == "unknown"


def test_a_pass_against_a_different_checkout_is_stale_not_fresh():
    """Rule 2."""
    e = {"outcome": "passed", "checkout_digest": "old", "checkout_stable": True}
    assert ST.classify(e, "new") == "stale_checkout"
    assert ST.classify(e, "old") == "fresh_pass"


def test_a_result_computed_while_the_checkout_moved_is_never_evidence():
    """Rule 3, and round 341's own finding made mechanical: a PASS produced
    while another round was editing `languages/whence/` is no more
    trustworthy than the FAIL it might equally have produced."""
    for outcome in ("passed", "failed"):
        e = {"outcome": outcome, "checkout_digest": "same", "checkout_stable": False}
        assert ST.classify(e, "same") == "raced"
    assert "raced" not in ST.CONCLUSIVE


def test_an_unrecognised_outcome_falls_back_to_unknown():
    """Fail-closed on the default branch too — a `timeout` outcome is not
    a pass and must not be counted as one."""
    e = {"outcome": "timeout", "checkout_digest": "d", "checkout_stable": True}
    assert ST.classify(e, "d") == "unknown"


# ------------------------------------------------------------------ status --

def _status_over(tmp_path, entries, files, digest="D"):
    tests = tmp_path / "t"
    tests.mkdir(exist_ok=True)
    for f in files:
        (tests / f).write_text("")
    p = str(tmp_path / "l.jsonl")
    for e in entries:
        # Round 343: these entries are about SUBJECT staleness, so stamp them
        # with the harness digest they would really have been written with.
        # Without it every one classifies `unstamped` and the tests below stop
        # testing what they were written to test — a schema change silently
        # neutering the suite that guards it.
        e.setdefault("dep_digests",
                     ST.dep_digests(e["file"], tests_dir=str(tests)))
        ST.append_entry(p, e)
    return ST.status(ledger_path=p, tests_dir=str(tests), digest=digest)


def test_status_reports_its_own_recall(tmp_path):
    """Round 339's rule: a checker nobody is watching must report the size
    of its own blind spot, or a partial sweep reads as a complete one."""
    st = _status_over(tmp_path, [
        {"file": "test_swe_a.py", "outcome": "passed", "finished_at": 5,
         "checkout_digest": "D", "checkout_stable": True},
        {"file": "test_swe_b.py", "outcome": "passed", "finished_at": 5,
         "checkout_digest": "OLD", "checkout_stable": True},
    ], ["test_swe_a.py", "test_swe_b.py", "test_swe_c.py"])
    assert st["n_files"] == 3 and st["n_conclusive"] == 1
    assert abs(st["coverage"] - 1.0 / 3) < 1e-9
    by = dict((r["file"], r["state"]) for r in st["rows"])
    assert by == {"test_swe_a.py": "fresh_pass",
                  "test_swe_b.py": "stale_checkout",
                  "test_swe_c.py": "unknown"}


def test_status_counts_only_fresh_failures_as_failing(tmp_path):
    """A failure recorded against a checkout that has since changed is a
    lead, not a verdict — round 338's five failures need re-running, not
    re-asserting."""
    st = _status_over(tmp_path, [
        {"file": "test_swe_a.py", "outcome": "failed", "finished_at": 5,
         "checkout_digest": "D", "checkout_stable": True},
        {"file": "test_swe_b.py", "outcome": "failed", "finished_at": 5,
         "checkout_digest": "OLD", "checkout_stable": True},
    ], ["test_swe_a.py", "test_swe_b.py"])
    assert st["n_failing"] == 1


def test_report_text_names_the_uncovered_count(tmp_path):
    st = _status_over(tmp_path, [], ["test_swe_a.py", "test_swe_b.py"])
    txt = ST.report_text(st)
    assert "0% recall" in txt and "2 file(s) are NOT evidence" in txt
    assert "unknown" in txt


# -------------------------------------------------------------------- plan --

def test_plan_runs_the_least_covered_first(tmp_path):
    st = _status_over(tmp_path, [
        {"file": "test_swe_a.py", "outcome": "passed", "finished_at": 100,
         "checkout_digest": "D", "checkout_stable": True, "seconds": 10},
        {"file": "test_swe_b.py", "outcome": "passed", "finished_at": 50,
         "checkout_digest": "D", "checkout_stable": True, "seconds": 10},
    ], ["test_swe_a.py", "test_swe_b.py", "test_swe_c.py"])
    assert ST.plan(st, budget_s=10_000, default_s=10) == [
        "test_swe_c.py",     # no evidence at all -> first
        "test_swe_b.py",     # then oldest
        "test_swe_a.py",
    ]


def test_plan_respects_the_budget_and_uses_measured_costs(tmp_path):
    st = _status_over(tmp_path, [
        {"file": "test_swe_a.py", "outcome": "passed", "finished_at": 1,
         "checkout_digest": "D", "checkout_stable": True, "seconds": 30},
        {"file": "test_swe_b.py", "outcome": "passed", "finished_at": 2,
         "checkout_digest": "D", "checkout_stable": True, "seconds": 900},
        {"file": "test_swe_c.py", "outcome": "passed", "finished_at": 3,
         "checkout_digest": "D", "checkout_stable": True, "seconds": 30},
    ], ["test_swe_a.py", "test_swe_b.py", "test_swe_c.py"])
    # b's measured 900s does not fit beside a; c does.
    assert ST.plan(st, budget_s=100) == ["test_swe_a.py", "test_swe_c.py"]


def test_a_file_slower_than_any_budget_is_still_eventually_run(tmp_path):
    """The silent-truncation guard. If an over-budget file were simply
    skipped forever it would be permanently `unknown` while the report
    claimed progress — round 340's "no silent caps" lesson."""
    st = _status_over(tmp_path, [
        {"file": "test_swe_huge.py", "outcome": "passed", "finished_at": 1,
         "checkout_digest": "D", "checkout_stable": True, "seconds": 5000},
    ], ["test_swe_huge.py"])
    assert ST.plan(st, budget_s=60) == ["test_swe_huge.py"]


def test_plan_is_empty_only_when_there_is_nothing_to_run(tmp_path):
    st = _status_over(tmp_path, [], [])
    assert ST.plan(st, budget_s=600) == []


# --------------------------------------------------------------- run_slice --

def test_run_slice_records_one_entry_per_file_with_a_fake_runner(tmp_path):
    p = str(tmp_path / "l.jsonl")
    root = tmp_path / "co"
    (root).mkdir()
    (root / "a.py").write_text("v = 1\n")
    seen = []

    def runner(f):
        seen.append(f)
        return {"returncode": 0 if f.endswith("a.py") else 1,
                "timed_out": False, "tail": "output for " + f}

    ticks = iter([100.0, 130.0, 200.0, 260.0])
    written = ST.run_slice(["test_swe_a.py", "test_swe_b.py"], ledger_path=p,
                           whence_root=str(root), runner=runner,
                           clock=lambda: next(ticks))
    assert seen == ["test_swe_a.py", "test_swe_b.py"]
    assert [e["outcome"] for e in written] == ["passed", "failed"]
    assert [e["seconds"] for e in written] == [30.0, 60.0]
    assert all(e["checkout_stable"] for e in written)
    on_disk = ST.read_entries(p)
    assert len(on_disk) == 2 and on_disk[0]["file"] == "test_swe_a.py"


def test_run_slice_flags_a_checkout_that_moves_mid_run(tmp_path):
    """The mechanism behind four of round 338's five failures, caught and
    recorded instead of silently believed. The runner here edits the tree
    while it 'runs', exactly as a concurrent language(C) round does."""
    p = str(tmp_path / "l.jsonl")
    root = tmp_path / "co"
    root.mkdir()
    (root / "interp.py").write_text("v = 1\n")

    def runner(f):
        (root / "interp.py").write_text("# a concurrent round landed here\nv = 1\n")
        return {"returncode": 0, "timed_out": False, "tail": ""}

    written = ST.run_slice(["test_swe_a.py"], ledger_path=p, whence_root=str(root),
                           runner=runner, clock=iter([1.0, 2.0]).__next__)
    e = written[0]
    assert e["outcome"] == "passed"                       # pytest was happy
    assert e["checkout_stable"] is False                  # ...and it does not count
    assert e["checkout_digest"] != e["checkout_digest_after"]
    assert ST.classify(e, e["checkout_digest"]) == "raced"


def test_run_slice_records_a_timeout_as_a_timeout_not_a_failure(tmp_path):
    p = str(tmp_path / "l.jsonl")
    root = tmp_path / "co"
    root.mkdir()
    (root / "a.py").write_text("v = 1\n")
    written = ST.run_slice(["test_swe_a.py"], ledger_path=p, whence_root=str(root),
                           runner=lambda f: {"returncode": -9, "timed_out": True, "tail": ""},
                           clock=iter([1.0, 2.0]).__next__)
    assert written[0]["outcome"] == "timeout"
    assert ST.classify(written[0], written[0]["checkout_digest"]) == "unknown"


def test_entries_are_json_serialisable_and_append_only(tmp_path):
    p = str(tmp_path / "l.jsonl")
    root = tmp_path / "co"
    root.mkdir()
    (root / "a.py").write_text("v = 1\n")
    for _ in range(3):
        ST.run_slice(["test_swe_a.py"], ledger_path=p, whence_root=str(root),
                     runner=lambda f: {"returncode": 0, "timed_out": False, "tail": ""},
                     clock=iter([1.0, 2.0]).__next__)
    lines = open(p, encoding="utf-8").read().strip().splitlines()
    assert len(lines) == 3
    for l in lines:
        json.loads(l)


# --------------------------------------------------------- against the repo --

def test_the_real_slow_tier_is_the_files_round_338_measured():
    """A live-tree sanity check, deliberately a MEMBERSHIP assertion and
    not a count: the tier grows when a round adds a `test_swe_*.py`, and
    pinning `len(...)` here would be exactly the live-file aggregate pin
    round 340's next-steps item 4 warns against."""
    files = set(ST.slow_tier_files())
    for f in ("test_swe_alias_effects.py", "test_swe_campaign.py",
              "test_swe_repair.py", "test_swe_fuzz.py"):
        assert f in files, f


def test_the_real_checkout_digest_is_computable_and_short():
    d = ST.checkout_digest()
    assert isinstance(d, str) and len(d) == 16 and d == ST.checkout_digest()


# ------------------------------------------- the health-check integration --

def _fast_script():
    return os.path.join(os.path.dirname(os.path.dirname(os.path.abspath(__file__))),
                        "run_tests_fast.sh")


def test_fast_health_check_still_returns_pytests_own_exit_code():
    """Round 341 changed `run_tests_fast.sh` from `exec pytest` to
    run-then-report, which is exactly the shape that silently swallows an
    exit code. Both paths are exercised for real (collection only, so this
    stays a fast-tier test): a matching `-k` exits 0, a non-matching one
    exits pytest's own 5 (`NO_TESTS_COLLECTED`).

    Also asserts the slow-tier report is actually PRINTED — a diagnostic
    nobody sees is the failure mode this whole module exists to fix."""
    import subprocess
    ok = subprocess.run(["bash", _fast_script(), "--collect-only", "-q",
                         "-k", "test_digest_is_stable_and_content_sensitive"],
                        stdout=subprocess.PIPE, stderr=subprocess.STDOUT)
    assert ok.returncode == 0, ok.stdout[-2000:]
    assert b"slow tier:" in ok.stdout, ok.stdout[-2000:]

    none = subprocess.run(["bash", _fast_script(), "--collect-only", "-q",
                           "-k", "zzz_no_such_test_name_zzz"],
                          stdout=subprocess.PIPE, stderr=subprocess.STDOUT)
    assert none.returncode == 5, (none.returncode, none.stdout[-2000:])
    assert b"slow tier:" in none.stdout, none.stdout[-2000:]


# ------------------------------------------------------- harness deps (343) --
#
# Round 341's item 2: `checkout_digest` stamps the SUBJECT, so an entry stayed
# `fresh_pass` after the test file — or the `swe/` module under it — was
# rewritten. Round 343 adds a per-file dependency digest.

def test_dep_closure_is_the_test_plus_its_transitive_swe_imports():
    d = ST.harness_deps("test_swe_coverage.py")
    assert "tests/test_swe_coverage.py" in d
    assert "tests/conftest.py" in d                  # pytest loads it regardless
    assert "swe/coverage.py" in d
    assert "swe/proc.py" in d                        # transitive: coverage imports it
    assert "swe/__init__.py" in d                    # executed on package import
    assert "swe/campaign.py" not in d                # not reachable from this test


def test_dep_closure_follows_relative_and_function_scope_imports():
    """`swe/` uses both (`from . import killers as K`; `swe/coverage.py:499`
    imports `.fuzz` inside a function). A closure that missed either would
    under-report and call a stale result fresh."""
    d = set(ST.harness_deps("test_swe_equivalence.py"))
    assert "swe/killers.py" in d                     # `from .killers import ...`
    assert "swe/coverage.py" in d and "swe/triage.py" in d   # `from . import X as Y`
    assert "swe/fuzz.py" in d                        # function-scope in coverage.py


def test_closures_differ_per_file_which_is_the_whole_point():
    """A single digest over `harness/swe/` + `harness/tests/` — the literal
    shape round 341 proposed — would invalidate all 18 files on any harness
    edit. On a one-CPU box where the tier costs ~76 minutes and a round's
    budget is minutes, recall would reset faster than rounds could raise it.
    Per-file closures are what make the ledger able to accumulate at all."""
    small = ST.harness_deps("test_swe_proc.py")
    big = ST.harness_deps("test_swe_campaign.py")
    assert len(small) < len(big)
    assert set(small) < set(big) or "swe/proc.py" in big     # nested, not disjoint
    # slowtier.py is imported by no slow test, so editing IT invalidates none
    assert not any("slowtier" in p for p in big)


def test_a_blind_scan_falls_back_to_the_whole_package(tmp_path, monkeypatch):
    """Fail-closed floor: a `test_swe_*.py` resolving to NO swe module means
    the scan is blind (every slow test exists to exercise that package), so
    the closure widens to everything rather than narrowing to nothing."""
    td = tmp_path / "tests"
    td.mkdir()
    (td / "test_swe_blind.py").write_text("import os\n")     # no swe import
    d = ST.harness_deps("test_swe_blind.py", tests_dir=str(td))
    assert "swe/fuzz.py" in d and "swe/campaign.py" in d


def test_an_unparsable_dependency_falls_back_rather_than_crashing(tmp_path):
    td = tmp_path / "tests"
    td.mkdir()
    (td / "test_swe_broken.py").write_text("import swe.fuzz\ndef f(:\n")
    d = ST.harness_deps("test_swe_broken.py", tests_dir=str(td))
    assert "swe/fuzz.py" in d and "swe/campaign.py" in d      # whole package


def test_moved_deps_names_the_file_not_just_the_fact():
    """Round 341 asked for 'subject moved' and 'test moved' to stay
    distinguishable. Storing a digest PER PATH answers a sharper question:
    which one."""
    entry = {"dep_digests": {"swe/fuzz.py": "aaa", "tests/t.py": "bbb"}}
    assert ST.moved_deps(entry, {"swe/fuzz.py": "aaa", "tests/t.py": "bbb"}) == []
    assert ST.moved_deps(entry, {"swe/fuzz.py": "zzz", "tests/t.py": "bbb"}) \
        == ["swe/fuzz.py"]
    # an appeared/vanished dependency is a change to WHAT the test exercises
    assert ST.moved_deps(entry, {"swe/fuzz.py": "aaa"}) == ["tests/t.py"]
    assert ST.moved_deps(entry, dict(entry["dep_digests"], **{"swe/new.py": "c"})) \
        == ["swe/new.py"]


def _entry(**kw):
    e = {"file": "test_swe_x.py", "outcome": "passed", "checkout_digest": "D",
         "checkout_stable": True, "harness_stable": True,
         "dep_digests": {"swe/fuzz.py": "aaa"}}
    e.update(kw)
    return e


def test_classify_rejects_a_pass_whose_harness_moved():
    cur = {"swe/fuzz.py": "aaa"}
    assert ST.classify(_entry(), "D", cur) == "fresh_pass"
    assert ST.classify(_entry(), "D", {"swe/fuzz.py": "zzz"}) == "stale_harness"
    assert "stale_harness" not in ST.CONCLUSIVE


def test_classify_rejects_a_pre_343_entry_as_unstamped():
    """Fail-closed rule 5: an entry written before the harness was stamped
    says nothing about which harness produced it, and absence of evidence
    is not evidence (rule 1's own principle, applied to a schema change)."""
    old = _entry()
    del old["dep_digests"]
    assert ST.classify(old, "D", {"swe/fuzz.py": "aaa"}) == "unstamped"
    assert "unstamped" not in ST.CONCLUSIVE
    # ...and the round-341 caller, which passes no dep map, is unaffected
    assert ST.classify(old, "D") == "fresh_pass"


def test_a_harness_that_moved_mid_run_is_raced_like_the_checkout():
    """Rule 3 generalised: a result computed while its inputs moved is not
    evidence, whichever input moved."""
    assert ST.classify(_entry(harness_stable=False), "D", {"swe/fuzz.py": "aaa"}) \
        == "raced"
    # absent field defaults to stable, so round-341 entries are not all raced
    e = _entry(); del e["harness_stable"]
    assert ST.classify(e, "D", {"swe/fuzz.py": "aaa"}) == "fresh_pass"


def test_run_slice_stamps_both_digests_and_detects_a_harness_race(tmp_path):
    """The harness-race path, exercised the way round 340 exercised the
    subject race: mutate a real dependency from inside the injected runner,
    so the before/after scan straddles a genuine edit."""
    led = str(tmp_path / "l.jsonl")
    td = tmp_path / "tests"
    td.mkdir()
    (td / "test_swe_fake.py").write_text("import swe.proc\n")
    (td / "conftest.py").write_text("# c\n")
    target = os.path.join(ST.HARNESS_ROOT, "swe", "proc.py")
    original = open(target, "rb").read()

    calls = []

    def runner(f):
        calls.append(f)
        with open(target, "ab") as fh:               # a concurrent round, in effect
            fh.write(b"\n# round-343 transient\n")
        return {"returncode": 0, "timed_out": False, "tail": "ok"}

    try:
        [e] = ST.run_slice(["test_swe_fake.py"], ledger_path=led, runner=runner,
                           clock=lambda: 1.0, tests_dir=str(td))
    finally:
        with open(target, "wb") as fh:
            fh.write(original)
    assert calls == ["test_swe_fake.py"]
    # Round 361 bumped the schema to 3 (subject scope); round 367 bumped it
    # to 4, when rule 10 changed what `subject_scope.ok` MEANS for a run
    # that did not finish; round 433 bumped it to 5, when the entry stopped
    # being about a FILE and started being about a unit (`unit`, `unit_kind`,
    # `unit_tests`). The pin stays a pin: an entry writer that stops
    # stamping a version is how a reader silently starts guessing which
    # rules an entry obeyed.
    assert e["outcome"] == "passed" and e["schema"] == 5
    # ...and an unsplit file's unit id IS its filename, which is why every
    # pre-433 entry needs no migration.
    assert e["unit"] == "test_swe_fake.py" and e["unit_kind"] == ST.WHOLE
    assert e["checkout_stable"] is True               # whence never moved
    assert e["harness_stable"] is False               # but swe/proc.py did
    assert "swe/proc.py" in e["dep_digests"]
    assert ST.classify(e, e["checkout_digest"], e["dep_digests"]) == "raced"


def test_status_rows_carry_the_dep_count_and_the_moved_list(tmp_path):
    led = str(tmp_path / "l.jsonl")
    st = ST.status(ledger_path=led)
    row = [r for r in st["rows"] if r["file"] == "test_swe_proc.py"][0]
    assert row["state"] == "unknown" and row["n_deps"] >= 3
    assert row["moved_deps"] == []                   # no entry -> nothing moved


def test_plan_prefers_the_cheapest_unmeasured_file_not_the_alphabetical_one():
    """With an empty ledger every estimate is `default_s`, so round 341's
    key degenerated to alphabetical and spent a whole first budget on
    `test_swe_alias_effects.py` (873 s measured, round 341) covering one
    file. The size prior is a TIE-break only."""
    st = ST.status(ledger_path=os.path.join(str(os.devnull), "absent"))
    picked = ST.plan(st, 900.0)
    assert picked and picked[0] != "test_swe_alias_effects.py"
    assert len(picked) > 1


def test_a_real_measurement_always_beats_the_size_prior():
    rows = [{"file": "big.py", "state": "unknown", "finished_at": None, "seconds": 5.0},
            {"file": "aaa.py", "state": "unknown", "finished_at": None, "seconds": None}]
    picked = ST.plan({"rows": rows}, 900.0, default_s=300.0)
    assert picked[0] == "big.py"                     # measured 5s beats prior 300s


# ------------------------------------------------- subject scope (round 361) --
#
# The subject half of the freshness gate. `checkout_digest` is one sha over
# the whole whence checkout, and 52% of the commits that move it touch
# nothing any slow-tier file imports. These tests pin the narrowing AND — the
# part that matters — every way it is refused.

import swe.readscope as RS


def _scoped_entry(dirs, digs, **kw):
    e = _entry(checkout_digest="OLD")
    e["subject_scope"] = {"ok": True, "dirs": list(dirs), "opaque": [],
                          "n_reads": len(dirs), "why": ""}
    e["subject_digests"] = dict(digs)
    e["schema"] = 3
    e.update(kw)
    return e


def test_a_pyc_read_is_evidence_about_its_source_not_about_pycache():
    """With a populated `__pycache__`, importing `whence.parser` opens the
    `.pyc` and never opens the `.py`. Recording the raw path would place the
    scope in a directory the digest ignores by construction."""
    assert RS.normalize_read("whence/__pycache__/parser.cpython-312.pyc") \
        == "whence/parser.py"
    assert RS.normalize_read("whence/parser.py") == "whence/parser.py"
    assert RS.normalize_read(".git/objects/ab/cdef") is None
    # a pyc whose SOURCE would still be ignored is not resurrected
    assert RS.normalize_read(".venv/__pycache__/x.cpython-312.pyc") is None


def test_scope_is_directories_not_files():
    """Rule 2. `list_example_files` shells `git ls-files`, so a NEW example
    changes what the corpus contains without any existing file being opened.
    A file-granular scope would be fail-open against exactly that."""
    assert RS.scope_dirs(["examples/self_eval.lang", "whence/parser.py"]) \
        == ["examples", "whence"]
    assert RS.scope_dirs(["run.py"]) == ["."]
    assert RS.scope_dirs([]) == []


def test_dir_digest_notices_an_added_file_of_any_extension(tmp_path):
    root = tmp_path / "co"
    (root / "examples").mkdir(parents=True)
    (root / "examples" / "self_eval.lang").write_text("guest = 1\n")
    d = RS.dir_digest(str(root), "examples")
    (root / "examples" / "new_case.lang").write_text("x\n")
    assert RS.dir_digest(str(root), "examples") != d
    assert RS.dir_digest(str(tmp_path), "nope") == "<missing>"


def test_dir_digest_is_not_recursive():
    """`scope_dirs` reports every directory actually read, so a subdirectory
    that matters appears on its own. Recursing would silently re-couple
    `whence/` to trees nothing in it reads."""
    import tempfile
    d = tempfile.mkdtemp()
    os.makedirs(os.path.join(d, "a", "b"))
    open(os.path.join(d, "a", "x.py"), "w").write("1")
    before = RS.dir_digest(d, "a")
    open(os.path.join(d, "a", "b", "y.py"), "w").write("1")
    assert RS.dir_digest(d, "a") == before


def test_a_checkout_move_outside_the_scope_is_scoped_not_stale():
    """Rule 7. The claim is weaker, so it gets its OWN state and its own
    counter — it is never folded into `CONCLUSIVE`."""
    e = _scoped_entry(["whence"], {"whence": "W1"})
    assert ST.classify(e, "NEW", {"swe/fuzz.py": "aaa"}, {"whence": "W1"}) \
        == "fresh_pass_scoped"
    assert "fresh_pass_scoped" not in ST.CONCLUSIVE
    assert "fresh_pass_scoped" in ST.SCOPED_CONCLUSIVE


def test_a_checkout_move_inside_the_scope_is_stale_subject():
    """Rule 8, and it names the directory rather than counting one."""
    e = _scoped_entry(["whence", "examples"],
                      {"whence": "W1", "examples": "E1"})
    cur = {"whence": "W1", "examples": "E2"}
    assert ST.classify(e, "NEW", {"swe/fuzz.py": "aaa"}, cur) == "stale_subject"
    assert "stale_subject" not in ST.CONCLUSIVE
    assert "stale_subject" not in ST.SCOPED_CONCLUSIVE
    assert ST.moved_scope(e, cur) == ["examples"]


def test_a_scoped_failure_is_still_counted_as_failing():
    """A weaker freshness claim does not make the red less red."""
    e = _scoped_entry(["whence"], {"whence": "W1"}, outcome="failed")
    assert ST.classify(e, "NEW", {"swe/fuzz.py": "aaa"}, {"whence": "W1"}) \
        == "fresh_fail_scoped"
    assert "fresh_fail_scoped" in ST.FAILING and "fresh_fail" in ST.FAILING


def test_an_opaque_run_can_never_narrow_anything():
    """Rule 9, half one. `swe/coverage.py` spawns a pytest over the real
    checkout; that child has no audit hook, so its reads are invisible and
    nothing may be narrowed on their account."""
    scope = {"ok": True, "dirs": ["whence"], "opaque": ["subprocess.Popen"],
             "n_reads": 3, "why": ""}
    assert not RS.scope_is_narrowable(scope)
    e = _scoped_entry(["whence"], {"whence": "W1"})
    e["subject_scope"] = scope
    assert ST.scope_digests_now(e) is None
    assert ST.classify(e, "NEW", {"swe/fuzz.py": "aaa"},
                       ST.scope_digests_now(e)) == "stale_checkout"


def test_a_missing_or_torn_scope_record_falls_back_to_rule_2(tmp_path):
    """Rule 9, half two: no observation is not a narrow observation."""
    missing = RS.read_scope_file(str(tmp_path / "absent.json"))
    assert missing["ok"] is False and missing["why"] == "missing"
    torn = tmp_path / "torn.json"
    torn.write_text('{"reads": ["whence/parser.py"], "opaqu')
    assert RS.read_scope_file(str(torn))["why"] == "unreadable"
    wrong = tmp_path / "wrong.json"
    wrong.write_text('{"reads": "not-a-list", "opaque": []}')
    assert RS.read_scope_file(str(wrong))["why"] == "malformed"
    for bad in (missing, RS.read_scope_file(str(torn)),
                RS.read_scope_file(str(wrong))):
        assert not RS.scope_is_narrowable(bad)


def test_a_pre_361_entry_is_gated_exactly_as_round_341_gated_it():
    """The compatibility floor: nothing already in the ledger becomes
    fresher because this round shipped."""
    old = _entry(checkout_digest="OLD")           # no subject_scope at all
    assert ST.scope_digests_now(old) is None
    assert ST.classify(old, "NEW", {"swe/fuzz.py": "aaa"},
                       ST.scope_digests_now(old)) == "stale_checkout"
    assert ST.classify(old, "OLD", {"swe/fuzz.py": "aaa"}) == "fresh_pass"


def test_an_empty_scope_is_a_real_measurement_not_a_missing_one():
    """A test that reads nothing under the checkout — `test_swe_triage.py`
    measured 0 reads — is immune to every whence edit, and that is a FINDING,
    not an absence of one."""
    e = _scoped_entry([], {})
    assert ST.scope_digests_now(e) == {}
    assert ST.classify(e, "ANYTHING", {"swe/fuzz.py": "aaa"}, {}) \
        == "fresh_pass_scoped"


def test_run_slice_records_the_scope_and_a_scopeless_runner_is_fail_closed(tmp_path):
    root = tmp_path / "co"
    (root / "whence").mkdir(parents=True)
    (root / "whence" / "interp.py").write_text("x = 1\n")
    (root / "examples").mkdir()
    (root / "examples" / "self_eval.lang").write_text("guest = 1\n")
    tests = tmp_path / "t"
    tests.mkdir()
    (tests / "test_swe_a.py").write_text("")
    (tests / "test_swe_b.py").write_text("")
    led = str(tmp_path / "l.jsonl")

    def runner(f):
        if f == "test_swe_a.py":
            return {"returncode": 0, "timed_out": False, "tail": "",
                    "scope": {"ok": True, "dirs": ["whence"], "opaque": [],
                              "n_reads": 1, "why": ""}}
        return {"returncode": 0, "timed_out": False, "tail": ""}   # no scope

    a, b = ST.run_slice(["test_swe_a.py", "test_swe_b.py"], ledger_path=led,
                        whence_root=str(root), runner=runner,
                        clock=lambda: 1.0, tests_dir=str(tests))
    assert a["schema"] == 5
    assert a["subject_digests"] == {"whence": RS.dir_digest(str(root), "whence")}
    # A runner that reports nothing is not a runner that reported "nothing".
    assert b["subject_digests"] is None
    assert b["subject_scope"]["why"] == "runner-gave-none"
    assert ST.classify(b, "NEW", b["dep_digests"], ST.scope_digests_now(b)) \
        == "stale_checkout"
    # ... and the one that DID report is unaffected by an edit outside it.
    (root / "examples" / "self_eval.lang").write_text("guest = 2\n")
    assert ST.classify(a, ST.checkout_digest(str(root)), a["dep_digests"],
                       ST.scope_digests_now(a, str(root))) == "fresh_pass_scoped"
    # ... and IS affected by one inside it.
    (root / "whence" / "interp.py").write_text("x = 2\n")
    assert ST.classify(a, ST.checkout_digest(str(root)), a["dep_digests"],
                       ST.scope_digests_now(a, str(root))) == "stale_subject"


def test_status_reports_the_two_recalls_separately(tmp_path):
    """Round 334's rule, applied here: three rounds of reported figures and
    `run_tests_fast.sh`'s printed line depend on what `n_conclusive` has
    meant since round 341, so the weaker number is a NEW field."""
    tests = tmp_path / "t"
    tests.mkdir()
    for f in ("test_swe_a.py", "test_swe_b.py"):
        (tests / f).write_text("")
    p = str(tmp_path / "l.jsonl")
    fresh = _entry(file="test_swe_a.py", checkout_digest="D")
    fresh["dep_digests"] = ST.dep_digests("test_swe_a.py", tests_dir=str(tests))
    scoped = _scoped_entry([], {}, file="test_swe_b.py")
    scoped["dep_digests"] = ST.dep_digests("test_swe_b.py", tests_dir=str(tests))
    for e in (fresh, scoped):
        ST.append_entry(p, e)
    st = ST.status(ledger_path=p, tests_dir=str(tests), digest="D")
    assert st["n_conclusive"] == 1 and st["n_scoped"] == 1
    assert st["coverage"] == 0.5 and st["coverage_scoped"] == 1.0
    txt = ST.report_text(st)
    assert "1 conclusive" in txt
    assert "conclusive WITHIN their measured read-scope only" in txt


def test_the_bootstrap_installs_the_hook_before_it_imports_pytest():
    """Ordering is the whole mechanism: `swe.*` and `whence.*` are read
    during pytest's own collection, so a hook installed afterwards sees
    nothing. Pinned by source order because there is no runtime observable
    for 'too late'."""
    src = RS.bootstrap_source("/tmp/root", "/tmp/out.json", ["-q", "x.py"])
    assert src.index("sys.addaudithook") < src.index("import pytest")
    assert src.index("atexit.register") < src.index("sys.addaudithook")
    assert "/tmp/root" in src and "/tmp/out.json" in src


def test_the_lang_extension_is_in_the_digest_and_docs_are_not(tmp_path):
    """Round 361's correction to round 341's `.py`-only rule.
    `examples/self_eval.lang` is the guest INTERPRETER, not documentation;
    three commits in this repo change a `.lang` and no `.py` at all."""
    root = tmp_path / "co"
    (root / "examples").mkdir(parents=True)
    (root / "examples" / "self_eval.lang").write_text("guest = 1\n")
    d = ST.checkout_digest(str(root))
    (root / "SPEC.md").write_text("# doc\n")
    (root / "README.txt").write_text("notes\n")
    assert ST.checkout_digest(str(root)) == d          # docs still excluded
    (root / "examples" / "self_eval.lang").write_text("guest = 2\n")
    assert ST.checkout_digest(str(root)) != d          # the guest is not a doc


# ----------------------------------------------- rule 10 (round 367) --------
#
# Round 361's item 5, in its own words: "Scope is measured from a run that may
# have failed early. A crashed run reads less than a healthy one, so its scope
# is an under-approximation. Today `run_slice` narrows on any outcome
# including `failed`. Either refuse to narrow on a non-`passed` outcome or
# record the decision knowingly — this round did neither."

def _scope_root(tmp_path):
    root = tmp_path / "co"
    (root / "whence").mkdir(parents=True)
    (root / "whence" / "interp.py").write_text("x = 1\n")
    tests = tmp_path / "t"
    tests.mkdir()
    (tests / "test_swe_a.py").write_text("")
    return root, tests


def _narrowable(**over):
    r = {"returncode": 0, "timed_out": False, "tail": "",
         "scope": {"ok": True, "dirs": ["whence"], "opaque": [],
                   "n_reads": 3, "why": ""}}
    r.update(over)
    return r


def test_rule_10_a_run_that_timed_out_may_not_narrow(tmp_path):
    """The under-approximation case: killed at the timeout, so whatever it
    had not read yet is missing from the scope and an edit there would look
    like an edit outside it."""
    root, tests = _scope_root(tmp_path)
    [e] = ST.run_slice(["test_swe_a.py"], ledger_path=str(tmp_path / "l"),
                       whence_root=str(root),
                       runner=lambda f: _narrowable(timed_out=True,
                                                    returncode=-9),
                       clock=lambda: 1.0, tests_dir=str(tests))
    assert e["outcome"] == "timeout"
    assert e["subject_scope"]["ok"] is False
    assert e["subject_scope"]["why"] == "run-did-not-complete: timed out"
    # What it MEASURED is still readable; it is simply not usable.
    assert e["subject_scope"]["dirs"] == ["whence"]
    assert e["subject_digests"] is None
    assert ST.classify(e, "NEW", e["dep_digests"],
                       ST.scope_digests_now(e, str(root))) == "stale_checkout"


def test_rule_10_a_run_that_merely_failed_still_narrows(tmp_path):
    """The deliberate NON-case. pytest exit 1 means the run collected,
    imported and reported — its read-set is complete, and `fresh_fail_scoped`
    is the state this module most wants to stay visible."""
    root, tests = _scope_root(tmp_path)
    [e] = ST.run_slice(["test_swe_a.py"], ledger_path=str(tmp_path / "l"),
                       whence_root=str(root),
                       runner=lambda f: _narrowable(returncode=1),
                       clock=lambda: 1.0, tests_dir=str(tests))
    assert e["outcome"] == "failed"
    assert e["subject_scope"]["ok"] is True
    assert e["subject_digests"] == {"whence": RS.dir_digest(str(root), "whence")}
    (root / "examples").mkdir()
    (root / "examples" / "new.lang").write_text("z = 1\n")
    assert ST.classify(e, ST.checkout_digest(str(root)), e["dep_digests"],
                       ST.scope_digests_now(e, str(root))) == "fresh_fail_scoped"


def test_rule_10_covers_every_return_code_that_is_not_a_verdict(tmp_path):
    """2 interrupted, 3 internal error, 4 usage error, 5 nothing collected."""
    root, tests = _scope_root(tmp_path)
    for rc in (2, 3, 4, 5):
        [e] = ST.run_slice(["test_swe_a.py"],
                           ledger_path=str(tmp_path / ("l%d" % rc)),
                           whence_root=str(root),
                           runner=lambda f, rc=rc: _narrowable(returncode=rc),
                           clock=lambda: 1.0, tests_dir=str(tests))
        assert e["subject_scope"]["ok"] is False, rc
        assert e["subject_scope"]["why"] == "run-did-not-complete: rc=%d" % rc
        assert e["subject_digests"] is None, rc


def test_rule_10_also_applies_on_the_READ_side_to_entries_already_written():
    """A ledger is append-only: stamping the refusal into new entries would
    leave every pre-round-367 entry under the old fail-open rule. The same
    question is asked of the entry itself, from fields it always carried."""
    e = _scoped_entry(["whence"], {"whence": "W1"})
    e["returncode"] = 0
    assert ST.scope_digests_now(e) is not None           # the baseline
    stale = dict(e, returncode=-9, timed_out=True)
    assert ST.scope_digests_now(stale) is None
    for rc in (2, 3, 4, 5, -9):
        assert ST.scope_digests_now(dict(e, returncode=rc)) is None, rc
    # ... and the two verdict codes are untouched.
    for rc in (0, 1):
        assert ST.scope_digests_now(dict(e, returncode=rc)) is not None, rc


def test_rule_10_changes_nothing_for_an_entry_with_no_returncode_field():
    """Rule 6's floor, restated for rule 10: a pre-343 entry that never
    recorded a return code must not become MORE stale because round 367
    shipped, any more than it may become fresher."""
    e = _scoped_entry(["whence"], {"whence": "W1"})
    e.pop("returncode", None)
    assert ST.scope_digests_now(e) is not None


# --------------------------------------------------------------------------
# round 385: a recorded RED must not render as a neutral staleness word
# --------------------------------------------------------------------------
def test_a_stale_entry_that_last_ran_red_is_named_as_such(tmp_path):
    """The state machine is unchanged and still right — a failure measured
    against a checkout that has moved is not evidence about this one. What
    changes is that `report_text` no longer prints it as the bare word
    `stale_checkout`, which reads exactly like a stale PASS.

    Live instance: `test_swe_guest.py` sat in the ledger at `2 failed, 65
    passed` for 18 hours while every round's health log printed
    `slow tier: ... 0 failing` over the top of it."""
    tests = tmp_path / "t"
    tests.mkdir()
    for f in ("test_swe_a.py", "test_swe_b.py"):
        (tests / f).write_text("")
    p = str(tmp_path / "l.jsonl")
    red = _entry(file="test_swe_a.py", outcome="failed", checkout_digest="OLD",
                 seconds=201.7, finished_at=1.0)
    red["dep_digests"] = ST.dep_digests("test_swe_a.py", tests_dir=str(tests))
    green = _entry(file="test_swe_b.py", outcome="passed", checkout_digest="OLD",
                   seconds=5.0, finished_at=1.0)
    green["dep_digests"] = ST.dep_digests("test_swe_b.py", tests_dir=str(tests))
    for e in (red, green):
        ST.append_entry(p, e)

    st = ST.status(ledger_path=p, tests_dir=str(tests), digest="NEW")
    assert st["n_failing"] == 0, "the state machine must not start counting it"
    assert st["n_recorded_failing_stale"] == 1
    txt = ST.report_text(st)
    assert "0 failing" in txt
    assert "LAST RAN RED" in txt
    lines = [ln for ln in txt.splitlines() if "test_swe_a.py" in ln]
    assert lines and "[last run RED]" in lines[0], txt
    assert not any("[last run RED]" in ln for ln in txt.splitlines()
                   if "test_swe_b.py" in ln), txt


def test_n_failing_keeps_the_meaning_it_has_had_since_round_341(tmp_path):
    """Round 334's rule, applied again: the new fact is a NEW field. A
    conclusive failure counts in `n_failing` and NOT in the new count, so no
    row is ever counted twice and no published figure moves."""
    tests = tmp_path / "t"
    tests.mkdir()
    (tests / "test_swe_a.py").write_text("")
    p = str(tmp_path / "l.jsonl")
    red = _entry(file="test_swe_a.py", outcome="failed", checkout_digest="D")
    red["dep_digests"] = ST.dep_digests("test_swe_a.py", tests_dir=str(tests))
    ST.append_entry(p, red)
    st = ST.status(ledger_path=p, tests_dir=str(tests), digest="D")
    assert st["rows"][0]["state"] == "fresh_fail"
    assert st["n_failing"] == 1
    assert st["n_recorded_failing_stale"] == 0
    assert "LAST RAN RED" not in ST.report_text(st)


def test_an_entry_with_no_outcome_at_all_is_not_called_red():
    """`unknown` (no ledger entry) and a torn entry are absences, not
    failures — fail-closed rule 1 must not be inverted by this annotation."""
    assert ST.recorded_failing_but_stale({"state": "unknown", "outcome": None}) is False
    assert ST.recorded_failing_but_stale({"state": "stale_checkout"}) is False
    assert ST.recorded_failing_but_stale(
        {"state": "stale_checkout", "outcome": "passed"}) is False
    assert ST.recorded_failing_but_stale(
        {"state": "stale_subject", "outcome": "failed"}) is True
    assert ST.recorded_failing_but_stale(
        {"state": "raced", "outcome": "failed"}) is True


def test_the_planner_re_runs_a_last_red_file_before_an_unknown(tmp_path):
    """`report_text` calls a last-red file "the first thing a slow-tier slice
    should re-run". Before round 385 the planner disagreed: a red file has a
    `finished_at` and an unmeasured one has 0, so round 341's key sorted the
    red one BEHIND every `unknown`. The claim and the code agree now, and
    this test is the thing that keeps them agreeing."""
    tests = tmp_path / "t"
    tests.mkdir()
    for f in ("test_swe_red.py", "test_swe_unknown.py", "test_swe_ok.py"):
        (tests / f).write_text("")
    p = str(tmp_path / "l.jsonl")
    red = _entry(file="test_swe_red.py", outcome="failed",
                 checkout_digest="OLD", seconds=10.0, finished_at=99.0)
    red["dep_digests"] = ST.dep_digests("test_swe_red.py", tests_dir=str(tests))
    ok = _entry(file="test_swe_ok.py", outcome="passed",
                checkout_digest="OLD", seconds=10.0, finished_at=1.0)
    ok["dep_digests"] = ST.dep_digests("test_swe_ok.py", tests_dir=str(tests))
    for e in (red, ok):
        ST.append_entry(p, e)

    st = ST.status(ledger_path=p, tests_dir=str(tests), digest="NEW")
    picked = ST.plan(st, budget_s=10_000.0, tests_dir=str(tests))
    assert picked[0] == "test_swe_red.py", picked
    assert set(picked) == {"test_swe_red.py", "test_swe_unknown.py",
                           "test_swe_ok.py"}, picked
    # ... and it did not jump the CONCLUSIVE/non-conclusive line, which is
    # still the OUTERMOST term. At the digest the entries were written
    # against, the red one is `fresh_fail` — conclusive evidence about this
    # very checkout — and the never-measured file outranks it again.
    st2 = ST.status(ledger_path=p, tests_dir=str(tests), digest="OLD")
    by_file = {r["file"]: r["state"] for r in st2["rows"]}
    assert by_file["test_swe_red.py"] == "fresh_fail"
    assert by_file["test_swe_unknown.py"] == "unknown"
    assert ST.plan(st2, budget_s=10_000.0, tests_dir=str(tests))[0] \
        == "test_swe_unknown.py"


def test_a_conclusive_red_is_not_re_run_first_because_it_needs_no_re_run(tmp_path):
    """`recorded_failing_but_stale` excludes `fresh_fail` on purpose: that
    file's red IS evidence about this checkout, so spending the slice's
    budget re-confirming it buys nothing. The term only ever promotes a
    failure the state machine has had to discard."""
    tests = tmp_path / "t"
    tests.mkdir()
    for f in ("test_swe_red.py", "test_swe_unknown.py"):
        (tests / f).write_text("")
    p = str(tmp_path / "l.jsonl")
    red = _entry(file="test_swe_red.py", outcome="failed",
                 checkout_digest="D", seconds=10.0, finished_at=99.0)
    red["dep_digests"] = ST.dep_digests("test_swe_red.py", tests_dir=str(tests))
    ST.append_entry(p, red)
    st = ST.status(ledger_path=p, tests_dir=str(tests), digest="D")
    assert st["rows"][0]["state"] == "fresh_fail" or st["rows"][1]["state"] == "fresh_fail"
    assert st["n_recorded_failing_stale"] == 0
    picked = ST.plan(st, budget_s=10_000.0, tests_dir=str(tests))
    assert picked[0] == "test_swe_unknown.py", picked


# ------------------------------------------------------- units (round 433) --
#
# The tier's unit of work and of evidence was a FILE until round 433, and
# `test_swe_campaign.py` is the file that broke it: 19 of its 20 tests cost
# 571.3 s together and its 20th runs two full unfiltered whence suites, so
# the file fits in no budget, has never had a ledger entry, and hid a red
# test for 92 rounds. These tests pin the split AND — the half that matters —
# every way the split is refused and every way it is forbidden to flatter a
# verdict.

def _tests_dir_with(tmp_path, files):
    """A scratch tests dir. `files` maps basename -> list of test names."""
    td = tmp_path / "t"
    td.mkdir(exist_ok=True)
    for name, tests in files.items():
        body = "".join("def %s():\n    pass\n\n\n" % t for t in tests)
        (td / name).write_text(body or "# no tests\n")
    return str(td)


def _reg(**heavy):
    return {"heavy": dict((k, {"tests": v}) for k, v in heavy.items())}


def test_an_empty_registry_leaves_every_file_exactly_one_unit(tmp_path):
    """The property that makes this change free: with nothing declared, a
    unit id IS a filename and every pre-433 caller is unaffected."""
    td = _tests_dir_with(tmp_path, {"test_swe_a.py": ["test_x", "test_y"],
                                    "test_swe_b.py": ["test_z"]})
    units = ST.slow_tier_units(td, registry={"heavy": {}})
    assert [u["id"] for u in units] == ST.slow_tier_files(td)
    assert all(u["kind"] == ST.WHOLE and u["tests"] == [] for u in units)


def test_a_declared_heavy_test_splits_its_file_into_two_units(tmp_path):
    td = _tests_dir_with(tmp_path, {"test_swe_a.py": ["test_cheap", "test_slow"]})
    units = ST.slow_tier_units(td, registry=_reg(**{"test_swe_a.py": ["test_slow"]}))
    assert [(u["id"], u["kind"]) for u in units] == [
        ("test_swe_a.py[light]", ST.LIGHT),
        ("test_swe_a.py[heavy]", ST.HEAVY)]
    assert all(u["file"] == "test_swe_a.py" for u in units)


def test_the_two_units_of_a_split_file_are_complements(tmp_path):
    """`[light]` must deselect exactly the node ids `[heavy]` selects. If the
    two ever drift, a test is either run twice or run never — and "run never"
    is invisible, because both units would still go green."""
    td = _tests_dir_with(tmp_path, {"test_swe_a.py": ["test_p", "test_q", "test_r"]})
    light, heavy = ST.slow_tier_units(td, registry=_reg(**{"test_swe_a.py": ["test_q", "test_r"]}))
    hargs = ST.unit_pytest_args(heavy, td)
    largs = ST.unit_pytest_args(light, td)
    assert set(hargs) == set(a for a in largs if "::" in a)
    assert len(hargs) == 2


def test_heavy_selects_by_node_id_never_by_a_k_substring(tmp_path):
    """`-k test_q` would also match `test_q_and_more`, silently widening the
    heavy unit and shrinking the light one by a test nobody deselected."""
    td = _tests_dir_with(tmp_path, {"test_swe_a.py": ["test_q", "test_q_and_more"]})
    _, heavy = ST.slow_tier_units(td, registry=_reg(**{"test_swe_a.py": ["test_q"]}))
    args = ST.unit_pytest_args(heavy, td)
    assert "-k" not in args
    assert args == [os.path.join(td, "test_swe_a.py") + "::test_q"]


def test_a_declared_heavy_test_that_is_not_in_the_file_is_a_registry_error(tmp_path):
    """A rename must not silently produce a `[heavy]` unit that collects
    nothing and a `[light]` unit whose name claims an exclusion it does not
    make. Falling back to the whole file is the fail-CLOSED direction: the
    strongest claim is the one that has to be re-earned."""
    td = _tests_dir_with(tmp_path, {"test_swe_a.py": ["test_kept"]})
    units = ST.slow_tier_units(td, registry=_reg(**{"test_swe_a.py": ["test_renamed_away"]}))
    assert [u["id"] for u in units] == ["test_swe_a.py"]
    assert units[0]["kind"] == ST.WHOLE
    assert "test_renamed_away" in units[0]["registry_error"]


def test_declaring_every_test_heavy_refuses_to_split(tmp_path):
    td = _tests_dir_with(tmp_path, {"test_swe_a.py": ["test_p", "test_q"]})
    units = ST.slow_tier_units(td, registry=_reg(**{"test_swe_a.py": ["test_p", "test_q"]}))
    assert [u["id"] for u in units] == ["test_swe_a.py"]
    assert "collect nothing" in units[0]["registry_error"]


def test_an_unreadable_test_file_refuses_to_split(tmp_path):
    """`file_test_names` returns None rather than [] for a file it cannot
    parse, so "I could not check" is never confused with "it has no tests"."""
    td = _tests_dir_with(tmp_path, {"test_swe_a.py": []})
    open(os.path.join(td, "test_swe_a.py"), "w").write("def broken(:\n")
    assert ST.file_test_names("test_swe_a.py", td) is None
    units = ST.slow_tier_units(td, registry=_reg(**{"test_swe_a.py": ["test_p"]}))
    assert [u["id"] for u in units] == ["test_swe_a.py"]
    assert "unreadable" in units[0]["registry_error"]


def test_a_broken_registry_never_raises_and_splits_nothing(tmp_path):
    """Round 348's `pyproject.toml` outage, one level up: `status` runs in
    every round's fast health check, so a malformed registry must cost the
    split and nothing else."""
    bad = tmp_path / "bad.json"
    bad.write_text("{ this is not json")
    r = ST.load_units_registry(str(bad))
    assert r["heavy"] == {} and r["_load_error"] is True
    missing = ST.load_units_registry(str(tmp_path / "nope.json"))
    assert missing["heavy"] == {} and missing["_load_error"] is True
    wrong = tmp_path / "wrong.json"
    wrong.write_text('{"heavy": ["not", "a", "dict"]}')
    assert ST.load_units_registry(str(wrong))["heavy"] == {}


def test_unit_file_is_pure_string_surgery():
    assert ST.unit_file("test_swe_a.py") == "test_swe_a.py"
    assert ST.unit_file("test_swe_a.py[light]") == "test_swe_a.py"
    assert ST.unit_file("test_swe_a.py[heavy]") == "test_swe_a.py"


def test_resolve_unit_never_returns_none_for_an_unknown_id(tmp_path):
    td = _tests_dir_with(tmp_path, {"test_swe_a.py": ["test_p"]})
    u = ST.resolve_unit("test_swe_ghost.py", td, registry={"heavy": {}})
    assert u["id"] == "test_swe_ghost.py" and u["kind"] == ST.WHOLE


# ------------------------------------------------------ rule 11 (round 433) --

def _split_units():
    return [{"id": "f.py[light]", "file": "f.py", "kind": ST.LIGHT,
             "tests": ["test_slow"], "registry_error": ""},
            {"id": "f.py[heavy]", "file": "f.py", "kind": ST.HEAVY,
             "tests": ["test_slow"], "registry_error": ""}]


def test_rule_11_a_whole_file_pass_is_evidence_for_every_unit():
    """The run was a strict superset of each unit's, and "everything passed"
    entails "these passed". Refusing to inherit it would throw away real
    evidence the moment a file is split."""
    e = {"file": "f.py", "outcome": "passed", "finished_at": 10, "seconds": 900}
    best = ST.latest_by_unit([e], _split_units())
    assert best["f.py[light]"] == (e, True)
    assert best["f.py[heavy]"] == (e, True)


def test_rule_11_a_whole_file_failure_is_evidence_for_no_sub_unit():
    """pytest's exit code does not say WHO was red. Attributing it to a unit
    invents a verdict; attributing a pass to the other unit invents the
    opposite one. So a whole-file failure is inherited by neither."""
    e = {"file": "f.py", "outcome": "failed", "finished_at": 10}
    best = ST.latest_by_unit([e], _split_units())
    assert best["f.py[light]"] == (None, False)
    assert best["f.py[heavy]"] == (None, False)


def test_a_light_pass_is_never_evidence_about_the_heavy_unit():
    """Evidence flows only from the superset down. If it flowed sideways, a
    split would be a way to make an unrun test look green — the one thing
    the registry must not be able to do."""
    e = {"file": "f.py", "unit": "f.py[light]", "outcome": "passed",
         "finished_at": 10}
    best = ST.latest_by_unit([e], _split_units())
    assert best["f.py[light]"] == (e, False)
    assert best["f.py[heavy]"] == (None, False)


def test_an_own_entry_beats_an_inherited_one_when_it_is_newer():
    whole = {"file": "f.py", "outcome": "passed", "finished_at": 10}
    own = {"file": "f.py", "unit": "f.py[heavy]", "outcome": "failed",
           "finished_at": 20}
    best = ST.latest_by_unit([whole, own], _split_units())
    assert best["f.py[heavy]"] == (own, False)
    assert best["f.py[light]"] == (whole, True)


def test_an_inherited_row_does_not_lend_the_file_wall_clock_to_the_unit():
    """A `[light]` unit that inherited a 900 s whole-file pass must not be
    estimated at 900 s — that is the exact number the split exists to stop
    believing. It falls back to the unmeasured prior instead."""
    rows = [{"unit": "f.py[light]", "file": "f.py", "kind": ST.LIGHT,
             "unit_tests": [], "state": "unknown", "finished_at": None,
             "seconds": 900.0, "inherited": True},
            {"unit": "g.py", "file": "g.py", "kind": ST.WHOLE, "unit_tests": [],
             "state": "unknown", "finished_at": None, "seconds": 20.0,
             "inherited": False}]
    # g's real 20 s beats light's *prior*; light is not treated as a 900 s file.
    assert ST.plan({"rows": rows}, 200.0, default_s=100.0) == ["g.py", "f.py[light]"]


# ------------------------------------------------------- status and report --

def test_status_counts_units_and_files_separately(tmp_path):
    td = _tests_dir_with(tmp_path, {"test_swe_a.py": ["test_p", "test_q"],
                                    "test_swe_b.py": ["test_r"]})
    units = ST.slow_tier_units(td, registry=_reg(**{"test_swe_a.py": ["test_q"]}))
    st = ST.status(ledger_path=str(tmp_path / "absent.jsonl"), tests_dir=td,
                   digest="D", units=units)
    assert st["n_files"] == 2 and st["n_units"] == 3
    assert st["coverage"] == 0.0 and st["n_registry_errors"] == 0
    assert sorted(r["unit"] for r in st["rows"]) == [
        "test_swe_a.py[heavy]", "test_swe_a.py[light]", "test_swe_b.py"]


def test_report_text_says_units_only_when_something_is_split(tmp_path):
    td = _tests_dir_with(tmp_path, {"test_swe_a.py": ["test_p", "test_q"]})
    plain = ST.status(ledger_path=str(tmp_path / "a.jsonl"), tests_dir=td,
                      digest="D", units=ST.slow_tier_units(td, registry={"heavy": {}}))
    assert "1 files," in ST.report_text(plain)
    split = ST.status(ledger_path=str(tmp_path / "a.jsonl"), tests_dir=td, digest="D",
                      units=ST.slow_tier_units(td, registry=_reg(**{"test_swe_a.py": ["test_q"]})))
    txt = ST.report_text(split)
    assert "1 files / 2 units," in txt
    assert "2 unit(s) are NOT evidence" in txt
    assert "excludes: test_q" in txt


def test_report_text_never_hides_a_registry_error(tmp_path):
    """A registry error means the split a human asked for is NOT in effect
    and the recall percentage is over a different denominator than they
    think. Silence there is worse than the error."""
    td = _tests_dir_with(tmp_path, {"test_swe_a.py": ["test_p"]})
    units = ST.slow_tier_units(td, registry=_reg(**{"test_swe_a.py": ["test_gone"]}))
    st = ST.status(ledger_path=str(tmp_path / "a.jsonl"), tests_dir=td,
                   digest="D", units=units)
    assert st["n_registry_errors"] == 1
    txt = ST.report_text(st)
    assert "REGISTRY ERROR test_swe_a.py" in txt and "test_gone" in txt
    assert "running it whole" in txt


def test_run_slice_records_the_unit_and_keeps_file_a_filename(tmp_path):
    td = _tests_dir_with(tmp_path, {"test_swe_a.py": ["test_p", "test_q"]})
    root = tmp_path / "co"
    root.mkdir()
    (root / "a.py").write_text("v = 1\n")
    led = str(tmp_path / "l.jsonl")
    seen = []

    def runner(uid):
        seen.append(uid)
        return {"returncode": 0, "timed_out": False, "tail": ""}

    import json as _json
    reg = tmp_path / "units.json"
    reg.write_text(_json.dumps(_reg(**{"test_swe_a.py": ["test_q"]})))
    old = ST._UNITS_PATH
    ST._UNITS_PATH = str(reg)
    try:
        [e] = ST.run_slice(["test_swe_a.py[light]"], ledger_path=led,
                           whence_root=str(root), runner=runner,
                           clock=iter([1.0, 2.0]).__next__, tests_dir=td)
    finally:
        ST._UNITS_PATH = old
    assert seen == ["test_swe_a.py[light]"]
    assert e["unit"] == "test_swe_a.py[light]" and e["file"] == "test_swe_a.py"
    assert e["unit_kind"] == ST.LIGHT and e["unit_tests"] == ["test_q"]
    # and `latest_by_file` — every pre-433 reader — still finds it by filename
    assert ST.latest_by_file(ST.read_entries(led))["test_swe_a.py"]["unit_kind"] == ST.LIGHT


# --------------------------------------------------------- against the repo --

def test_the_live_registrys_declared_tests_all_exist():
    """A live-tree check with teeth: a rename in `harness/tests/` silently
    disables the split it belongs to (the file falls back to whole), which
    costs the coverage this mechanism was built to buy. The failure is loud
    here rather than a line nobody reads in a status report."""
    reg = ST.load_units_registry()
    assert not reg.get("_load_error"), "harness/tier-units.json is unreadable"
    for f, decl in (reg.get("heavy") or {}).items():
        names = ST.file_test_names(f)
        assert names is not None, "%s is unreadable" % f
        for t in decl.get("tests") or []:
            assert t in names, "%s declares heavy test %s, which is not in it" % (f, t)


def test_the_live_units_cover_every_slow_tier_file_exactly_once():
    units = ST.slow_tier_units()
    assert sorted(set(u["file"] for u in units)) == ST.slow_tier_files()
    assert len(set(u["id"] for u in units)) == len(units)
    for f in ST.slow_tier_files():
        kinds = sorted(u["kind"] for u in units if u["file"] == f)
        assert kinds in ([ST.WHOLE], sorted([ST.LIGHT, ST.HEAVY])), (f, kinds)


def test_the_campaign_file_is_split_and_its_light_unit_is_the_measured_one():
    """Round 433's subject, pinned. If somebody retires the split, this says
    so out loud rather than letting the tier quietly go back to a file that
    fits in no budget."""
    units = [u for u in ST.slow_tier_units() if u["file"] == "test_swe_campaign.py"]
    assert [u["kind"] for u in units] == [ST.LIGHT, ST.HEAVY]
    assert units[0]["tests"] == ["test_cli_runs_offline_stages_and_stops"]
    names = ST.file_test_names("test_swe_campaign.py")
    assert len(names) == 20 and units[0]["tests"][0] in names
