"""swe.killerrepin — the differential re-pin of a GENERATED oracle file.

Round 450 (language C). `languages/whence/tests/test_generated_killers.py`
says "do not edit by hand" and cannot be regenerated (the mutation JSONs its
killers came from are not kept), so when a deliberate language change moves
one of its expectations the only supported moves are "hand-edit the file that
says not to" or "delete the test". Both silently destroy the discrimination
the test exists for, and nothing in the repo would say so.

These tests cover the two properties that make the re-pin safe:

  * a pin is rewritten ONLY when the baseline tree reproduces its OLD
    expectation exactly, so the movement is attributable to the working-tree
    diff and to nothing else; and
  * the rewrite is byte-identical to what `killers.render_tests` would have
    generated, so a re-pinned file is a generated file.
"""
import os
import subprocess
import sys
import textwrap

sys.path.insert(0, os.path.dirname(os.path.dirname(os.path.abspath(__file__))))

import pytest

from swe import killerrepin, killers

FIXTURE = textwrap.dedent('''\
    """GENERATED by harness/swe/killers.py — do not edit by hand."""


    def test_kill_values_py_139_const_121():
        """mutant values.py:139:const#121: 12 -> 13 (line 139) — mutant gave {'kind': 'ok'}"""
        src = 'let v1 = [nosuch(1)]\\n'
        assert run(src) == {'kind': 'ok', 'vals': {'v1': '[miss]'}}


    def test_kill_interp_py_486_ifneg_150():
        """mutant interp.py:486:ifneg#150: negate if-condition (line 486) — mutant gave {'kind': 'crash'}"""
        src = 'print(1)\\n'
        assert run(src) == {'kind': 'ok', 'out': ['1']}
    ''')


def test_parse_pins_reads_the_generated_shape():
    pins = killerrepin.parse_pins(FIXTURE)
    assert [p.name for p in pins] == ["test_kill_values_py_139_const_121",
                                      "test_kill_interp_py_486_ifneg_150"]
    a, b = pins
    assert (a.path, a.lineno, a.desc) == ("values.py", 139, "12 -> 13")
    assert a.src == "let v1 = [nosuch(1)]\n"
    assert a.expected == {"kind": "ok", "vals": {"v1": "[miss]"}}
    assert (b.path, b.lineno, b.desc) == ("interp.py", 486, "negate if-condition")


def test_parse_pins_skips_anything_that_is_not_a_generated_killer():
    text = FIXTURE + textwrap.dedent('''

        def test_written_by_a_human():
            """not a mutant docstring"""
            assert 1 == 1


        def test_kill_no_assert():
            """mutant values.py:1:const#0: 1 -> 2 (line 1) — mutant gave {}"""
            src = 'x\\n'
        ''')
    assert len(killerrepin.parse_pins(text)) == 2


def test_rewrite_is_byte_identical_to_what_render_tests_would_emit():
    """A re-pinned file must still be a GENERATED file, or the next real
    regeneration produces a spurious diff."""
    pins = killerrepin.parse_pins(FIXTURE)
    new = {"kind": "ok", "vals": {"v1": '[miss "unbound name \'nosuch\'"]'}}
    out = killerrepin.rewrite(FIXTURE, [(pins[0], new)])
    assert "    assert run(src) == %r\n" % (new,) in out
    assert killerrepin.parse_pins(out)[0].expected == new
    # the untouched pin is untouched, to the byte
    assert killerrepin.parse_pins(out)[1].expected == pins[1].expected
    assert out.count("def test_kill_") == 2


def test_rewrite_applies_bottom_up_so_line_numbers_cannot_drift():
    """Both pins at once, with a replacement whose repr is much longer than
    the line it replaces. Applied top-down the second pin's recorded line
    range would already be stale."""
    pins = killerrepin.parse_pins(FIXTURE)
    long_ = {"kind": "ok", "vals": {"v1": "x" * 400}}
    out = killerrepin.rewrite(FIXTURE, [(pins[0], long_), (pins[1], long_)])
    got = killerrepin.parse_pins(out)
    assert [p.expected for p in got] == [long_, long_]


def test_moved_keys_names_the_leaf_that_moved():
    old = {"kind": "ok", "out": ["a"], "vals": {"v1": "1", "v2": "2"}}
    new = {"kind": "ok", "out": ["a"], "vals": {"v1": "9", "v2": "2"}}
    assert killerrepin.moved_keys(old, new) == ["vals.v1"]
    assert killerrepin.moved_keys(old, old) == []
    assert killerrepin.moved_keys(
        old, {"kind": "ok", "out": ["b"], "vals": old["vals"]}) == ["out[0]"]


def test_moved_keys_handles_a_length_change_without_pretending_to_align():
    assert killerrepin.moved_keys({"out": ["a"]}, {"out": ["a", "b"]}) == ["out"]


# --------------------------------------------------------------------------
# the live tree
# --------------------------------------------------------------------------

def _have_git_whence():
    if not os.path.isdir(os.path.join(killerrepin.WHENCE_ROOT, "whence")):
        return False
    r = subprocess.run(["git", "rev-parse", "--is-inside-work-tree"],
                       cwd=killerrepin.WHENCE_ROOT, capture_output=True)
    return r.returncode == 0


needs_tree = pytest.mark.skipif(not _have_git_whence(),
                                reason="no git checkout of languages/whence")


@needs_tree
def test_every_live_pin_holds_against_the_committed_tree():
    """The green-tree statement, and the one that makes `--write` meaningful:
    with the working tree and HEAD agreeing, EVERY pin must be `holds`. A
    `stale` here would mean the generated file is out of step with the
    interpreter for a reason nobody declared."""
    pins = killerrepin.parse_pins(
        open(killerrepin.TEST_PATH, encoding="utf-8").read())
    assert len(pins) > 40, "the generated file lost its pins"
    results = killerrepin.judge_all(pins, ref="HEAD")
    bad = [(p.name, v) for p, v, _, _ in results if v != "holds"]
    assert bad == [], bad


@needs_tree
def test_a_pin_the_baseline_cannot_reproduce_is_stale_and_is_not_written():
    """The refusal. A pin whose expectation neither tree produces is not a
    re-pin candidate — rewriting it would paste in today's output and call
    the result a regression pin."""
    pins = killerrepin.parse_pins(
        open(killerrepin.TEST_PATH, encoding="utf-8").read())[:1]
    pins[0].expected = {"kind": "ok", "out": ["nothing produces this"]}
    results = killerrepin.judge_all(pins, ref="HEAD")
    assert [v for _, v, _, _ in results] == ["stale"]


@needs_tree
def test_the_mutant_ids_in_the_generated_file_have_decayed():
    """Round 450's measurement, kept as an instrument rather than a sentence.

    The obvious way to verify a re-pin is "rebuild the mutant from its id and
    check the test still separates it". A mutant id is a LINE NUMBER plus a
    generation counter, both of which move whenever the mutated file is
    edited — and at round 450 NOT ONE of the pins resolved. This asserts the
    weak, durable half (the census runs and the ids are decayed rather than
    silently half-working); the exact number belongs in the round file, not
    in an assertion that a lucky edit could flip."""
    pins = killerrepin.parse_pins(
        open(killerrepin.TEST_PATH, encoding="utf-8").read())
    scores = killerrepin.audit_ids(pins)
    assert set(scores) == {p.name for p in pins}
    exact = [n for n, (e, _) in scores.items() if e == 1]
    assert len(exact) < len(pins) // 2, (
        "mutant ids resolve again (%d of %d) — if a campaign has re-pinned "
        "them, killerrepin can verify by rebuild and this test should say so"
        % (len(exact), len(pins)))
