"""Tests for `harness/swe/slowtier.py` — the recorded, resumable slow-tier
ledger (round 341, SWE-loop D).

Deliberately NOT named `test_swe_*.py`: `harness/tests/conftest.py` marks
every file with that prefix `swe_slow`, and a module whose whole purpose is
to make the slow tier visible to the FAST health check must itself run in
the fast tier. Every test here injects a fake runner and a fake clock —
nothing shells out to pytest, nothing reads the real whence checkout except
the two tests that say so in their names.
"""
import json
import os
import sys

sys.path.insert(0, os.path.dirname(os.path.dirname(os.path.abspath(__file__))))

import swe.slowtier as ST


# ------------------------------------------------------------------ digest --

def test_digest_is_stable_and_content_sensitive(tmp_path):
    root = tmp_path / "co"
    (root / "whence").mkdir(parents=True)
    (root / "whence" / "interp.py").write_text("x = 1\n")
    (root / "whence" / "parser.py").write_text("y = 2\n")
    d1 = ST.checkout_digest(str(root))
    assert d1 == ST.checkout_digest(str(root))          # stable
    (root / "whence" / "interp.py").write_text("x = 2\n")
    assert ST.checkout_digest(str(root)) != d1          # content-sensitive


def test_digest_ignores_bytecode_caches_and_non_python(tmp_path):
    """A digest that moved every time the suite RAN would mark every result
    stale immediately — self-defeating. `__pycache__`/`.pytest_cache` are
    regenerated by merely running the tests, and a SPEC.md edit cannot
    move a line number in a `.py` source."""
    root = tmp_path / "co"
    (root / "whence").mkdir(parents=True)
    (root / "whence" / "interp.py").write_text("x = 1\n")
    d = ST.checkout_digest(str(root))
    (root / "whence" / "__pycache__").mkdir()
    (root / "whence" / "__pycache__" / "interp.cpython-311.pyc").write_bytes(b"\x00bytecode")
    (root / ".pytest_cache").mkdir()
    (root / ".pytest_cache" / "junk.py").write_text("noise = 1\n")
    (root / "SPEC.md").write_text("# a doc edit\n")
    (root / ".venv").mkdir()
    (root / ".venv" / "lib.py").write_text("vendored = 1\n")
    assert ST.checkout_digest(str(root)) == d


def test_digest_notices_a_renamed_file(tmp_path):
    """Path names are folded in, not just contents — moving a module is a
    change that shifts what a scratch copy contains."""
    root = tmp_path / "co"
    root.mkdir()
    (root / "a.py").write_text("v = 1\n")
    d = ST.checkout_digest(str(root))
    os.rename(str(root / "a.py"), str(root / "b.py"))
    assert ST.checkout_digest(str(root)) != d


# ------------------------------------------------------------------ ledger --

def test_slow_tier_files_matches_conftests_own_rule():
    """`conftest.pytest_collection_modifyitems` marks exactly
    `basename.startswith("test_swe_")`. If that rule ever changes, this
    module's whole notion of 'the tier' silently drifts from pytest's."""
    src = open(os.path.join(os.path.dirname(os.path.abspath(__file__)),
                            "conftest.py"), encoding="utf-8").read()
    assert 'startswith("test_swe_")' in src
    files = ST.slow_tier_files()
    assert files and all(f.startswith("test_swe_") and f.endswith(".py") for f in files)
    assert "test_slowtier.py" not in files          # this file is fast-tier


def test_latest_by_file_takes_the_newest_entry(tmp_path):
    p = str(tmp_path / "l.jsonl")
    ST.append_entry(p, {"file": "test_swe_a.py", "outcome": "failed", "finished_at": 10})
    ST.append_entry(p, {"file": "test_swe_a.py", "outcome": "passed", "finished_at": 20})
    ST.append_entry(p, {"file": "test_swe_b.py", "outcome": "failed", "finished_at": 15})
    best = ST.latest_by_file(ST.read_entries(p))
    assert best["test_swe_a.py"]["outcome"] == "passed"
    assert best["test_swe_b.py"]["outcome"] == "failed"


def test_a_torn_last_line_is_skipped_not_fatal(tmp_path):
    """A round killed mid-append (round 338/339 both died at max-turns)
    leaves a partial line. Absence of a record is handled by rule 1; a
    crash here would take the whole health check down with it."""
    p = str(tmp_path / "l.jsonl")
    ST.append_entry(p, {"file": "test_swe_a.py", "outcome": "passed", "finished_at": 1})
    with open(p, "a") as f:
        f.write('{"file": "test_swe_b.py", "outc')
    entries = ST.read_entries(p)
    assert len(entries) == 1 and entries[0]["file"] == "test_swe_a.py"


def test_read_entries_on_a_missing_ledger_is_empty_not_an_error(tmp_path):
    assert ST.read_entries(str(tmp_path / "nope.jsonl")) == []


# -------------------------------------------------------- the fail-closed --

def test_no_entry_is_unknown_never_pass():
    """Rule 1. The whole point: a tier nobody ran must not read as green,
    which is exactly how round 338's five failures stayed invisible."""
    assert ST.classify(None, "abc") == "unknown"


def test_a_pass_against_a_different_checkout_is_stale_not_fresh():
    """Rule 2."""
    e = {"outcome": "passed", "checkout_digest": "old", "checkout_stable": True}
    assert ST.classify(e, "new") == "stale_checkout"
    assert ST.classify(e, "old") == "fresh_pass"


def test_a_result_computed_while_the_checkout_moved_is_never_evidence():
    """Rule 3, and round 341's own finding made mechanical: a PASS produced
    while another round was editing `languages/whence/` is no more
    trustworthy than the FAIL it might equally have produced."""
    for outcome in ("passed", "failed"):
        e = {"outcome": outcome, "checkout_digest": "same", "checkout_stable": False}
        assert ST.classify(e, "same") == "raced"
    assert "raced" not in ST.CONCLUSIVE


def test_an_unrecognised_outcome_falls_back_to_unknown():
    """Fail-closed on the default branch too — a `timeout` outcome is not
    a pass and must not be counted as one."""
    e = {"outcome": "timeout", "checkout_digest": "d", "checkout_stable": True}
    assert ST.classify(e, "d") == "unknown"


# ------------------------------------------------------------------ status --

def _status_over(tmp_path, entries, files, digest="D"):
    tests = tmp_path / "t"
    tests.mkdir(exist_ok=True)
    for f in files:
        (tests / f).write_text("")
    p = str(tmp_path / "l.jsonl")
    for e in entries:
        ST.append_entry(p, e)
    return ST.status(ledger_path=p, tests_dir=str(tests), digest=digest)


def test_status_reports_its_own_recall(tmp_path):
    """Round 339's rule: a checker nobody is watching must report the size
    of its own blind spot, or a partial sweep reads as a complete one."""
    st = _status_over(tmp_path, [
        {"file": "test_swe_a.py", "outcome": "passed", "finished_at": 5,
         "checkout_digest": "D", "checkout_stable": True},
        {"file": "test_swe_b.py", "outcome": "passed", "finished_at": 5,
         "checkout_digest": "OLD", "checkout_stable": True},
    ], ["test_swe_a.py", "test_swe_b.py", "test_swe_c.py"])
    assert st["n_files"] == 3 and st["n_conclusive"] == 1
    assert abs(st["coverage"] - 1.0 / 3) < 1e-9
    by = dict((r["file"], r["state"]) for r in st["rows"])
    assert by == {"test_swe_a.py": "fresh_pass",
                  "test_swe_b.py": "stale_checkout",
                  "test_swe_c.py": "unknown"}


def test_status_counts_only_fresh_failures_as_failing(tmp_path):
    """A failure recorded against a checkout that has since changed is a
    lead, not a verdict — round 338's five failures need re-running, not
    re-asserting."""
    st = _status_over(tmp_path, [
        {"file": "test_swe_a.py", "outcome": "failed", "finished_at": 5,
         "checkout_digest": "D", "checkout_stable": True},
        {"file": "test_swe_b.py", "outcome": "failed", "finished_at": 5,
         "checkout_digest": "OLD", "checkout_stable": True},
    ], ["test_swe_a.py", "test_swe_b.py"])
    assert st["n_failing"] == 1


def test_report_text_names_the_uncovered_count(tmp_path):
    st = _status_over(tmp_path, [], ["test_swe_a.py", "test_swe_b.py"])
    txt = ST.report_text(st)
    assert "0% recall" in txt and "2 file(s) are NOT evidence" in txt
    assert "unknown" in txt


# -------------------------------------------------------------------- plan --

def test_plan_runs_the_least_covered_first(tmp_path):
    st = _status_over(tmp_path, [
        {"file": "test_swe_a.py", "outcome": "passed", "finished_at": 100,
         "checkout_digest": "D", "checkout_stable": True, "seconds": 10},
        {"file": "test_swe_b.py", "outcome": "passed", "finished_at": 50,
         "checkout_digest": "D", "checkout_stable": True, "seconds": 10},
    ], ["test_swe_a.py", "test_swe_b.py", "test_swe_c.py"])
    assert ST.plan(st, budget_s=10_000, default_s=10) == [
        "test_swe_c.py",     # no evidence at all -> first
        "test_swe_b.py",     # then oldest
        "test_swe_a.py",
    ]


def test_plan_respects_the_budget_and_uses_measured_costs(tmp_path):
    st = _status_over(tmp_path, [
        {"file": "test_swe_a.py", "outcome": "passed", "finished_at": 1,
         "checkout_digest": "D", "checkout_stable": True, "seconds": 30},
        {"file": "test_swe_b.py", "outcome": "passed", "finished_at": 2,
         "checkout_digest": "D", "checkout_stable": True, "seconds": 900},
        {"file": "test_swe_c.py", "outcome": "passed", "finished_at": 3,
         "checkout_digest": "D", "checkout_stable": True, "seconds": 30},
    ], ["test_swe_a.py", "test_swe_b.py", "test_swe_c.py"])
    # b's measured 900s does not fit beside a; c does.
    assert ST.plan(st, budget_s=100) == ["test_swe_a.py", "test_swe_c.py"]


def test_a_file_slower_than_any_budget_is_still_eventually_run(tmp_path):
    """The silent-truncation guard. If an over-budget file were simply
    skipped forever it would be permanently `unknown` while the report
    claimed progress — round 340's "no silent caps" lesson."""
    st = _status_over(tmp_path, [
        {"file": "test_swe_huge.py", "outcome": "passed", "finished_at": 1,
         "checkout_digest": "D", "checkout_stable": True, "seconds": 5000},
    ], ["test_swe_huge.py"])
    assert ST.plan(st, budget_s=60) == ["test_swe_huge.py"]


def test_plan_is_empty_only_when_there_is_nothing_to_run(tmp_path):
    st = _status_over(tmp_path, [], [])
    assert ST.plan(st, budget_s=600) == []


# --------------------------------------------------------------- run_slice --

def test_run_slice_records_one_entry_per_file_with_a_fake_runner(tmp_path):
    p = str(tmp_path / "l.jsonl")
    root = tmp_path / "co"
    (root).mkdir()
    (root / "a.py").write_text("v = 1\n")
    seen = []

    def runner(f):
        seen.append(f)
        return {"returncode": 0 if f.endswith("a.py") else 1,
                "timed_out": False, "tail": "output for " + f}

    ticks = iter([100.0, 130.0, 200.0, 260.0])
    written = ST.run_slice(["test_swe_a.py", "test_swe_b.py"], ledger_path=p,
                           whence_root=str(root), runner=runner,
                           clock=lambda: next(ticks))
    assert seen == ["test_swe_a.py", "test_swe_b.py"]
    assert [e["outcome"] for e in written] == ["passed", "failed"]
    assert [e["seconds"] for e in written] == [30.0, 60.0]
    assert all(e["checkout_stable"] for e in written)
    on_disk = ST.read_entries(p)
    assert len(on_disk) == 2 and on_disk[0]["file"] == "test_swe_a.py"


def test_run_slice_flags_a_checkout_that_moves_mid_run(tmp_path):
    """The mechanism behind four of round 338's five failures, caught and
    recorded instead of silently believed. The runner here edits the tree
    while it 'runs', exactly as a concurrent language(C) round does."""
    p = str(tmp_path / "l.jsonl")
    root = tmp_path / "co"
    root.mkdir()
    (root / "interp.py").write_text("v = 1\n")

    def runner(f):
        (root / "interp.py").write_text("# a concurrent round landed here\nv = 1\n")
        return {"returncode": 0, "timed_out": False, "tail": ""}

    written = ST.run_slice(["test_swe_a.py"], ledger_path=p, whence_root=str(root),
                           runner=runner, clock=iter([1.0, 2.0]).__next__)
    e = written[0]
    assert e["outcome"] == "passed"                       # pytest was happy
    assert e["checkout_stable"] is False                  # ...and it does not count
    assert e["checkout_digest"] != e["checkout_digest_after"]
    assert ST.classify(e, e["checkout_digest"]) == "raced"


def test_run_slice_records_a_timeout_as_a_timeout_not_a_failure(tmp_path):
    p = str(tmp_path / "l.jsonl")
    root = tmp_path / "co"
    root.mkdir()
    (root / "a.py").write_text("v = 1\n")
    written = ST.run_slice(["test_swe_a.py"], ledger_path=p, whence_root=str(root),
                           runner=lambda f: {"returncode": -9, "timed_out": True, "tail": ""},
                           clock=iter([1.0, 2.0]).__next__)
    assert written[0]["outcome"] == "timeout"
    assert ST.classify(written[0], written[0]["checkout_digest"]) == "unknown"


def test_entries_are_json_serialisable_and_append_only(tmp_path):
    p = str(tmp_path / "l.jsonl")
    root = tmp_path / "co"
    root.mkdir()
    (root / "a.py").write_text("v = 1\n")
    for _ in range(3):
        ST.run_slice(["test_swe_a.py"], ledger_path=p, whence_root=str(root),
                     runner=lambda f: {"returncode": 0, "timed_out": False, "tail": ""},
                     clock=iter([1.0, 2.0]).__next__)
    lines = open(p, encoding="utf-8").read().strip().splitlines()
    assert len(lines) == 3
    for l in lines:
        json.loads(l)


# --------------------------------------------------------- against the repo --

def test_the_real_slow_tier_is_the_files_round_338_measured():
    """A live-tree sanity check, deliberately a MEMBERSHIP assertion and
    not a count: the tier grows when a round adds a `test_swe_*.py`, and
    pinning `len(...)` here would be exactly the live-file aggregate pin
    round 340's next-steps item 4 warns against."""
    files = set(ST.slow_tier_files())
    for f in ("test_swe_alias_effects.py", "test_swe_campaign.py",
              "test_swe_repair.py", "test_swe_fuzz.py"):
        assert f in files, f


def test_the_real_checkout_digest_is_computable_and_short():
    d = ST.checkout_digest()
    assert isinstance(d, str) and len(d) == 16 and d == ST.checkout_digest()


# ------------------------------------------- the health-check integration --

def _fast_script():
    return os.path.join(os.path.dirname(os.path.dirname(os.path.abspath(__file__))),
                        "run_tests_fast.sh")


def test_fast_health_check_still_returns_pytests_own_exit_code():
    """Round 341 changed `run_tests_fast.sh` from `exec pytest` to
    run-then-report, which is exactly the shape that silently swallows an
    exit code. Both paths are exercised for real (collection only, so this
    stays a fast-tier test): a matching `-k` exits 0, a non-matching one
    exits pytest's own 5 (`NO_TESTS_COLLECTED`).

    Also asserts the slow-tier report is actually PRINTED — a diagnostic
    nobody sees is the failure mode this whole module exists to fix."""
    import subprocess
    ok = subprocess.run(["bash", _fast_script(), "--collect-only", "-q",
                         "-k", "test_digest_is_stable_and_content_sensitive"],
                        stdout=subprocess.PIPE, stderr=subprocess.STDOUT)
    assert ok.returncode == 0, ok.stdout[-2000:]
    assert b"slow tier:" in ok.stdout, ok.stdout[-2000:]

    none = subprocess.run(["bash", _fast_script(), "--collect-only", "-q",
                           "-k", "zzz_no_such_test_name_zzz"],
                          stdout=subprocess.PIPE, stderr=subprocess.STDOUT)
    assert none.returncode == 5, (none.returncode, none.stdout[-2000:])
    assert b"slow tier:" in none.stdout, none.stdout[-2000:]
