"""Tests for `harness/swe/slowtier.py` — the recorded, resumable slow-tier
ledger (round 341, SWE-loop D).

Deliberately NOT named `test_swe_*.py`: `harness/tests/conftest.py` marks
every file with that prefix `swe_slow`, and a module whose whole purpose is
to make the slow tier visible to the FAST health check must itself run in
the fast tier. Every test here injects a fake runner and a fake clock —
nothing shells out to pytest, nothing reads the real whence checkout except
the two tests that say so in their names.
"""
import json
import os
import sys

sys.path.insert(0, os.path.dirname(os.path.dirname(os.path.abspath(__file__))))

import swe.slowtier as ST


# ------------------------------------------------------------------ digest --

def test_digest_is_stable_and_content_sensitive(tmp_path):
    root = tmp_path / "co"
    (root / "whence").mkdir(parents=True)
    (root / "whence" / "interp.py").write_text("x = 1\n")
    (root / "whence" / "parser.py").write_text("y = 2\n")
    d1 = ST.checkout_digest(str(root))
    assert d1 == ST.checkout_digest(str(root))          # stable
    (root / "whence" / "interp.py").write_text("x = 2\n")
    assert ST.checkout_digest(str(root)) != d1          # content-sensitive


def test_digest_ignores_bytecode_caches_and_documentation(tmp_path):
    """A digest that moved every time the suite RAN would mark every result
    stale immediately — self-defeating. `__pycache__`/`.pytest_cache` are
    regenerated by merely running the tests, and a SPEC.md edit cannot
    move a line number in a `.py` source.

    Round 361 renamed this from `..._and_non_python`: the digest now covers
    `.lang` too (`_SOURCE_EXTS`), so the excluded set is documentation and
    caches, not "everything that is not Python". Nothing this test asserts
    changed."""
    root = tmp_path / "co"
    (root / "whence").mkdir(parents=True)
    (root / "whence" / "interp.py").write_text("x = 1\n")
    d = ST.checkout_digest(str(root))
    (root / "whence" / "__pycache__").mkdir()
    (root / "whence" / "__pycache__" / "interp.cpython-311.pyc").write_bytes(b"\x00bytecode")
    (root / ".pytest_cache").mkdir()
    (root / ".pytest_cache" / "junk.py").write_text("noise = 1\n")
    (root / "SPEC.md").write_text("# a doc edit\n")
    (root / ".venv").mkdir()
    (root / ".venv" / "lib.py").write_text("vendored = 1\n")
    assert ST.checkout_digest(str(root)) == d


def test_digest_notices_a_renamed_file(tmp_path):
    """Path names are folded in, not just contents — moving a module is a
    change that shifts what a scratch copy contains."""
    root = tmp_path / "co"
    root.mkdir()
    (root / "a.py").write_text("v = 1\n")
    d = ST.checkout_digest(str(root))
    os.rename(str(root / "a.py"), str(root / "b.py"))
    assert ST.checkout_digest(str(root)) != d


# ------------------------------------------------------------------ ledger --

def test_slow_tier_files_matches_conftests_own_rule():
    """`conftest.pytest_collection_modifyitems` marks exactly
    `basename.startswith("test_swe_")`. If that rule ever changes, this
    module's whole notion of 'the tier' silently drifts from pytest's."""
    src = open(os.path.join(os.path.dirname(os.path.abspath(__file__)),
                            "conftest.py"), encoding="utf-8").read()
    assert 'startswith("test_swe_")' in src
    files = ST.slow_tier_files()
    assert files and all(f.startswith("test_swe_") and f.endswith(".py") for f in files)
    assert "test_slowtier.py" not in files          # this file is fast-tier


def test_latest_by_file_takes_the_newest_entry(tmp_path):
    p = str(tmp_path / "l.jsonl")
    ST.append_entry(p, {"file": "test_swe_a.py", "outcome": "failed", "finished_at": 10})
    ST.append_entry(p, {"file": "test_swe_a.py", "outcome": "passed", "finished_at": 20})
    ST.append_entry(p, {"file": "test_swe_b.py", "outcome": "failed", "finished_at": 15})
    best = ST.latest_by_file(ST.read_entries(p))
    assert best["test_swe_a.py"]["outcome"] == "passed"
    assert best["test_swe_b.py"]["outcome"] == "failed"


def test_a_torn_last_line_is_skipped_not_fatal(tmp_path):
    """A round killed mid-append (round 338/339 both died at max-turns)
    leaves a partial line. Absence of a record is handled by rule 1; a
    crash here would take the whole health check down with it."""
    p = str(tmp_path / "l.jsonl")
    ST.append_entry(p, {"file": "test_swe_a.py", "outcome": "passed", "finished_at": 1})
    with open(p, "a") as f:
        f.write('{"file": "test_swe_b.py", "outc')
    entries = ST.read_entries(p)
    assert len(entries) == 1 and entries[0]["file"] == "test_swe_a.py"


def test_read_entries_on_a_missing_ledger_is_empty_not_an_error(tmp_path):
    assert ST.read_entries(str(tmp_path / "nope.jsonl")) == []


# -------------------------------------------------------- the fail-closed --

def test_no_entry_is_unknown_never_pass():
    """Rule 1. The whole point: a tier nobody ran must not read as green,
    which is exactly how round 338's five failures stayed invisible."""
    assert ST.classify(None, "abc") == "unknown"


def test_a_pass_against_a_different_checkout_is_stale_not_fresh():
    """Rule 2."""
    e = {"outcome": "passed", "checkout_digest": "old", "checkout_stable": True}
    assert ST.classify(e, "new") == "stale_checkout"
    assert ST.classify(e, "old") == "fresh_pass"


def test_a_result_computed_while_the_checkout_moved_is_never_evidence():
    """Rule 3, and round 341's own finding made mechanical: a PASS produced
    while another round was editing `languages/whence/` is no more
    trustworthy than the FAIL it might equally have produced."""
    for outcome in ("passed", "failed"):
        e = {"outcome": outcome, "checkout_digest": "same", "checkout_stable": False}
        assert ST.classify(e, "same") == "raced"
    assert "raced" not in ST.CONCLUSIVE


def test_an_unrecognised_outcome_falls_back_to_unknown():
    """Fail-closed on the default branch too — a `timeout` outcome is not
    a pass and must not be counted as one."""
    e = {"outcome": "timeout", "checkout_digest": "d", "checkout_stable": True}
    assert ST.classify(e, "d") == "unknown"


# ------------------------------------------------------------------ status --

def _status_over(tmp_path, entries, files, digest="D"):
    tests = tmp_path / "t"
    tests.mkdir(exist_ok=True)
    for f in files:
        (tests / f).write_text("")
    p = str(tmp_path / "l.jsonl")
    for e in entries:
        # Round 343: these entries are about SUBJECT staleness, so stamp them
        # with the harness digest they would really have been written with.
        # Without it every one classifies `unstamped` and the tests below stop
        # testing what they were written to test — a schema change silently
        # neutering the suite that guards it.
        e.setdefault("dep_digests",
                     ST.dep_digests(e["file"], tests_dir=str(tests)))
        ST.append_entry(p, e)
    return ST.status(ledger_path=p, tests_dir=str(tests), digest=digest)


def test_status_reports_its_own_recall(tmp_path):
    """Round 339's rule: a checker nobody is watching must report the size
    of its own blind spot, or a partial sweep reads as a complete one."""
    st = _status_over(tmp_path, [
        {"file": "test_swe_a.py", "outcome": "passed", "finished_at": 5,
         "checkout_digest": "D", "checkout_stable": True},
        {"file": "test_swe_b.py", "outcome": "passed", "finished_at": 5,
         "checkout_digest": "OLD", "checkout_stable": True},
    ], ["test_swe_a.py", "test_swe_b.py", "test_swe_c.py"])
    assert st["n_files"] == 3 and st["n_conclusive"] == 1
    assert abs(st["coverage"] - 1.0 / 3) < 1e-9
    by = dict((r["file"], r["state"]) for r in st["rows"])
    assert by == {"test_swe_a.py": "fresh_pass",
                  "test_swe_b.py": "stale_checkout",
                  "test_swe_c.py": "unknown"}


def test_status_counts_only_fresh_failures_as_failing(tmp_path):
    """A failure recorded against a checkout that has since changed is a
    lead, not a verdict — round 338's five failures need re-running, not
    re-asserting."""
    st = _status_over(tmp_path, [
        {"file": "test_swe_a.py", "outcome": "failed", "finished_at": 5,
         "checkout_digest": "D", "checkout_stable": True},
        {"file": "test_swe_b.py", "outcome": "failed", "finished_at": 5,
         "checkout_digest": "OLD", "checkout_stable": True},
    ], ["test_swe_a.py", "test_swe_b.py"])
    assert st["n_failing"] == 1


def test_report_text_names_the_uncovered_count(tmp_path):
    st = _status_over(tmp_path, [], ["test_swe_a.py", "test_swe_b.py"])
    txt = ST.report_text(st)
    assert "0% recall" in txt and "2 file(s) are NOT evidence" in txt
    assert "unknown" in txt


# -------------------------------------------------------------------- plan --

def test_plan_runs_the_least_covered_first(tmp_path):
    st = _status_over(tmp_path, [
        {"file": "test_swe_a.py", "outcome": "passed", "finished_at": 100,
         "checkout_digest": "D", "checkout_stable": True, "seconds": 10},
        {"file": "test_swe_b.py", "outcome": "passed", "finished_at": 50,
         "checkout_digest": "D", "checkout_stable": True, "seconds": 10},
    ], ["test_swe_a.py", "test_swe_b.py", "test_swe_c.py"])
    assert ST.plan(st, budget_s=10_000, default_s=10) == [
        "test_swe_c.py",     # no evidence at all -> first
        "test_swe_b.py",     # then oldest
        "test_swe_a.py",
    ]


def test_plan_respects_the_budget_and_uses_measured_costs(tmp_path):
    st = _status_over(tmp_path, [
        {"file": "test_swe_a.py", "outcome": "passed", "finished_at": 1,
         "checkout_digest": "D", "checkout_stable": True, "seconds": 30},
        {"file": "test_swe_b.py", "outcome": "passed", "finished_at": 2,
         "checkout_digest": "D", "checkout_stable": True, "seconds": 900},
        {"file": "test_swe_c.py", "outcome": "passed", "finished_at": 3,
         "checkout_digest": "D", "checkout_stable": True, "seconds": 30},
    ], ["test_swe_a.py", "test_swe_b.py", "test_swe_c.py"])
    # b's measured 900s does not fit beside a; c does.
    assert ST.plan(st, budget_s=100) == ["test_swe_a.py", "test_swe_c.py"]


def test_a_file_slower_than_any_budget_is_still_eventually_run(tmp_path):
    """The silent-truncation guard. If an over-budget file were simply
    skipped forever it would be permanently `unknown` while the report
    claimed progress — round 340's "no silent caps" lesson."""
    st = _status_over(tmp_path, [
        {"file": "test_swe_huge.py", "outcome": "passed", "finished_at": 1,
         "checkout_digest": "D", "checkout_stable": True, "seconds": 5000},
    ], ["test_swe_huge.py"])
    assert ST.plan(st, budget_s=60) == ["test_swe_huge.py"]


def test_plan_is_empty_only_when_there_is_nothing_to_run(tmp_path):
    st = _status_over(tmp_path, [], [])
    assert ST.plan(st, budget_s=600) == []


# --------------------------------------------------------------- run_slice --

def test_run_slice_records_one_entry_per_file_with_a_fake_runner(tmp_path):
    p = str(tmp_path / "l.jsonl")
    root = tmp_path / "co"
    (root).mkdir()
    (root / "a.py").write_text("v = 1\n")
    seen = []

    def runner(f):
        seen.append(f)
        return {"returncode": 0 if f.endswith("a.py") else 1,
                "timed_out": False, "tail": "output for " + f}

    ticks = iter([100.0, 130.0, 200.0, 260.0])
    written = ST.run_slice(["test_swe_a.py", "test_swe_b.py"], ledger_path=p,
                           whence_root=str(root), runner=runner,
                           clock=lambda: next(ticks))
    assert seen == ["test_swe_a.py", "test_swe_b.py"]
    assert [e["outcome"] for e in written] == ["passed", "failed"]
    assert [e["seconds"] for e in written] == [30.0, 60.0]
    assert all(e["checkout_stable"] for e in written)
    on_disk = ST.read_entries(p)
    assert len(on_disk) == 2 and on_disk[0]["file"] == "test_swe_a.py"


def test_run_slice_flags_a_checkout_that_moves_mid_run(tmp_path):
    """The mechanism behind four of round 338's five failures, caught and
    recorded instead of silently believed. The runner here edits the tree
    while it 'runs', exactly as a concurrent language(C) round does."""
    p = str(tmp_path / "l.jsonl")
    root = tmp_path / "co"
    root.mkdir()
    (root / "interp.py").write_text("v = 1\n")

    def runner(f):
        (root / "interp.py").write_text("# a concurrent round landed here\nv = 1\n")
        return {"returncode": 0, "timed_out": False, "tail": ""}

    written = ST.run_slice(["test_swe_a.py"], ledger_path=p, whence_root=str(root),
                           runner=runner, clock=iter([1.0, 2.0]).__next__)
    e = written[0]
    assert e["outcome"] == "passed"                       # pytest was happy
    assert e["checkout_stable"] is False                  # ...and it does not count
    assert e["checkout_digest"] != e["checkout_digest_after"]
    assert ST.classify(e, e["checkout_digest"]) == "raced"


def test_run_slice_records_a_timeout_as_a_timeout_not_a_failure(tmp_path):
    p = str(tmp_path / "l.jsonl")
    root = tmp_path / "co"
    root.mkdir()
    (root / "a.py").write_text("v = 1\n")
    written = ST.run_slice(["test_swe_a.py"], ledger_path=p, whence_root=str(root),
                           runner=lambda f: {"returncode": -9, "timed_out": True, "tail": ""},
                           clock=iter([1.0, 2.0]).__next__)
    assert written[0]["outcome"] == "timeout"
    assert ST.classify(written[0], written[0]["checkout_digest"]) == "unknown"


def test_entries_are_json_serialisable_and_append_only(tmp_path):
    p = str(tmp_path / "l.jsonl")
    root = tmp_path / "co"
    root.mkdir()
    (root / "a.py").write_text("v = 1\n")
    for _ in range(3):
        ST.run_slice(["test_swe_a.py"], ledger_path=p, whence_root=str(root),
                     runner=lambda f: {"returncode": 0, "timed_out": False, "tail": ""},
                     clock=iter([1.0, 2.0]).__next__)
    lines = open(p, encoding="utf-8").read().strip().splitlines()
    assert len(lines) == 3
    for l in lines:
        json.loads(l)


# --------------------------------------------------------- against the repo --

def test_the_real_slow_tier_is_the_files_round_338_measured():
    """A live-tree sanity check, deliberately a MEMBERSHIP assertion and
    not a count: the tier grows when a round adds a `test_swe_*.py`, and
    pinning `len(...)` here would be exactly the live-file aggregate pin
    round 340's next-steps item 4 warns against."""
    files = set(ST.slow_tier_files())
    for f in ("test_swe_alias_effects.py", "test_swe_campaign.py",
              "test_swe_repair.py", "test_swe_fuzz.py"):
        assert f in files, f


def test_the_real_checkout_digest_is_computable_and_short():
    d = ST.checkout_digest()
    assert isinstance(d, str) and len(d) == 16 and d == ST.checkout_digest()


# ------------------------------------------- the health-check integration --

def _fast_script():
    return os.path.join(os.path.dirname(os.path.dirname(os.path.abspath(__file__))),
                        "run_tests_fast.sh")


def test_fast_health_check_still_returns_pytests_own_exit_code():
    """Round 341 changed `run_tests_fast.sh` from `exec pytest` to
    run-then-report, which is exactly the shape that silently swallows an
    exit code. Both paths are exercised for real (collection only, so this
    stays a fast-tier test): a matching `-k` exits 0, a non-matching one
    exits pytest's own 5 (`NO_TESTS_COLLECTED`).

    Also asserts the slow-tier report is actually PRINTED — a diagnostic
    nobody sees is the failure mode this whole module exists to fix."""
    import subprocess
    ok = subprocess.run(["bash", _fast_script(), "--collect-only", "-q",
                         "-k", "test_digest_is_stable_and_content_sensitive"],
                        stdout=subprocess.PIPE, stderr=subprocess.STDOUT)
    assert ok.returncode == 0, ok.stdout[-2000:]
    assert b"slow tier:" in ok.stdout, ok.stdout[-2000:]

    none = subprocess.run(["bash", _fast_script(), "--collect-only", "-q",
                           "-k", "zzz_no_such_test_name_zzz"],
                          stdout=subprocess.PIPE, stderr=subprocess.STDOUT)
    assert none.returncode == 5, (none.returncode, none.stdout[-2000:])
    assert b"slow tier:" in none.stdout, none.stdout[-2000:]


# ------------------------------------------------------- harness deps (343) --
#
# Round 341's item 2: `checkout_digest` stamps the SUBJECT, so an entry stayed
# `fresh_pass` after the test file — or the `swe/` module under it — was
# rewritten. Round 343 adds a per-file dependency digest.

def test_dep_closure_is_the_test_plus_its_transitive_swe_imports():
    d = ST.harness_deps("test_swe_coverage.py")
    assert "tests/test_swe_coverage.py" in d
    assert "tests/conftest.py" in d                  # pytest loads it regardless
    assert "swe/coverage.py" in d
    assert "swe/proc.py" in d                        # transitive: coverage imports it
    assert "swe/__init__.py" in d                    # executed on package import
    assert "swe/campaign.py" not in d                # not reachable from this test


def test_dep_closure_follows_relative_and_function_scope_imports():
    """`swe/` uses both (`from . import killers as K`; `swe/coverage.py:499`
    imports `.fuzz` inside a function). A closure that missed either would
    under-report and call a stale result fresh."""
    d = set(ST.harness_deps("test_swe_equivalence.py"))
    assert "swe/killers.py" in d                     # `from .killers import ...`
    assert "swe/coverage.py" in d and "swe/triage.py" in d   # `from . import X as Y`
    assert "swe/fuzz.py" in d                        # function-scope in coverage.py


def test_closures_differ_per_file_which_is_the_whole_point():
    """A single digest over `harness/swe/` + `harness/tests/` — the literal
    shape round 341 proposed — would invalidate all 18 files on any harness
    edit. On a one-CPU box where the tier costs ~76 minutes and a round's
    budget is minutes, recall would reset faster than rounds could raise it.
    Per-file closures are what make the ledger able to accumulate at all."""
    small = ST.harness_deps("test_swe_proc.py")
    big = ST.harness_deps("test_swe_campaign.py")
    assert len(small) < len(big)
    assert set(small) < set(big) or "swe/proc.py" in big     # nested, not disjoint
    # slowtier.py is imported by no slow test, so editing IT invalidates none
    assert not any("slowtier" in p for p in big)


def test_a_blind_scan_falls_back_to_the_whole_package(tmp_path, monkeypatch):
    """Fail-closed floor: a `test_swe_*.py` resolving to NO swe module means
    the scan is blind (every slow test exists to exercise that package), so
    the closure widens to everything rather than narrowing to nothing."""
    td = tmp_path / "tests"
    td.mkdir()
    (td / "test_swe_blind.py").write_text("import os\n")     # no swe import
    d = ST.harness_deps("test_swe_blind.py", tests_dir=str(td))
    assert "swe/fuzz.py" in d and "swe/campaign.py" in d


def test_an_unparsable_dependency_falls_back_rather_than_crashing(tmp_path):
    td = tmp_path / "tests"
    td.mkdir()
    (td / "test_swe_broken.py").write_text("import swe.fuzz\ndef f(:\n")
    d = ST.harness_deps("test_swe_broken.py", tests_dir=str(td))
    assert "swe/fuzz.py" in d and "swe/campaign.py" in d      # whole package


def test_moved_deps_names_the_file_not_just_the_fact():
    """Round 341 asked for 'subject moved' and 'test moved' to stay
    distinguishable. Storing a digest PER PATH answers a sharper question:
    which one."""
    entry = {"dep_digests": {"swe/fuzz.py": "aaa", "tests/t.py": "bbb"}}
    assert ST.moved_deps(entry, {"swe/fuzz.py": "aaa", "tests/t.py": "bbb"}) == []
    assert ST.moved_deps(entry, {"swe/fuzz.py": "zzz", "tests/t.py": "bbb"}) \
        == ["swe/fuzz.py"]
    # an appeared/vanished dependency is a change to WHAT the test exercises
    assert ST.moved_deps(entry, {"swe/fuzz.py": "aaa"}) == ["tests/t.py"]
    assert ST.moved_deps(entry, dict(entry["dep_digests"], **{"swe/new.py": "c"})) \
        == ["swe/new.py"]


def _entry(**kw):
    e = {"file": "test_swe_x.py", "outcome": "passed", "checkout_digest": "D",
         "checkout_stable": True, "harness_stable": True,
         "dep_digests": {"swe/fuzz.py": "aaa"}}
    e.update(kw)
    return e


def test_classify_rejects_a_pass_whose_harness_moved():
    cur = {"swe/fuzz.py": "aaa"}
    assert ST.classify(_entry(), "D", cur) == "fresh_pass"
    assert ST.classify(_entry(), "D", {"swe/fuzz.py": "zzz"}) == "stale_harness"
    assert "stale_harness" not in ST.CONCLUSIVE


def test_classify_rejects_a_pre_343_entry_as_unstamped():
    """Fail-closed rule 5: an entry written before the harness was stamped
    says nothing about which harness produced it, and absence of evidence
    is not evidence (rule 1's own principle, applied to a schema change)."""
    old = _entry()
    del old["dep_digests"]
    assert ST.classify(old, "D", {"swe/fuzz.py": "aaa"}) == "unstamped"
    assert "unstamped" not in ST.CONCLUSIVE
    # ...and the round-341 caller, which passes no dep map, is unaffected
    assert ST.classify(old, "D") == "fresh_pass"


def test_a_harness_that_moved_mid_run_is_raced_like_the_checkout():
    """Rule 3 generalised: a result computed while its inputs moved is not
    evidence, whichever input moved."""
    assert ST.classify(_entry(harness_stable=False), "D", {"swe/fuzz.py": "aaa"}) \
        == "raced"
    # absent field defaults to stable, so round-341 entries are not all raced
    e = _entry(); del e["harness_stable"]
    assert ST.classify(e, "D", {"swe/fuzz.py": "aaa"}) == "fresh_pass"


def test_run_slice_stamps_both_digests_and_detects_a_harness_race(tmp_path):
    """The harness-race path, exercised the way round 340 exercised the
    subject race: mutate a real dependency from inside the injected runner,
    so the before/after scan straddles a genuine edit."""
    led = str(tmp_path / "l.jsonl")
    td = tmp_path / "tests"
    td.mkdir()
    (td / "test_swe_fake.py").write_text("import swe.proc\n")
    (td / "conftest.py").write_text("# c\n")
    target = os.path.join(ST.HARNESS_ROOT, "swe", "proc.py")
    original = open(target, "rb").read()

    calls = []

    def runner(f):
        calls.append(f)
        with open(target, "ab") as fh:               # a concurrent round, in effect
            fh.write(b"\n# round-343 transient\n")
        return {"returncode": 0, "timed_out": False, "tail": "ok"}

    try:
        [e] = ST.run_slice(["test_swe_fake.py"], ledger_path=led, runner=runner,
                           clock=lambda: 1.0, tests_dir=str(td))
    finally:
        with open(target, "wb") as fh:
            fh.write(original)
    assert calls == ["test_swe_fake.py"]
    # Round 361 bumped the schema to 3 (subject scope). The pin stays a
    # pin: an entry writer that stops stamping a version is how a
    # reader silently starts guessing which rules an entry obeyed.
    assert e["outcome"] == "passed" and e["schema"] == 3
    assert e["checkout_stable"] is True               # whence never moved
    assert e["harness_stable"] is False               # but swe/proc.py did
    assert "swe/proc.py" in e["dep_digests"]
    assert ST.classify(e, e["checkout_digest"], e["dep_digests"]) == "raced"


def test_status_rows_carry_the_dep_count_and_the_moved_list(tmp_path):
    led = str(tmp_path / "l.jsonl")
    st = ST.status(ledger_path=led)
    row = [r for r in st["rows"] if r["file"] == "test_swe_proc.py"][0]
    assert row["state"] == "unknown" and row["n_deps"] >= 3
    assert row["moved_deps"] == []                   # no entry -> nothing moved


def test_plan_prefers_the_cheapest_unmeasured_file_not_the_alphabetical_one():
    """With an empty ledger every estimate is `default_s`, so round 341's
    key degenerated to alphabetical and spent a whole first budget on
    `test_swe_alias_effects.py` (873 s measured, round 341) covering one
    file. The size prior is a TIE-break only."""
    st = ST.status(ledger_path=os.path.join(str(os.devnull), "absent"))
    picked = ST.plan(st, 900.0)
    assert picked and picked[0] != "test_swe_alias_effects.py"
    assert len(picked) > 1


def test_a_real_measurement_always_beats_the_size_prior():
    rows = [{"file": "big.py", "state": "unknown", "finished_at": None, "seconds": 5.0},
            {"file": "aaa.py", "state": "unknown", "finished_at": None, "seconds": None}]
    picked = ST.plan({"rows": rows}, 900.0, default_s=300.0)
    assert picked[0] == "big.py"                     # measured 5s beats prior 300s


# ------------------------------------------------- subject scope (round 361) --
#
# The subject half of the freshness gate. `checkout_digest` is one sha over
# the whole whence checkout, and 52% of the commits that move it touch
# nothing any slow-tier file imports. These tests pin the narrowing AND — the
# part that matters — every way it is refused.

import swe.readscope as RS


def _scoped_entry(dirs, digs, **kw):
    e = _entry(checkout_digest="OLD")
    e["subject_scope"] = {"ok": True, "dirs": list(dirs), "opaque": [],
                          "n_reads": len(dirs), "why": ""}
    e["subject_digests"] = dict(digs)
    e["schema"] = 3
    e.update(kw)
    return e


def test_a_pyc_read_is_evidence_about_its_source_not_about_pycache():
    """With a populated `__pycache__`, importing `whence.parser` opens the
    `.pyc` and never opens the `.py`. Recording the raw path would place the
    scope in a directory the digest ignores by construction."""
    assert RS.normalize_read("whence/__pycache__/parser.cpython-312.pyc") \
        == "whence/parser.py"
    assert RS.normalize_read("whence/parser.py") == "whence/parser.py"
    assert RS.normalize_read(".git/objects/ab/cdef") is None
    # a pyc whose SOURCE would still be ignored is not resurrected
    assert RS.normalize_read(".venv/__pycache__/x.cpython-312.pyc") is None


def test_scope_is_directories_not_files():
    """Rule 2. `list_example_files` shells `git ls-files`, so a NEW example
    changes what the corpus contains without any existing file being opened.
    A file-granular scope would be fail-open against exactly that."""
    assert RS.scope_dirs(["examples/self_eval.lang", "whence/parser.py"]) \
        == ["examples", "whence"]
    assert RS.scope_dirs(["run.py"]) == ["."]
    assert RS.scope_dirs([]) == []


def test_dir_digest_notices_an_added_file_of_any_extension(tmp_path):
    root = tmp_path / "co"
    (root / "examples").mkdir(parents=True)
    (root / "examples" / "self_eval.lang").write_text("guest = 1\n")
    d = RS.dir_digest(str(root), "examples")
    (root / "examples" / "new_case.lang").write_text("x\n")
    assert RS.dir_digest(str(root), "examples") != d
    assert RS.dir_digest(str(tmp_path), "nope") == "<missing>"


def test_dir_digest_is_not_recursive():
    """`scope_dirs` reports every directory actually read, so a subdirectory
    that matters appears on its own. Recursing would silently re-couple
    `whence/` to trees nothing in it reads."""
    import tempfile
    d = tempfile.mkdtemp()
    os.makedirs(os.path.join(d, "a", "b"))
    open(os.path.join(d, "a", "x.py"), "w").write("1")
    before = RS.dir_digest(d, "a")
    open(os.path.join(d, "a", "b", "y.py"), "w").write("1")
    assert RS.dir_digest(d, "a") == before


def test_a_checkout_move_outside_the_scope_is_scoped_not_stale():
    """Rule 7. The claim is weaker, so it gets its OWN state and its own
    counter — it is never folded into `CONCLUSIVE`."""
    e = _scoped_entry(["whence"], {"whence": "W1"})
    assert ST.classify(e, "NEW", {"swe/fuzz.py": "aaa"}, {"whence": "W1"}) \
        == "fresh_pass_scoped"
    assert "fresh_pass_scoped" not in ST.CONCLUSIVE
    assert "fresh_pass_scoped" in ST.SCOPED_CONCLUSIVE


def test_a_checkout_move_inside_the_scope_is_stale_subject():
    """Rule 8, and it names the directory rather than counting one."""
    e = _scoped_entry(["whence", "examples"],
                      {"whence": "W1", "examples": "E1"})
    cur = {"whence": "W1", "examples": "E2"}
    assert ST.classify(e, "NEW", {"swe/fuzz.py": "aaa"}, cur) == "stale_subject"
    assert "stale_subject" not in ST.CONCLUSIVE
    assert "stale_subject" not in ST.SCOPED_CONCLUSIVE
    assert ST.moved_scope(e, cur) == ["examples"]


def test_a_scoped_failure_is_still_counted_as_failing():
    """A weaker freshness claim does not make the red less red."""
    e = _scoped_entry(["whence"], {"whence": "W1"}, outcome="failed")
    assert ST.classify(e, "NEW", {"swe/fuzz.py": "aaa"}, {"whence": "W1"}) \
        == "fresh_fail_scoped"
    assert "fresh_fail_scoped" in ST.FAILING and "fresh_fail" in ST.FAILING


def test_an_opaque_run_can_never_narrow_anything():
    """Rule 9, half one. `swe/coverage.py` spawns a pytest over the real
    checkout; that child has no audit hook, so its reads are invisible and
    nothing may be narrowed on their account."""
    scope = {"ok": True, "dirs": ["whence"], "opaque": ["subprocess.Popen"],
             "n_reads": 3, "why": ""}
    assert not RS.scope_is_narrowable(scope)
    e = _scoped_entry(["whence"], {"whence": "W1"})
    e["subject_scope"] = scope
    assert ST.scope_digests_now(e) is None
    assert ST.classify(e, "NEW", {"swe/fuzz.py": "aaa"},
                       ST.scope_digests_now(e)) == "stale_checkout"


def test_a_missing_or_torn_scope_record_falls_back_to_rule_2(tmp_path):
    """Rule 9, half two: no observation is not a narrow observation."""
    missing = RS.read_scope_file(str(tmp_path / "absent.json"))
    assert missing["ok"] is False and missing["why"] == "missing"
    torn = tmp_path / "torn.json"
    torn.write_text('{"reads": ["whence/parser.py"], "opaqu')
    assert RS.read_scope_file(str(torn))["why"] == "unreadable"
    wrong = tmp_path / "wrong.json"
    wrong.write_text('{"reads": "not-a-list", "opaque": []}')
    assert RS.read_scope_file(str(wrong))["why"] == "malformed"
    for bad in (missing, RS.read_scope_file(str(torn)),
                RS.read_scope_file(str(wrong))):
        assert not RS.scope_is_narrowable(bad)


def test_a_pre_361_entry_is_gated_exactly_as_round_341_gated_it():
    """The compatibility floor: nothing already in the ledger becomes
    fresher because this round shipped."""
    old = _entry(checkout_digest="OLD")           # no subject_scope at all
    assert ST.scope_digests_now(old) is None
    assert ST.classify(old, "NEW", {"swe/fuzz.py": "aaa"},
                       ST.scope_digests_now(old)) == "stale_checkout"
    assert ST.classify(old, "OLD", {"swe/fuzz.py": "aaa"}) == "fresh_pass"


def test_an_empty_scope_is_a_real_measurement_not_a_missing_one():
    """A test that reads nothing under the checkout — `test_swe_triage.py`
    measured 0 reads — is immune to every whence edit, and that is a FINDING,
    not an absence of one."""
    e = _scoped_entry([], {})
    assert ST.scope_digests_now(e) == {}
    assert ST.classify(e, "ANYTHING", {"swe/fuzz.py": "aaa"}, {}) \
        == "fresh_pass_scoped"


def test_run_slice_records_the_scope_and_a_scopeless_runner_is_fail_closed(tmp_path):
    root = tmp_path / "co"
    (root / "whence").mkdir(parents=True)
    (root / "whence" / "interp.py").write_text("x = 1\n")
    (root / "examples").mkdir()
    (root / "examples" / "self_eval.lang").write_text("guest = 1\n")
    tests = tmp_path / "t"
    tests.mkdir()
    (tests / "test_swe_a.py").write_text("")
    (tests / "test_swe_b.py").write_text("")
    led = str(tmp_path / "l.jsonl")

    def runner(f):
        if f == "test_swe_a.py":
            return {"returncode": 0, "timed_out": False, "tail": "",
                    "scope": {"ok": True, "dirs": ["whence"], "opaque": [],
                              "n_reads": 1, "why": ""}}
        return {"returncode": 0, "timed_out": False, "tail": ""}   # no scope

    a, b = ST.run_slice(["test_swe_a.py", "test_swe_b.py"], ledger_path=led,
                        whence_root=str(root), runner=runner,
                        clock=lambda: 1.0, tests_dir=str(tests))
    assert a["schema"] == 3
    assert a["subject_digests"] == {"whence": RS.dir_digest(str(root), "whence")}
    # A runner that reports nothing is not a runner that reported "nothing".
    assert b["subject_digests"] is None
    assert b["subject_scope"]["why"] == "runner-gave-none"
    assert ST.classify(b, "NEW", b["dep_digests"], ST.scope_digests_now(b)) \
        == "stale_checkout"
    # ... and the one that DID report is unaffected by an edit outside it.
    (root / "examples" / "self_eval.lang").write_text("guest = 2\n")
    assert ST.classify(a, ST.checkout_digest(str(root)), a["dep_digests"],
                       ST.scope_digests_now(a, str(root))) == "fresh_pass_scoped"
    # ... and IS affected by one inside it.
    (root / "whence" / "interp.py").write_text("x = 2\n")
    assert ST.classify(a, ST.checkout_digest(str(root)), a["dep_digests"],
                       ST.scope_digests_now(a, str(root))) == "stale_subject"


def test_status_reports_the_two_recalls_separately(tmp_path):
    """Round 334's rule, applied here: three rounds of reported figures and
    `run_tests_fast.sh`'s printed line depend on what `n_conclusive` has
    meant since round 341, so the weaker number is a NEW field."""
    tests = tmp_path / "t"
    tests.mkdir()
    for f in ("test_swe_a.py", "test_swe_b.py"):
        (tests / f).write_text("")
    p = str(tmp_path / "l.jsonl")
    fresh = _entry(file="test_swe_a.py", checkout_digest="D")
    fresh["dep_digests"] = ST.dep_digests("test_swe_a.py", tests_dir=str(tests))
    scoped = _scoped_entry([], {}, file="test_swe_b.py")
    scoped["dep_digests"] = ST.dep_digests("test_swe_b.py", tests_dir=str(tests))
    for e in (fresh, scoped):
        ST.append_entry(p, e)
    st = ST.status(ledger_path=p, tests_dir=str(tests), digest="D")
    assert st["n_conclusive"] == 1 and st["n_scoped"] == 1
    assert st["coverage"] == 0.5 and st["coverage_scoped"] == 1.0
    txt = ST.report_text(st)
    assert "1 conclusive" in txt
    assert "conclusive WITHIN their measured read-scope only" in txt


def test_the_bootstrap_installs_the_hook_before_it_imports_pytest():
    """Ordering is the whole mechanism: `swe.*` and `whence.*` are read
    during pytest's own collection, so a hook installed afterwards sees
    nothing. Pinned by source order because there is no runtime observable
    for 'too late'."""
    src = RS.bootstrap_source("/tmp/root", "/tmp/out.json", ["-q", "x.py"])
    assert src.index("sys.addaudithook") < src.index("import pytest")
    assert src.index("atexit.register") < src.index("sys.addaudithook")
    assert "/tmp/root" in src and "/tmp/out.json" in src


def test_the_lang_extension_is_in_the_digest_and_docs_are_not(tmp_path):
    """Round 361's correction to round 341's `.py`-only rule.
    `examples/self_eval.lang` is the guest INTERPRETER, not documentation;
    three commits in this repo change a `.lang` and no `.py` at all."""
    root = tmp_path / "co"
    (root / "examples").mkdir(parents=True)
    (root / "examples" / "self_eval.lang").write_text("guest = 1\n")
    d = ST.checkout_digest(str(root))
    (root / "SPEC.md").write_text("# doc\n")
    (root / "README.txt").write_text("notes\n")
    assert ST.checkout_digest(str(root)) == d          # docs still excluded
    (root / "examples" / "self_eval.lang").write_text("guest = 2\n")
    assert ST.checkout_digest(str(root)) != d          # the guest is not a doc
