"""Fuzzing the Whence interpreter for totality violations.

Whence's central invariant (SPEC decision 2): the evaluator never raises for
user-level problems — every runtime error is a `miss` value. The only
exceptions allowed out of `Interpreter.run` are LexError and ParseError. So
the oracle is simple and strong: generate a random program, run it, and
anything else escaping (RecursionError, OverflowError, TypeError, ...) is a
bug. A second oracle checks a structural invariant: every bound value's
provenance node retains that very payload (`v.prov.value is v.payload`).

Pieces:
  ProgramGen(seed).program()   grammar-directed random program (plus stress
                               templates: deep nesting, big ints, parser depth)
  run_program(src)             in-process oracle with a SIGALRM timeout
  signature(outcome)           stable crash key: (exc type, innermost whence
                               function, message prefix)
  shrink(src, keep)            line ddmin + integer minimisation, keeps `keep`
                               (a predicate on the source) true
  fuzz(seed, n)                campaign: returns Campaign with unique crashers
"""

import os
import random
import signal
import subprocess
import sys
import time
import traceback

WHENCE_ROOT = os.path.normpath(os.path.join(
    os.path.dirname(os.path.abspath(__file__)), "..", "..", "languages", "whence"))


#: Name of the curation manifest `_copy_project` materialises into a copied
#: tree's `examples/`. Round 437 (SWE-loop D): `list_example_files` resolves
#: the curated corpus by shelling `git ls-files`, and
#: `swe.mutation._copy_project` deliberately EXCLUDES `.git` from every copy
#: it makes. So in a copied tree the git branch could not answer, the
#: function fell through to `os.listdir`, and the 14 gitignored `.lang`
#: files another process drops into `languages/whence/examples/` entered
#: every differential corpus built there — silently, because a widened
#: corpus produces more evidence, not an error. The manifest is how the
#: curation travels with the copy: it is a plain file, so a copy of a copy
#: inherits it from `shutil.copytree` at no cost.
CURATION_MANIFEST = ".curated-examples"

#: `example_curation` returns one of these as its second element. Callers
#: that build a differential corpus should record it: "which examples" is a
#: denominator, and a denominator whose provenance is unrecorded cannot be
#: compared across runs.
CURATION_SOURCES = ("git", "manifest", "listdir")


def _git_example_names(root):
    """Curated `examples/*.lang` names from `root`'s git index, or None.

    None means "git could not answer for this tree" — git missing, `root`
    outside any checkout, or `root` inside a checkout that tracks nothing
    under `examples/` (which is what an untracked COPY placed inside some
    other repo looks like). It is deliberately distinct from an empty list.
    """
    try:
        out = subprocess.run(
            ["git", "ls-files", "examples"], cwd=root,
            capture_output=True, text=True, timeout=10, check=True)
    except (OSError, subprocess.CalledProcessError, subprocess.TimeoutExpired):
        return None
    names = sorted(
        line.split("/", 1)[1] for line in out.stdout.splitlines()
        if line.startswith("examples/") and line.endswith(".lang"))
    return names or None


def _manifest_example_names(root):
    """Curated names from `<root>/examples/.curated-examples`, or None."""
    path = os.path.join(root, "examples", CURATION_MANIFEST)
    try:
        with open(path, encoding="utf-8") as f:
            lines = f.read().splitlines()
    except OSError:
        return None
    names = sorted(n for n in (l.strip() for l in lines)
                   if n and not n.startswith("#") and n.endswith(".lang"))
    return names or None


def write_example_curation(src_root, dst_root):
    """Materialise `src_root`'s example curation into the copy at `dst_root`.

    Called by `swe.mutation._copy_project`, the one place a tree loses its
    `.git`. No-ops when there is nothing to preserve (`dst_root` has no
    `examples/`, or `src_root` is not a checkout) and when `dst_root`
    already carries a manifest — a copy of a copy inherits its parent's,
    which is the whole point: the curation is decided ONCE, at the edge of
    the real checkout, and every later copy is downstream of that decision.

    Returns the manifest path if one was written, else None.
    """
    ex_dir = os.path.join(dst_root, "examples")
    if not os.path.isdir(ex_dir):
        return None
    path = os.path.join(ex_dir, CURATION_MANIFEST)
    if os.path.exists(path):
        return None
    names = _git_example_names(src_root) or _manifest_example_names(src_root)
    if names is None:
        return None
    body = ["# GENERATED by swe.fuzz.write_example_curation — do not edit by hand.",
            "# The curated examples/*.lang corpus of the checkout this tree was",
            "# copied from. `_copy_project` excludes `.git`, so this file is the",
            "# only thing that can still tell a curated example from a file another",
            "# process dropped into examples/. One name per line.",
            "# source: %s" % os.path.abspath(src_root)]
    body.extend(names)
    with open(path, "w", encoding="utf-8") as f:
        f.write("\n".join(body) + "\n")
    return path


def example_curation(root=WHENCE_ROOT):
    """`(names, source)` for the curated `examples/*.lang` corpus of `root`.

    `examples/` is not exclusively ours: a separate autonomous process
    sharing this repo (the Hermes gateway, see
    `project_hermes_gateway_shares_the_repo`) drops its own `.lang` files
    into this same directory, and `.gitignore` lists 14 of them by name. A
    plain `os.listdir` has no way to tell those apart from the real corpus,
    so only committed, curated examples may enter a differential-testing
    corpus — new example files a language(C) round adds show up
    automatically once committed, and any file another process drops in
    stays invisible until it is actually ours.

    Three resolutions, in order, each reported by name so a caller can
    record which one it got:

      "git"       `root` is a checkout and tracks examples: ask the index.
      "manifest"  `root` is a COPY carrying `.curated-examples`: the copy
                  inherited the decision the real checkout made.
      "listdir"   neither — the old behaviour, and the one that cannot tell
                  a curated example from a foreign one. Returned, not
                  raised, because a caller with no corpus at all is worse
                  off than one with an uncurated corpus it knows about.
    """
    names = _git_example_names(root)
    if names is not None:
        return names, "git"
    names = _manifest_example_names(root)
    if names is not None:
        return names, "manifest"
    ex_dir = os.path.join(root, "examples")
    return sorted(n for n in os.listdir(ex_dir) if n.endswith(".lang")), "listdir"


def list_example_files(root=WHENCE_ROOT):
    """Names of the CURATED `examples/*.lang` corpus, sorted.

    Thin wrapper over `example_curation`, which documents the three
    resolutions and why the curation exists at all. Kept because it is the
    call four corpus builders already make (`killers.corpus`,
    `oracles`, `oraclekill`, `exemptmap`) and its contract — a sorted list
    of names — has not changed.
    """
    return example_curation(root)[0]


def _import_whence(root=WHENCE_ROOT):
    """Import the whence package from `root` (default: the checkout)."""
    if root not in sys.path:
        sys.path.insert(0, root)
    from whence.interp import Interpreter          # noqa: E402
    from whence.lexer import LexError              # noqa: E402
    from whence.parser import ParseError           # noqa: E402
    from whence.values import Value, full_show     # noqa: E402
    return Interpreter, LexError, ParseError, Value, full_show


# --------------------------------------------------------------- generator --

BUILTIN_ARITY = {
    "print": 1, "len": 1, "range": (1, 2), "map": 2, "filter": 2, "fold": 3,
    "push": 2, "str": 1, "num": 1, "abs": 1, "sqrt": 1, "trunc": 1,
    "missed": 1,
    "reasons": 1, "note": 2, "contains": 2, "join": 2, "keys": 1, "merge": 2,
    "get": 2, "put": 3, "has": 2, "find": 2,
    "steps": (1, 2), "at": 2, "blame": 1, "diverge": (1, 2),
    "contrast": (1, 2),
    "guess": 3, "is_guess": 1, "confidence": 1, "sure": 2,
    # v0.14.8 (round 294): `rand()`, arity 0 — the ONLY zero-arity entry in
    # this table. `call()`'s generic fallback path (`n = ar` when `ar` is a
    # plain int, `args = [self.expr(...) for _ in range(n)]`) already
    # produces `range(0)` == `[]` and `args[:0] == []` with no special case
    # needed, so this is a pure table addition — round 299 (SWE-loop D),
    # closing round 294's own next-steps item 2.
    "rand": 0,
    # v0.12 (rounds 122-128), added to this table round 335 -- the LAST
    # three registered `whence/interp.py` builtins the generator could not
    # reach. Found by re-diffing this table's keys against
    # `interp._make_builtin_table()` (36 names), exactly the check round
    # 323's own next-steps item 3 asked the next SWE-loop(D) round to run
    # before assuming there were no gaps left. All three are ORDINARY
    # calls, not new syntax. Round 323 also recorded why a `shape`
    # DECLARATION stayed out of this grammar -- "the guest parser has
    # none" -- and that a type SPEC is a first-class VALUE anyway, so a
    # hand-built record literal reaches the whole structural-matching
    # engine without any `shape` statement (SPEC v0.12: "a record built
    # entirely by hand ... matches it exactly as one built from it").
    # The guest-parser half of that has been FALSE since round 338, which
    # taught `self_eval.lang`/`self_host.lang` the `shape` statement, and
    # `swe/guest.py`'s own docstring has said so ("that is now a GENERATOR
    # choice rather than a guest limitation") for nine rounds while this
    # comment still gave the old reason. Round 347 closes it: `_shape_decl`
    # below declares real shapes and `type_tag` puts their names in
    # `p: Type`/`-> Type` annotations.
    "matches": 2, "shapeof": 1, "typed": 3,
    # v0.29 (round 374): `show(v)`, arity 1 -- the 37th registered builtin
    # and, until round 380, the only one this table could not reach. Round
    # 335 closed this same gap by re-diffing the table's keys against
    # `interp._make_builtin_table()` and said so; a builtin registered
    # forty rounds later re-opened it, because nothing RE-RUNS that diff.
    # `test_generator_covers_every_registered_builtin` (round 380) does,
    # so the next 38th builtin fails a test instead of waiting for a
    # backlog item. Architecturally a plain total unary derive over the
    # payload (`derived("show", "", line, (v,), show_payload(v.payload))`,
    # never a miss, never higher-order), so `call()`'s generic fallback
    # covers it exactly as it covers `str`/`abs`/`trunc`.
    "show": 1,
    # v0.17 (round 318): `trunc(x)`, arity 1 -- a plain numeric builtin,
    # architecturally identical to the pre-existing `abs`/`sqrt` entries
    # (miss on a non-numeric argument, otherwise a total, pure derive of
    # the payload; `call()`'s generic fallback `args = [self.expr(...) for
    # _ in range(n)]` already covers it, same as `abs`/`sqrt`). Closes the
    # gap named in round 318's own next-steps item 6 and repeated in every
    # SWE-loop(D)-adjacent round's list since (319-322) — round 323
    # (SWE-loop D).
}
BINOPS = ["+", "-", "*", "/", "%", "==", "!=", "<", "<=", ">", ">=", "and", "or"]
STR_POOL = ["", "a", "ab", "3O", "42", " 7 ", "1_000", "nan", "inf", "-inf",
            "1e400", "1e5", "0x1f", "true", "let a", "a\\nb", "\\\\", "\\\"",
            "0.5", "-3", "+4", "٣", "1e-2", "let x", "call f", "literal"]
FIELD_POOL = ["a", "b", "c", "x", "name", "v"]
STEP_NAMES = ["let x", "literal", "call", "arg", "note k", "+", "let a", "if",
              "call go", "call even", "odd", "fold", "==", "arg acc"]
# v0.13 backlog (SPEC "Not done"): the grammar generated no `: Type`/`-> Type`
# annotations, so type-guard code paths (v0.12 params, v0.13 returns) were
# only ever exercised by the hand-written corpus, never by fuzz input. No
# `shape` names exist here (nothing declares one), so only primitive tags —
# the values flowing through are otherwise-untyped fuzz expressions, so a
# tag frequently WON'T match at runtime; that mismatch-as-miss path is
# exactly what needs exercising against fast/direct/trampoline + tail calls.
# The parenthesis two lines up stopped being true in round 347:
# `_shape_decl` declares shapes and `type_tag` draws from these tags AND
# from their names, so an annotation now also reaches
# `interp._closure_spec`'s NameRef branch (a shape looked up in the
# DEFINING env) instead of only its `A.Str` branch.
TYPE_TAGS = ("num", "str", "bool", "list", "record", "fn", "any")

# Round 347 (SWE-loop D). v0.12 gave annotations a shape NAME as well as a
# primitive tag; v0.13 resolved a `-> Shape` once at closure creation;
# v0.18 (round 342) made the type namespace obey the value namespace's
# scope rule; v0.19 (round 344) moved the PARAMETER half onto the same
# `_closure_spec` at the same moment. Not one of those four changes could
# be fuzzed, because 0 of 400 generated programs contained the word
# `shape` (measured round 347) — so `_closure_spec`'s NameRef branch, both
# of `_check_contract`'s pre-`_type_match` guards, and the guest's
# mirroring `resolve_spec`/`resolve_param_specs` were reachable ONLY from
# the hand-written corpus.
#
# Field types a generated `shape` may declare. Primitives only here; a
# shape field naming an EARLIER shape is drawn separately in
# `_shape_decl`, because "may only reference shapes declared earlier"
# (parser.py's `shape_scopes` comment) is a property of the declaration
# ORDER, not of this pool.
SHAPE_FIELD_TAGS = ("num", "str", "bool", "list", "record", "fn", "any")
# Literal source that really SATISFIES each primitive tag, so
# `_witness_for` can build a record a declared shape actually matches.
# Without witnesses every shape annotation would be a miss and the success
# path — the branch where `_check_contract` returns its input unchanged and
# leaves no node in the why-tree at all — would be dead, the same "the pass
# path would be near-dead" reasoning `call()` already applies to
# `matches`/`typed`.
SHAPE_WITNESS_LITERALS = {
    "num": ("1", "0.5", "-3"),
    "str": ('"3O"', '""'),
    "bool": ("true", "false"),
    "list": ("[]", "[1, 2]"),
    "record": ("@{}", "@{a: 1}"),
    "fn": ("fn(a) { a }",),
    "any": ("1", '"3O"', "true", "[]"),
}
# What an ordinary `let` shadowing a shape name inside a block binds
# instead (`_shadowed_shape_stmt`). Three outcomes on purpose: a non-spec
# (`3`, `"3O"`, `true`, `[1]`, a closure) reaches `_check_contract`'s
# `not _spec_ok` guard — round 344 measured that exact program raising
# `AttributeError` straight out of the interpreter before it added the
# guard; a malformed record spec (`@{a: 5}`) reaches the same guard through
# `_spec_ok`'s recursive half (round 335); and a WELL-FORMED but different
# spec (`@{a: "num"}`, `"str"`) reaches neither guard — it is the
# late-binding capture hazard round 342 §7 pinned, where the answer depends
# entirely on whether the spec was resolved in the DEFINING env (v0.19,
# correct) or in the CALLING env (v0.12-v0.18).
SHADOW_BINDINGS = ('3', '"3O"', 'true', '[1]', 'fn(a) { a }', '@{a: 5}',
                   '@{a: "num"}', '"str"', '"nosuch"')

# Round 336 (language C) found that a `-> Type` contract reached through a
# TAIL call was blamed outermost-first, and reported the OUTER call's line
# rather than the tail call's own — the same chain lifted out of tail
# position disagreed on both. Its next-steps item 1 named why no oracle
# caught it: `-> TAG` lands on ~25% of generated `fn`s (`maybe_ret_type`),
# but nothing ever shaped a body whose TAIL is a call to ANOTHER generated
# typed `fn`, so a typed CHAIN — two or more `-> Type` contracts stacked
# through tail position — was outside the grammar entirely. Round 337
# confirmed that by running its new `tail_transparency` oracle over 400
# generated programs against a deliberately un-fixed pre-336 interpreter:
# zero findings, on a build with the bug still in it.
#
# `_typed_tail_chain` below closes that. The tags a link declares are drawn
# against the tag of the terminal literal the chain actually returns, so
# roughly half the links are violated on purpose and the rest exercise the
# success path — round 336's own hand-built family kept 351 of its 2325
# programs on the success path for the same reason.
TAIL_CHAIN_TAGS = ("num", "str", "bool", "list")
# (source, the tag it actually satisfies) — deliberately only the tags a
# fuzz literal can really produce, so "declared tag != terminal tag" is a
# genuine miss rather than an accident of an unreachable tag.
TAIL_CHAIN_TERMINALS = (("1", "num"), ("0.5", "num"), ('"3O"', "str"),
                        ("true", "bool"), ("[]", "list"), ("[1, 2]", "list"))

# v0.14 backlog (closed round 162): the grammar generated no `effects [...]`
# clauses either, so the parse-time effect check (round 146) was only ever
# exercised by the hand-written corpus (`examples/effects.lang`,
# `tests/test_v14.py`). Through v0.14.7, `io` (`print`) was the only
# builtin ever registered as effectful; v0.14.8 (round 294) added `rand`
# (tag "random"). `net` is still deliberately never registered to any
# builtin, so it fuzzes the "declared but unrelated tag does not grant"
# path alongside the two real ones. A generated body is free to call
# `print`/`rand` directly (both ordinary `BUILTIN_ARITY` entries `call()`
# can pick) inside an `effects []` function, which is a real host
# ParseError — already a normal, handled fuzzer outcome (every existing
# seed already produces plenty from other causes). Round 299 added the
# four `random`-inclusive combinations below so this corpus also generates
# clauses that DO grant `rand`'s own tag (unlike the `net`-only combos,
# which deliberately never grant anything real) — the same reason
# `[io, net]` already existed for `print`.
EFFECT_TAG_SETS = ("[]", "[io]", "[net]", "[io, net]", "[random]",
                   "[io, random]", "[net, random]", "[io, net, random]")

# `guess`/`is_guess`/`confidence`/`sure` are ORDINARY builtin calls (no new
# syntax, unlike `: Type`/`effects [...]`), so they join `BUILTIN_ARITY` and
# `call()` picks them like any other builtin — exercising `_guess_binop`'s
# weakest-link-confidence path, the "genuine type error stays a miss"
# path, and `sure()`'s threshold both ways against fast/direct/trampoline.
# STALE until round 236, this comment used to say `GuestGen` (guest.py)
# bans these four names because self_eval.lang had no guest support for
# them yet — that was true when this section was first written (v0.15,
# guest parity "not started") but has been false since round 176, which
# gave `self_eval.lang`'s `arities`/`apply_builtin` tables free-delegation
# entries for all four (a guest Guess literally IS the host's own `Guess`
# payload). `GuestGen` never banned them via the BANNED-line mechanism at
# all — see `guest.py`'s own `BANNED` regex and its accurate round-176
# comment, which this one failed to match for 60 rounds (158-217 or so, a
# comment-only instance of the exact staleness class rounds 230/234 found
# and fixed in SPEC.md prose; nothing here needed a code fix, only this
# text). `call()` already generates guess/is_guess/confidence/sure freely
# for BOTH the host-only and guest-safe generators today.
# Round 335: type specs as VALUES, for `matches`/`typed`. Mixes tags that
# match, tags that never match a generated value, structural record specs
# (plain, `__shape`-named, and nested), MALFORMED record specs (a field
# whose value is not itself a spec -- the shape that crashed `_type_match`
# with an uncaught `AttributeError` before round 335 fixed it), and
# outright non-specs, so the match path, the mismatch path and `typed`'s
# own "spec must be a type name or a shape" miss all fire.
SPEC_POOL = ['"num"', '"str"', '"bool"', '"list"', '"record"', '"fn"',
             '"any"', '"miss"', '"guess"', '"nosuch"', '""',
             '@{a: "num"}', '@{a: "num", b: "str"}', '@{x: "num"}',
             '@{__shape: "Pt", x: "num"}', '@{a: @{b: "num"}}',
             '@{a: 5}', '@{a: [1]}', '@{__shape: 5, a: "num"}',
             '5', 'true', '[1]', '@{}']
# `typed`'s third argument. A non-string is the host's own "typed label
# must be a string" miss, a path nothing else in this grammar reaches.
TYPED_LABELS = ['"lbl"', '"parameter \'a\' of f"', '""', '5', 'true']

GUESS_CONFIDENCES = ("0.9", "0.5", "0.1", "0.0", "1.0", "1.5", "-0.2", '"bad"')
GUESS_SOURCES = ('"model"', '"sampled"', "42")


class ProgramGen(object):
    def __init__(self, seed, stress_rate=0.5, max_depth=4):
        self.r = random.Random(seed)
        self.stress_rate = stress_rate
        self.max_depth = max_depth
        self.counter = 0
        self.scope = []       # top-level bound names
        self.fns = []         # (name, arity) of top-level fns
        # v0.14.2 backlog (round 257/269): names bound as a direct alias of
        # `print` (`let x = print`), so `call()` can occasionally call
        # THROUGH one instead of only ever calling `print` directly — the
        # one grammar shape `Parser.alias_scopes` tracks that this fuzzer
        # could not previously reach at all (round 269's own dedicated,
        # ORACLED campaign in `harness/swe/alias_effects.py` is the real
        # bug-finding tool for this feature; this is crash-fuzz coverage
        # only — no semantic oracle here, just "does it ever escape as
        # something other than LexError/ParseError").
        self.alias_names = []
        # v0.14.3/v0.14.4/v0.14.5 fuzz-coverage gap (rounds 266/270/272/276,
        # closed round 278): `alias_names` above only reaches the DIRECT-
        # alias shape (v0.14.2). The other three shipped effect-tracking
        # shapes need their own generated forms:
        #   return_alias_fns  -- 0-arity-callable (name, arity) pairs whose
        #                        body's own tail resolves to an effectful
        #                        alias (a bare alias NameRef, or an
        #                        if/else(-if) tail where every arm does --
        #                        see `_return_alias_body`), so `call()`/
        #                        `statement()` can exercise
        #                        `_resolve_effectful_return`'s "call it"
        #                        and "chain a call on it" shapes (v0.14.3)
        #                        and, via `_return_alias_body`'s if/else
        #                        form, the if-tail shape (v0.14.5).
        #   field_alias_boxes -- (box_name, field_name) pairs bound as
        #                        `let box = @{field: <alias>, ...}`, so
        #                        `call()` can exercise
        #                        `_resolve_effectful_field`'s `box.field(
        #                        ...)` shape (v0.14.4).
        # Before this round, `harness/swe/fuzz.py`'s `ProgramGen` never
        # emitted any of these three shapes at all (confirmed by grep, each
        # of rounds 266/270/272/276) — every v0.14.3/4/5 test came only
        # from `tests/test_v14.py`'s hand-written corpus, zero differential-
        # fuzz coverage. This is still crash-fuzz coverage only, same as
        # `alias_names` above -- no semantic oracle checks WHICH tag a
        # shape resolves to, only that generating it never escapes as
        # anything other than LexError/ParseError.
        self.return_alias_fns = []
        self.field_alias_boxes = []
        # v0.14.6 fuzz-coverage gap (round 282, closed round 284): a FOURTH
        # shape, the field-access mirror of `return_alias_fns` above —
        # `field_return_alias_boxes` holds (box_name, field_name) pairs
        # bound as `let box = @{field: <return_alias_fn name>, ...}` (the
        # field VALUE is a bare NameRef naming one of `return_alias_fns`,
        # not a call), so `call()` can exercise
        # `_resolve_effectful_field_return`'s `box.field()(...)` shape —
        # TWO applications, exactly `get_printer()(1)` (v0.14.3) with the
        # first hop routed through a field instead of a bare name. Same
        # "never previously reachable from ProgramGen's grammar" gap as the
        # other three, named explicitly in round 282's own SPEC.md entry
        # and left untouched by round 278/279's fuzz-coverage pass (which
        # predates v0.14.6 by four rounds). Still crash-fuzz coverage only.
        self.field_return_alias_boxes = []
        # v0.14.7 fuzz-coverage gap (round 288, closed round 290): a FIFTH
        # shape, the structural (not call) mirror of `field_alias_boxes`
        # above — `nested_field_alias_boxes` holds (box_name, outer_field,
        # inner_field) triples bound as `let box = @{outer: @{inner: <alias>,
        # ...}, ...}` (the outer field's VALUE is itself another record
        # literal, one container hop deeper than `field_alias_boxes`'s bare-
        # NameRef field), so `call()` can exercise
        # `_resolve_effectful_field_nested`'s `box.outer.inner(...)` shape —
        # mirroring the hand-written corpus's `@{box: @{run: print}}`. Same
        # "never previously reachable from ProgramGen's grammar" gap as the
        # other four, named explicitly in round 288's own SPEC.md entry and
        # left untouched by round 284's own v0.14.6 fuzz-coverage pass
        # (which predates v0.14.7 by four rounds). Still crash-fuzz coverage
        # only, same limitation as the other four shapes in this family.
        self.nested_field_alias_boxes = []
        # v0.14.9/v0.14.10 fuzz-coverage gap (rounds 300/302, closed round
        # 305): `param_call_fns` holds `(name, arity, called_index)` triples
        # for a NAMED fn (`fn NAME(...) {...}`) or a `let`-bound anonymous
        # fn (`let NAME = fn(...) {...}`) whose body calls ONE of its own
        # params directly (`Parser.param_call_scopes`/`_check_call_site_
        # param_effects`) — a call site can then pass `print`/`rand`/an
        # existing alias for EXACTLY that param position (`call()` below)
        # so the ACTUAL new check (round 300/302's own "closes the
        # long-flagged builtin-as-function-ARGUMENT gap") fires its
        # ParseError path under fuzzing, not only via `tests/test_v14.py`'s
        # hand-written corpus. Confirmed by grep first, the same discipline
        # every earlier addition in this family already uses: `call()`'s
        # existing branches only ever call a name from `self.fns`
        # (top-level fn names), a tracked alias, or a builtin — `some_name`
        # includes local PARAMS as plain VALUES but nothing in `call()`/
        # `expr()` ever calls a bare local param AS a function, so this
        # exact shape (a param used as a callee inside its own fn's body)
        # was genuinely unreachable before this round, the same "never
        # previously reachable from ProgramGen's grammar" gap named by
        # every one of the five entries above. Unlike those five (each a
        # new ALIAS-TRACKING shape resolved by NAME alone), this is the
        # first CALL-SITE-dependent check in the family — the verdict
        # depends on the ARGUMENT at each individual call site, not just on
        # the callee's own name — so this is still crash-fuzz coverage only
        # (no oracle here checks WHICH verdict is correct for a given
        # call site; that lives in `harness/swe/alias_effects.py`'s
        # `ExtendedEffectGen`, extended the same round for exactly this
        # reason).
        self.param_call_fns = []
        # v0.14.11 fuzz-coverage gap (round 306, closed round 311): a
        # rename-chain VARIANT of `param_call_fns`'s own body shape — a fn
        # body that calls one of its own params THROUGH a `let`-rename
        # (`let g = f\n g(1)`) instead of directly (`f(1)`), mirroring the
        # hand-written corpus's `let g = f\n g(1)` (`Parser.param_alias_
        # scopes`/`_resolve_param_alias`). Deliberately reuses the SAME
        # `param_call_fns` list (not a new one) and the SAME `call()`
        # consumer (line ~645 below) — the external, call-site-observable
        # shape is IDENTICAL either way (`fn_name(args)` with an effectful
        # arg at the tracked position), `call()`'s own consumer never
        # needed to know HOW the fn's body arrived at "calls this param",
        # the same fact-producer/fact-consumer separation `alias_effects.
        # py`'s own `ExtendedEffectGen` docstring names for this whole
        # family. Still crash-fuzz coverage only, same limitation as
        # `param_call_fns` above (no oracle here checks WHICH verdict is
        # correct for a given call site — that lives in `harness/swe/
        # alias_effects.py`'s `ExtendedEffectGen`, extended the same round
        # for exactly this reason).
        #
        # v0.14.12 fuzz-coverage gap (round 308, closed round 311):
        # `return_param_fns` holds `(name, arity, returned_index)` triples
        # for a NAMED fn or `let`-bound anonymous fn whose body's own TAIL
        # directly returns one of its own params, unchanged (`fn apply(f)
        # { f }`), mirroring the hand-written corpus's `apply`
        # (`Parser.return_param_scopes`/`_resolve_return_param_
        # passthrough`). Two consumption shapes, both crash-fuzz only:
        # (1) `let g = apply(print)` in the `let`-statement branch below,
        # reusing `alias_names`/`call()`'s existing alias-call consumer
        # unchanged (same fact-producer/fact-consumer reuse as `param_
        # call_fns`'s rename variant above); (2) `apply(print)(1)`, a
        # chained call with no intermediate `let`, in `call()` itself,
        # mirroring `return_alias_fns`'s own chained-call shape.
        self.return_param_fns = []
        # v0.12/v0.13/v0.18/v0.19 fuzz-coverage gap (round 347): declared
        # shapes, as `(name, ((field, tag), ...))` in DECLARATION order —
        # the order is what makes a later shape's field able to name an
        # earlier one (parser.py `shape_scopes`: "single pass, no forward
        # refs"). Consumed by `type_tag` (annotations), `spec_arg`
        # (`matches`/`typed` spec VALUES), `_witness_for` (a record literal
        # that really satisfies one) and `_shadowed_shape_stmt` (an
        # ordinary `let` shadowing one inside a block). Every entry is
        # declared at TOP LEVEL by `program()` before any statement is
        # generated, which is what makes an annotation naming one always in
        # scope for `parse_type` — v0.18 rejects a name whose declaring
        # block has closed, and a mid-program declaration would make that
        # rejection a routine ParseError rather than a rare one.
        self.shapes = []

    # names ---------------------------------------------------------------
    def fresh(self, prefix="v"):
        self.counter += 1
        return "%s%d" % (prefix, self.counter)

    def some_name(self, local):
        r = self.r
        pool = list(local) + self.scope + [f for f, _ in self.fns]
        if not pool or r.random() < 0.04:
            return r.choice(["zz", "undefined_name", "q"])
        return r.choice(pool)

    def _alias_source(self):
        """A bare NameRef `Parser._resolve_effectful_alias` recognizes as
        effectful right now: `print` or `rand` (v0.14.8, round 294; added
        here round 299) themselves, or any name already tracked as a direct
        alias of either. Deliberately excludes `return_alias_fns` names — a
        bare fn NAME used as a tail (not a call) resolves through
        `alias_scopes`, where a named fn is always bound to `None`
        (`parser.py` `statement()`'s named-fn branch sets it explicitly),
        never through `return_alias_scopes`."""
        return self.r.choice(["print", "rand"] + self.alias_names)

    def _return_alias_body(self, params):
        """v0.14.3/v0.14.5 fuzz coverage: a fn body whose tail is a bare
        alias NameRef, or an if/else(-if chain) tail where every arm is
        one — the two shapes `_resolve_effectful_return`/
        `_if_tail_alias_tag` track. `params[0]` (when present) becomes the
        `if` condition so the CALL SITE's own argument decides which arm
        actually runs; ~20% of the time one arm gets a non-alias value
        instead (a literal), exercising the "not every arm agrees, stays
        untracked" path structurally (no semantic check here of which tag
        it resolves to — see `__init__`'s docstring on this whole family)."""
        r = self.r
        tail = self._alias_source()
        if not params or r.random() < 0.4:
            return "{ %s }" % tail
        cond = params[0]
        other = self._alias_source() if r.random() < 0.8 else self.literal()
        if r.random() < 0.6:
            return "{ if %s { %s } else { %s } }" % (cond, tail, other)
        mid = self._alias_source() if r.random() < 0.8 else self.literal()
        return "{ if %s == 0 { %s } else if %s == 1 { %s } else { %s } }" % (
            cond, tail, cond, mid, other)

    def _field_alias_record(self):
        """v0.14.4 fuzz coverage: a record literal with one bare-NameRef
        field aliasing an effectful builtin (or an existing alias) plus 0-2
        ordinary fields, mirroring the hand-written corpus's `@{run: print,
        other: 5}`. Returns `(source_text, alias_field_name)`."""
        r = self.r
        alias_field = r.choice(FIELD_POOL)
        pairs = ["%s: %s" % (alias_field, self._alias_source())]
        others = r.sample([f for f in FIELD_POOL if f != alias_field], r.randint(0, 2))
        for fname in others:
            pairs.append("%s: %s" % (fname, self.expr(1, [])))
        r.shuffle(pairs)
        return "@{%s}" % ", ".join(pairs), alias_field

    def _field_return_alias_record(self):
        """v0.14.6 fuzz coverage: a record literal with one bare-NameRef
        field naming a `return_alias_fns` entry (not calling it — the field
        VALUE is the fn name itself, mirroring the hand-written corpus's
        `@{run: get_printer}`) plus 0-2 ordinary fields. Caller must check
        `self.return_alias_fns` is non-empty first. Returns
        `(source_text, field_name)`."""
        r = self.r
        fn_name, _fn_arity = r.choice(self.return_alias_fns)
        alias_field = r.choice(FIELD_POOL)
        pairs = ["%s: %s" % (alias_field, fn_name)]
        others = r.sample([f for f in FIELD_POOL if f != alias_field], r.randint(0, 2))
        for fname in others:
            pairs.append("%s: %s" % (fname, self.expr(1, [])))
        r.shuffle(pairs)
        return "@{%s}" % ", ".join(pairs), alias_field

    def _nested_field_alias_record(self):
        """v0.14.7 fuzz coverage: a record literal with one field whose
        value is ANOTHER record literal, that inner literal itself having
        one bare-NameRef field aliasing an effectful builtin (or an
        existing alias) plus 0-2 ordinary fields at EACH level, mirroring
        the hand-written corpus's `@{box: @{run: print}}`. Returns
        `(source_text, outer_field_name, inner_field_name)`."""
        r = self.r
        inner_field = r.choice(FIELD_POOL)
        inner_pairs = ["%s: %s" % (inner_field, self._alias_source())]
        inner_others = r.sample([f for f in FIELD_POOL if f != inner_field], r.randint(0, 2))
        for fname in inner_others:
            inner_pairs.append("%s: %s" % (fname, self.expr(1, [])))
        r.shuffle(inner_pairs)
        inner_lit = "@{%s}" % ", ".join(inner_pairs)
        outer_field = r.choice(FIELD_POOL)
        pairs = ["%s: %s" % (outer_field, inner_lit)]
        others = r.sample([f for f in FIELD_POOL if f != outer_field], r.randint(0, 2))
        for fname in others:
            pairs.append("%s: %s" % (fname, self.expr(1, [])))
        r.shuffle(pairs)
        return "@{%s}" % ", ".join(pairs), outer_field, inner_field

    def _param_call_body(self, params):
        """v0.14.9/v0.14.10 fuzz coverage: a fn body that calls ONE of its
        own params directly (`f(1)`), mirroring the hand-written corpus's
        `fn apply(f) effects [io] { f(1) }`. `params` must be non-empty.
        Returns `(source_text, called_param_index)` — the caller registers
        `(name, arity, called_param_index)` in `self.param_call_fns` so
        `call()` below knows exactly which argument POSITION to target
        with an effectful name."""
        r = self.r
        idx = r.randrange(len(params))
        called = params[idx]
        stmts = []
        for _ in range(r.randint(0, 1)):
            stmts.append("let %s = %s" % (self.fresh("t"), self.expr(1, params)))
        stmts.append("%s(%s)" % (called, self.expr(1, params)))
        return "{ " + "\n  ".join(stmts) + " }", idx

    def _param_rename_call_body(self, params):
        """v0.14.11 fuzz coverage: a fn body that renames one of its own
        params (`let g = f`, 30% of the time a SECOND rename hop, `let h =
        g`) then calls THROUGH the rename (`h(1)`) rather than the param
        directly — mirrors the hand-written corpus's `let g = f\\n g(1)`
        (`_resolve_param_alias`). Same `(source_text, called_param_index)`
        contract as `_param_call_body` above — see `__init__`'s own
        docstring for why `call()`'s existing `param_call_fns` consumer
        needs no change at all to reach this variant too."""
        r = self.r
        idx = r.randrange(len(params))
        called = params[idx]
        rename1 = self.fresh("g")
        stmts = ["let %s = %s" % (rename1, called)]
        call_name = rename1
        if r.random() < 0.3:
            rename2 = self.fresh("g")
            stmts.append("let %s = %s" % (rename2, call_name))
            call_name = rename2
        stmts.append("%s(%s)" % (call_name, self.expr(1, params)))
        return "{ " + "\n  ".join(stmts) + " }", idx

    def _param_forward_body(self, params, target_name, target_arity, target_called_idx):
        """v0.14.13 fuzz coverage: a fn body that FORWARDS one of its own
        params as the argument at ANOTHER already-tracked fn's own
        called-param position (`fn outer(f) { inner(f) }` where `inner` is
        drawn from `self.param_call_fns`), instead of calling a param
        directly/through a rename/returning one — mirrors the hand-written
        corpus's `fn inner(g) effects [io] { g(1) }` / `fn outer(f)
        effects [io] { inner(f) }` pair (`_check_param_forwarding`).
        `params` must be non-empty; `(target_name, target_arity,
        target_called_idx)` is one entry already drawn from `self.param_
        call_fns` by the caller. Returns `(source_text, forwarded_param_
        index)` — the OWN param position used as the forwarded argument,
        NOT `target_called_idx` (that identifies a position in the
        TARGET's own params, a different fn entirely) — the caller
        registers `(name, arity, forwarded_param_index)` into `self.
        param_call_fns` ITSELF (the SAME list, not a new one), since THIS
        fn now also "calls that param directly" by composition, exactly
        the same fact-producer/fact-consumer reuse `_param_rename_call_
        body`'s own docstring already explains for the rename variant —
        `call()`'s existing `param_call_fns` consumer needs no changes at
        all to reach a call through a FORWARDING fn either."""
        r = self.r
        idx = r.randrange(len(params))
        forwarded = params[idx]
        args = []
        for i in range(target_arity):
            args.append(forwarded if i == target_called_idx else self.expr(1, params))
        stmts = []
        for _ in range(r.randint(0, 1)):
            stmts.append("let %s = %s" % (self.fresh("t"), self.expr(1, params)))
        stmts.append("%s(%s)" % (target_name, ", ".join(args)))
        return "{ " + "\n  ".join(stmts) + " }", idx

    def _return_param_body(self, params):
        """v0.14.12 fuzz coverage: a fn body whose tail is a bare NameRef
        to ONE of its own params, unchanged (`fn apply(f) { f }`),
        mirroring the hand-written corpus's `apply`
        (`Parser.return_param_scopes`/`_resolve_return_param_
        passthrough`). `params` must be non-empty. Returns `(source_text,
        returned_param_index)` — the caller registers `(name, arity,
        returned_param_index)` in `self.return_param_fns` so `call()`/the
        `let`-statement branch below know exactly which argument POSITION
        a later call site should target with an effectful name."""
        r = self.r
        idx = r.randrange(len(params))
        returned = params[idx]
        stmts = []
        for _ in range(r.randint(0, 1)):
            stmts.append("let %s = %s" % (self.fresh("t"), self.expr(1, params)))
        stmts.append(returned)
        return "{ " + "\n  ".join(stmts) + " }", idx

    # program -------------------------------------------------------------
    def program(self):
        r = self.r
        lines = []
        # (round 347) shape declarations come FIRST, before the template
        # and before any statement, so every annotation `type_tag` later
        # emits names a shape whose declaring block (the module) is still
        # open — see `self.shapes`'s own comment for why a mid-program
        # declaration would turn v0.18's scope rejection into noise.
        # Emitted alongside the statement budget rather than out of it,
        # the same accounting round 337 measured for `_typed_tail_chain`.
        if r.random() < 0.35:
            for _ in range(r.randint(1, 2)):
                lines.extend(self._shape_decl())
        if r.random() < self.stress_rate:
            lines.extend(self.template())
        # v0.13 fuzz coverage (round 337, closing round 336's item 1): a
        # typed tail chain, emitted ALONGSIDE the ordinary statement budget
        # the way `template` above is, not as one of its statements. Round
        # 337 first spent a statement on it and measured the cost at
        # n=2000: every other generated shape lost ~10% of its own rate
        # (trunc 6.4% -> 5.3%, param-call 8.0% -> 6.9%, rand 34.6% ->
        # 31.1%, sqrt 13.5% -> 12.2%), which is just the 8% of the 2-7
        # statement budget the branch was taking. Emitting it here costs
        # nothing from that budget, and the chain's own `fn`s land in
        # `self.fns` BEFORE the ordinary statements are generated, so the
        # rest of the grammar can call and probe them too.
        if r.random() < 0.3:
            lines.append(self._typed_tail_chain())
        for _ in range(r.randint(2, 7)):
            lines.append(self.statement())
        probes = r.sample(self.scope, min(len(self.scope), 3)) if self.scope else []
        for name in probes:
            lines.append(self.probe(name))
        return "\n".join(s for s in lines if self.keep_stmt(s)) + "\n"

    def keep_stmt(self, stmt):
        """Whether one generated STATEMENT survives into the program.
        Always true here.

        The only extension point `program` has, and the reason it has one
        (round 347): `GuestGen` used to carry its own hand-copied `program`
        so it could drop guest-unsafe statements, and that fork silently
        skipped every recipe the base gained afterwards. Round 337's typed
        tail chain was added to the base and NEVER reached the guest
        differential — 0 of 400 generated guest programs contained one, ten
        rounds later — and round 347's shape declarations would have been
        the second instance on the same day they were written. A predicate
        cannot drift that way: a subclass that answers "keep this?" cannot
        also decide WHAT is generated.

        `test_swe_fuzz.py`'s `test_program_recipe_has_no_subclass_fork`
        asserts structurally (over the AST, not by grep) that no subclass
        of `ProgramGen` anywhere under `harness/` defines `program` — the
        guard round 341's item 5 and round 343's item 5 both asked for,
        applied to the first case that actually needed it."""
        return True

    def template(self):
        r = self.r
        k = r.choice([3, 20, 60, 200, 700, 1500, 3000])
        which = r.randrange(13)
        if which == 9:      # v0.3 tail loop: merged `call go xN` + merged `if` (v0.4)
            self.fns.append(("go", 2)); self.scope.append("tail")
            return ["fn go(n, acc) { if n == 0 { acc } else { go(n - 1, acc + n) } }",
                    "let tail = go(%d, 0)" % k]
        if which == 10:     # mutual recursion: `call even/odd xN`
            self.fns.append(("even", 1)); self.fns.append(("odd", 1)); self.scope.append("par")
            return ["fn even(n) { if n == 0 { true } else { odd(n - 1) } }",
                    "fn odd(n) { if n == 0 { false } else { even(n - 1) } }",
                    "let par = even(%d)" % k]
        if which == 11:     # alternating branches: run-length merge boundaries
            self.fns.append(("alt", 2)); self.scope.append("zig")
            return ["fn alt(n, acc) { if n == 0 { acc } else if n %% %d == 0 { alt(n - 1, acc + 1) }"
                    " else { alt(n - 1, acc - 1) } }" % r.choice([2, 3, 5]),
                    "let zig = alt(%d, 0)" % k]
        if which == 12:     # two near-identical runs for diverge/contrast
            self.fns.append(("go", 2)); self.scope.extend(["r0", "r1"])
            return ["fn go(n, acc) { if n == 0 { acc } else { go(n - 1, acc + n) } }",
                    "let r0 = go(%d, 0)" % k, "let r1 = go(%d, %s)" % (k, r.choice(["1", "0", '"3O"']))]
        if which == 0:
            self.fns.append(("nest", 1)); self.scope.append("deep")
            return ["fn nest(n) { if n == 0 { [] } else { [nest(n - 1)] } }",
                    "let deep = nest(%d)" % k]
        if which == 1:
            self.fns.append(("count", 1)); self.scope.append("cnt")
            return ["fn count(n) { if n == 0 { 0 } else { 1 + count(n - 1) } }",
                    "let cnt = count(%d)" % k]
        if which == 2:
            self.fns.append(("wrap", 1)); self.scope.append("rec")
            return ["fn wrap(n) { if n == 0 { @{v: 0} } else { @{v: wrap(n - 1)} } }",
                    "let rec = wrap(%d)" % k]
        if which == 3:
            self.scope.append("paren")
            return ["let paren = " + "(" * k + "1" + ")" * k]
        if which == 4:
            self.scope.append("neg")
            return ["let neg = " + "- " * k + "1"]
        if which == 5:
            self.scope.append("lst")
            return ["let lst = " + "[" * k + "]" * k]
        if which == 6:
            self.scope.append("huge")
            return ["let huge = fold(fn(a, x) { a * 2 }, 1, range(%d))" % k]
        if which == 7:
            self.scope.append("grown")
            return ["let grown = fold(fn(acc, x) { push(acc, x) }, [], range(%d))" % k]
        self.scope.append("chain")
        return ["let chain = 1" + " + 1" * k]

    # shapes (round 347) --------------------------------------------------
    def shape_names(self):
        return [s for s, _ in self.shapes]

    def _shape_decl(self):
        """One `shape S7 = @{a: num, b: S3}` line, plus (60%) a witness
        binding that really satisfies it.

        0-3 fields: the 0-field case (`shape S = @{}`) is deliberate — it
        desugars to `@{__shape: "S"}`, whose non-`__shape` field set is
        empty, so `_spec_ok` is vacuously true and `_type_match` accepts
        ANY record. That is the widest possible shape and the one most
        likely to make a generated annotation PASS.

        A field may name an earlier shape (25%), which is the only way a
        generated program reaches `_spec_ok`'s recursive half and
        `_type_match`'s nested-record branch through a real declaration
        rather than through `SPEC_POOL`'s hand-built `@{a: @{b: "num"}}`.
        """
        r = self.r
        name = self.fresh("S")
        fields, used = [], set()
        for _ in range(r.randint(0, 3)):
            f = r.choice(FIELD_POOL)
            if f in used:
                continue        # a duplicate field is a ParseError, not a
                                # program shape worth spending a slot on
            used.add(f)
            if self.shapes and r.random() < 0.25:
                tag = r.choice(self.shape_names())
            else:
                tag = r.choice(SHAPE_FIELD_TAGS)
            fields.append((f, tag))
        lines = ["shape %s = @{%s}" % (
            name, ", ".join("%s: %s" % (f, t) for f, t in fields))]
        self.shapes.append((name, tuple(fields)))
        if r.random() < 0.6:
            w = self.fresh("w")
            lines.append("let %s = %s" % (w, self._witness_for(name)))
            self.scope.append(w)
        return lines

    def _witness_for(self, shape_name, depth=0):
        """A record literal that satisfies `shape_name` exactly.

        Terminates without a depth argument in principle (a shape may only
        reference EARLIER shapes, so the reference graph is a DAG on
        declaration order), but the cap is kept: `_shape_decl` is the only
        producer today and a future one that allows self-reference would
        otherwise hang the generator rather than fail a test."""
        fields = dict(self.shapes)[shape_name]
        return "@{%s}" % ", ".join(
            "%s: %s" % (f, self._witness_value(t, depth)) for f, t in fields)

    def _witness_value(self, tag, depth):
        if tag in SHAPE_WITNESS_LITERALS:
            return self.r.choice(SHAPE_WITNESS_LITERALS[tag])
        if depth >= 4:
            return "@{}"
        return self._witness_for(tag, depth + 1)

    def type_tag(self):
        """A tag for a `p: Type` / `-> Type` annotation: a primitive, or
        (35%, once any shape is declared) a declared shape NAME.

        The one place the three annotation sites — `typed_params`,
        `maybe_ret_type` and `_chain_tag` — agree on what a "tag" is, so a
        future tag kind reaches all three at once. Before round 347 each
        drew `r.choice(TYPE_TAGS)` for itself."""
        r = self.r
        if self.shapes and r.random() < 0.35:
            return r.choice(self.shape_names())
        return r.choice(TYPE_TAGS)

    def spec_arg(self, depth, local):
        """The spec ARGUMENT of a generated `matches`/`typed` call. A
        declared shape name (25%) reaches the same runtime record the
        annotation path resolves to, but through the ordinary evaluator —
        so `_spec_ok`/`_type_match` see it with no `_closure_spec` in
        front of them, and a divergence between the two routes shows up as
        a `matches(x, S)` that disagrees with `fn f(p: S)`."""
        r = self.r
        if self.shapes and r.random() < 0.25:
            return r.choice(self.shape_names())
        if r.random() < 0.15:
            return self.expr(depth + 1, local)
        return r.choice(SPEC_POOL)

    def _shadowed_shape_stmt(self):
        """An ordinary `let` shadowing a declared shape name INSIDE a
        block, with an annotated `fn` defined after it in that same block:

            fn sh3() { let S1 = 3
              fn sg4() -> S1 { 1 }
              sg4() }
            let sr5 = sh3()

        v0.18's parser accepts the annotation — `S1`'s declaring block (the
        module) has not closed, and `shape_scopes` tracks shape
        DECLARATIONS, not the ordinary `let` that shadows one — so the
        program's fate is decided at runtime by `_closure_spec`, which
        resolves `S1` in the DEFINING env: the block's, where it is 3.

        This is the ONLY generated shape that reaches `_check_contract`'s
        `not _spec_ok(spec)` guard. Round 335 wrote that guard off as
        "unreachable today"; round 344 measured the AttributeError it
        actually raised, in all three evaluation modes, for both FnDef and
        FnExpr, tail and non-tail. Both halves of the contract are
        generated (`-> S` and `p: S`) because v0.19 routes them through the
        same `_closure_spec` and the same `_check_contract`, and a shape
        that only ever exercised one end could not show a divergence
        between them.

        EARLY vs LATE (round 359). The recipe above only ever emitted the
        shadowing `let` BEFORE the annotated fn, and that placement cannot
        show the difference this family exists to find. Round 342 §7's
        hazard is about WHEN a spec name is resolved — at closure creation
        (v0.19, the defining env) or per call (v0.12-v0.18, the calling
        env) — and with the `let` first, BOTH answer 3. Round 359 measured
        the consequence: its `param_erasure` oracle diverged on 47 of 2500
        generated programs, and all 47 differed only in a v0.22 wording
        clause, with the two forms resolving the spec to the same value. So
        half the time the `let` now runs AFTER the fn is defined:

            fn sh3() { fn sg4(q: S1) { q }
              let S1 = 3
              sg4(1) }

        `_closure_spec` resolves `S1` at `fn sg4`'s creation, when the only
        `S1` in scope is the module's real shape, while a v0.12-style guard
        would look it up at the call and find the 3. That is the hazard
        itself, generated for the first time. The EARLY half is kept
        because it is the only thing that reaches `_check_contract`'s
        `not _spec_ok` guard (round 344's AttributeError), which the LATE
        half specifically does not."""
        r = self.r
        sname = r.choice(self.shape_names())
        outer, inner, res = self.fresh("sh"), self.fresh("sg"), self.fresh("sr")
        bind = r.choice(SHADOW_BINDINGS)
        if r.random() < 0.5:
            decl = "fn %s() -> %s { 1 }" % (inner, sname)
            call = "%s()" % inner
        else:
            q = self.fresh("q")
            decl = "fn %s(%s: %s) { %s }" % (inner, q, sname, q)
            call = "%s(%s)" % (inner, r.choice(
                ["1", '"3O"', "@{}", "@{a: 1}", self._witness_for(sname)]))
        shadow = "let %s = %s" % (sname, bind)
        # LATE (round 359): the shadowing `let` runs AFTER the annotated fn
        # is defined, so the two resolutions really do see different values
        # — see this method's docstring.
        if r.random() < 0.5:
            stmts = [decl, shadow, call]      # LATE: shadow after the fn
        else:
            stmts = [shadow, decl, call]      # EARLY: the original recipe
        self.fns.append((outer, 0))
        self.scope.append(res)
        return ("fn %s() { %s }\nlet %s = %s()"
                % (outer, "\n  ".join(stmts), res, outer))

    def _chain_tag(self, term_tag):
        """A `-> Type` annotation for one link of a typed tail chain, drawn
        against `term_tag` (the tag the chain's terminal literal really
        satisfies): `None` (untyped link) 20%, `any` 15% (typed but always
        satisfied), the terminal's own tag 20% (typed and satisfied), a
        deliberately WRONG tag 45%. Mixing satisfied and violated links in
        one chain is the point — round 336's defect was about WHICH of
        several contracts gets blamed, so a chain with only one contract in
        it cannot show it."""
        r = self.r
        q = r.random()
        if q < 0.2:
            return None
        if q < 0.35:
            return "any"
        if q < 0.55:
            return term_tag
        if self.shapes and r.random() < 0.3:
            # (round 347) a declared shape as the violated tag: a chain
            # link whose contract can only ever be missed by the terminal
            # LITERAL, but whose spec had to be resolved through
            # `_closure_spec`'s NameRef branch first — the tail-chain
            # mirror of `type_tag`'s own shape draw.
            return r.choice(self.shape_names())
        return r.choice([t for t in TAIL_CHAIN_TAGS if t != term_tag])

    def _typed_tail_chain(self):
        """A whole typed tail chain as one multi-line statement (see
        TAIL_CHAIN_TAGS above for why the grammar needed this at all).

        Three shapes, all of which round 337 confirmed the new
        `tail_transparency` oracle reports on a pre-336 interpreter and
        stays silent on the fixed one:
          linear   `fn a() -> T { b() }  fn b() -> U { c() }  fn c() -> V
                   { <lit> }` — the blame-ORDER shape (round 336 blamed the
                   outermost contract, the lifted form the innermost).
          self     `fn f(n) -> T { if n == 0 { <lit> } else { f(n - 1) } }`
                   — the LINE shape: same function, same contract, but the
                   miss must name the recursive call's line, not the
                   original call's.
          mutual   two functions in a typed 2-cycle — the "revisiting a
                   closure" family, where a chain entry for a spec already
                   seen has to be refreshed rather than deduplicated away.
        Every fn is registered in `self.fns` and the result in `self.scope`,
        so the rest of the grammar can call and probe them like any other.
        """
        r = self.r
        shape = r.random()
        term, term_tag = r.choice(TAIL_CHAIN_TERMINALS)
        if shape < 0.2:
            return self._typed_self_tail_loop(term, term_tag)
        if shape < 0.35:
            return self._typed_mutual_tail_loop(term, term_tag)
        hops = r.randint(2, 4)
        names = [self.fresh("tc") for _ in range(hops)]
        lines = []
        for i, name in enumerate(names):
            tag = self._chain_tag(term_tag)
            ann = "" if tag is None else " -> %s" % tag
            body = term if i == hops - 1 else "%s()" % names[i + 1]
            lines.append("fn %s()%s { %s }" % (name, ann, body))
            self.fns.append((name, 0))
        res = self.fresh("tr")
        lines.append("let %s = %s()" % (res, names[0]))
        self.scope.append(res)
        return "\n".join(lines)

    def _typed_self_tail_loop(self, term, term_tag):
        """`fn f(n) -> T { if n == 0 { <lit> } else { f(n - 1) } }` plus a
        call. A fresh param name (not a literal `n`) so nothing the rest of
        the grammar bound can be captured."""
        r = self.r
        name = self.fresh("tl")
        p = self.fresh("p")
        tag = self._chain_tag(term_tag)
        ann = "" if tag is None else " -> %s" % tag
        res = self.fresh("tr")
        self.fns.append((name, 1))
        self.scope.append(res)
        return ("fn %s(%s)%s { if %s == 0 { %s } else { %s(%s - 1) } }\n"
                "let %s = %s(%d)" % (name, p, ann, p, term, name, p,
                                     res, name, r.randint(0, 4)))

    def _typed_mutual_tail_loop(self, term, term_tag):
        """Two typed functions in a tail 2-cycle, so the loop re-enters a
        closure whose `-> Type` spec the chain has already recorded once."""
        r = self.r
        a, b = self.fresh("tm"), self.fresh("tm")
        pa, pb = self.fresh("p"), self.fresh("p")
        aa = self._chain_tag(term_tag)
        ab = self._chain_tag(term_tag)
        res = self.fresh("tr")
        self.fns.append((a, 1))
        self.fns.append((b, 1))
        self.scope.append(res)
        return ("fn %s(%s)%s { if %s == 0 { %s } else { %s(%s - 1) } }\n"
                "fn %s(%s)%s { if %s == 0 { %s } else { %s(%s - 1) } }\n"
                "let %s = %s(%d)" % (
                    a, pa, "" if aa is None else " -> %s" % aa, pa, term, b, pa,
                    b, pb, "" if ab is None else " -> %s" % ab, pb, term, a, pb,
                    res, a, r.randint(0, 5)))

    def statement(self):
        r = self.r
        # (round 347) the shadowed-shape block: rare on purpose. It is the
        # only generated program that reaches `_check_contract`'s
        # `not _spec_ok` guard, but it costs a whole statement and every
        # other shape in this grammar loses rate proportionally, so it is
        # held near the floor at which a 200-program campaign still sees
        # several.
        if self.shapes and r.random() < 0.08:
            return self._shadowed_shape_stmt()
        p = r.random()
        if p < 0.55:
            name = self.fresh()
            # v0.14.2: 10% of ordinary `let`s bind a direct alias instead —
            # of `print`/`rand` itself (round 299 added `rand` alongside
            # `print` here), or (if one already exists) of a prior alias,
            # so multi-hop chains show up too (see `__init__`).
            aq = r.random()
            if aq < 0.05 or (aq < 0.1 and not self.alias_names):
                e = r.choice(["print", "rand"])
                self.alias_names.append(name)
            elif aq < 0.1:
                e = r.choice(self.alias_names)   # chain through a prior alias
                self.alias_names.append(name)
            elif aq < 0.14 and self.return_alias_fns:
                # v0.14.3 fuzz coverage: `let p = get_x()` -- p becomes an
                # ordinary effectful-VALUE alias (parser.py `statement()`'s
                # `A.Call` branch), so a later `call()` can call `p(...)`
                # exactly as any other tracked alias.
                fn_name, fn_arity = r.choice(self.return_alias_fns)
                e = "%s(%s)" % (fn_name, ", ".join(self.expr(1, []) for _ in range(fn_arity)))
                self.alias_names.append(name)
            elif aq < 0.18:
                # v0.14.4 fuzz coverage: `let box = @{field: print, ...}`.
                lit, field = self._field_alias_record()
                e = lit
                self.field_alias_boxes.append((name, field))
            elif aq < 0.22 and self.return_alias_fns:
                # v0.14.6 fuzz coverage: `let box = @{field: get_x, ...}`
                # (the field VALUE names a return-alias fn, not a call).
                lit, field = self._field_return_alias_record()
                e = lit
                self.field_return_alias_boxes.append((name, field))
            elif aq < 0.26:
                # v0.14.7 fuzz coverage: `let box = @{outer: @{inner: print}}`
                # (the outer field's VALUE is itself another record literal).
                lit, outer_field, inner_field = self._nested_field_alias_record()
                e = lit
                self.nested_field_alias_boxes.append((name, outer_field, inner_field))
            elif aq < 0.30:
                # v0.14.10 fuzz coverage: `let g = fn(f) effects [...] {
                # f(1) }` -- the `let`-bound-anonymous-fn analogue of the
                # NAMED-fn `param_call_fns` shape below (see `__init__`'s
                # own docstring): `A.FnExpr.param_call_fact` tracks the
                # exact same "calls one of its own params directly" fact,
                # just carried on the node instead of keyed by a `fn NAME`
                # statement. `call()` doesn't care which of the two shapes
                # produced an entry -- both just consume `param_call_fns`.
                # v0.14.11 fuzz coverage (round 311): half the time the
                # body calls THROUGH a rename instead of directly (see
                # `_param_rename_call_body`) -- `param_call_fns`'s own
                # consumer is unchanged either way (see `__init__`'s
                # docstring). v0.14.13 fuzz coverage (round 317): a THIRD
                # option, ~34% of the time when a target already exists --
                # the body FORWARDS one of its own params into an already-
                # tracked fn's own called-param position instead of calling/
                # renaming/returning it (see `_param_forward_body`) -- same
                # unchanged `param_call_fns` consumer either way.
                params = [self.fresh("p") for _ in range(r.randint(1, 2))]
                if self.param_call_fns and r.random() < 0.34:
                    target = r.choice(self.param_call_fns)
                    body, idx = self._param_forward_body(params, *target)
                elif r.random() < 0.5:
                    body, idx = self._param_call_body(params)
                else:
                    body, idx = self._param_rename_call_body(params)
                e = "fn(%s)%s %s" % (self.typed_params(params), self.maybe_effects(), body)
                self.param_call_fns.append((name, len(params), idx))
            elif aq < 0.34:
                # v0.14.12 fuzz coverage (round 311): `let g = fn(f) {f}`
                # -- the `let`-bound-anonymous-fn analogue of the NAMED-fn
                # `return_param_fns` shape below, same "node carries the
                # fact forward" reasoning `param_call_fns`'s own v0.14.10
                # entry above already uses.
                params = [self.fresh("p") for _ in range(r.randint(1, 2))]
                body, idx = self._return_param_body(params)
                e = "fn(%s)%s %s" % (self.typed_params(params), self.maybe_effects(), body)
                self.return_param_fns.append((name, len(params), idx))
            elif aq < 0.38 and self.return_param_fns:
                # v0.14.12 fuzz coverage (round 311): `let g = apply(print)`
                # -- calls a return_param-tracked fn, passing an effectful
                # arg at the exact RETURNED param's own position, so `g`
                # itself becomes an ordinary tracked alias
                # (`_resolve_return_param_passthrough`) that a later
                # `call()` can call through exactly like any other `alias_
                # names` entry -- reuses that existing consumer unchanged
                # (see `__init__`'s own docstring).
                fn_name, fn_arity, ridx = r.choice(self.return_param_fns)
                cargs = []
                for i in range(fn_arity):
                    if i == ridx and r.random() < 0.7:
                        cargs.append(self._alias_source())
                    else:
                        cargs.append(self.expr(1, []))
                e = "%s(%s)" % (fn_name, ", ".join(cargs))
                self.alias_names.append(name)
            else:
                e = self.expr(0, [])
            self.scope.append(name)
            return "let %s = %s" % (name, e)
        if p < 0.75:
            name = self.fresh("f")
            arity = r.randint(0, 3)
            params = [self.fresh("p") for _ in range(arity)]
            self.fns.append((name, arity))    # visible inside body: recursion
            # v0.14.3/v0.14.5 fuzz coverage: ~8% of fns get a return-alias
            # body instead of an ordinary one (see `_return_alias_body`).
            # v0.14.9/v0.14.11 fuzz coverage: ~10% of fns WITH at least one
            # param instead get a body that calls that param directly, or
            # (round 311) through a rename (see `_param_call_body`/
            # `_param_rename_call_body`), registered in `self.param_call_
            # fns` so `call()` below can target it with an effectful
            # argument. v0.14.12 fuzz coverage (round 311): ~8% instead get
            # a body that returns a param unchanged (see `_return_param_
            # body`), registered in `self.return_param_fns` above. v0.14.13
            # fuzz coverage (round 317): the SAME ~10% bucket, a THIRD
            # option forwarding one of its own params into an already-
            # tracked fn's own called-param position instead (see `_param_
            # forward_body`).
            if arity and r.random() < 0.1:
                if self.param_call_fns and r.random() < 0.34:
                    target = r.choice(self.param_call_fns)
                    body, idx = self._param_forward_body(params, *target)
                elif r.random() < 0.5:
                    body, idx = self._param_call_body(params)
                else:
                    body, idx = self._param_rename_call_body(params)
                self.param_call_fns.append((name, arity, idx))
            elif r.random() < 0.08:
                body = self._return_alias_body(params)
                self.return_alias_fns.append((name, arity))
            elif arity and r.random() < 0.08:
                body, idx = self._return_param_body(params)
                self.return_param_fns.append((name, arity, idx))
            else:
                body = self.body(params)
            return "fn %s(%s)%s%s %s" % (name, self.typed_params(params),
                                         self.maybe_effects(), self.maybe_ret_type(), body)
        if p < 0.9:
            return 'check "%s": %s' % (self.fresh("c"), self.expr(0, []))
        return self.expr(0, [])

    def typed_params(self, params):
        """`(a, b: num, c: Pt)` — each param independently gets a `: TAG`
        30% of the time (v0.13 backlog), the tag drawn by `type_tag` so a
        declared shape name can appear here as well as a primitive (round
        347, v0.19's own half of the contract)."""
        r = self.r
        return ", ".join(
            "%s: %s" % (p, self.type_tag()) if r.random() < 0.3 else p
            for p in params)

    def maybe_ret_type(self):
        """` -> TAG` 25% of the time, else ''. Tag via `type_tag`, so a
        declared shape name can appear (round 347)."""
        if self.r.random() < 0.25:
            return " -> %s" % self.type_tag()
        return ""

    def maybe_effects(self):
        """` effects [...]` 30% of the time, BEFORE `-> Type` (fixed order
        per SPEC v0.14 — the other order is an ordinary out-of-order parse
        error, already covered by the grammar's general malformed-syntax
        rate)."""
        if self.r.random() < 0.3:
            return " effects %s" % self.r.choice(EFFECT_TAG_SETS)
        return ""

    def body(self, local):
        r = self.r
        local = list(local)
        stmts = []
        for _ in range(r.randint(0, 2)):
            name = self.fresh("t")
            stmts.append("let %s = %s" % (name, self.expr(1, local)))
            local.append(name)
        stmts.append(self.expr(1, local))
        return "{ " + "\n  ".join(stmts) + " }"

    def probe(self, name):
        r = self.r
        return r.choice([
            "print(%s)", "print(why %s)", "print(str(why %s))",
            "print(len(steps(%s)))", "print(blame(%s))", 'print(at(%s, "let %s"))',
            'check "p": %s == %s', "print(contains([%s], %s))",
            "print(str(steps(%s)))", "print(reasons(%s))", "print(missed(%s))",
            "print(snip %s)", "print(steps(why %s))", 'check "p": %s == %s',
            "print(%s / 3)", "print(sqrt(%s))", "print(%s == [%s])",
            "print(contains(%s, %s))", "print(%s + %s)", "print(-%s)",
            "print(contrast(%s, %s))", "print(len(diverge(%s, %s)))",
            'print(len(steps(%s, "call go")))', 'print(at(%s, "if"))',
            "print(steps(%s)[0].count)", 'print(steps(%s, "if"))',
            "print(contrast(%s, snip %s))", "print(diverge(why %s, %s))",
        ]).replace("%s", name)

    # expressions -------------------------------------------------------
    def literal(self):
        r = self.r
        p = r.random()
        if p < 0.45:
            return str(r.choice([0, 1, 2, 3, 7, 10, 100, 0, 1]))
        if p < 0.6:
            return r.choice(["0.5", "2.0", "0.0", "1.5", "100.25"])
        if p < 0.85:
            return '"%s"' % r.choice(STR_POOL)
        return r.choice(["true", "false"])

    def fnlike(self, depth, local):
        r = self.r
        p = r.random()
        if p < 0.4:
            n = r.randint(0, 2)
            params = [self.fresh("q") for _ in range(n)]
            return "fn(%s)%s%s { %s }" % (self.typed_params(params), self.maybe_effects(),
                                          self.maybe_ret_type(),
                                          self.expr(depth + 1, local + params))
        if p < 0.7 and self.fns:
            return r.choice(self.fns)[0]
        if p < 0.85:
            return r.choice(list(BUILTIN_ARITY))
        return self.expr(depth + 1, local)

    def listlike(self, depth, local):
        r = self.r
        p = r.random()
        if p < 0.35:
            return "[%s]" % ", ".join(self.expr(depth + 1, local) for _ in range(r.randint(0, 4)))
        if p < 0.6:
            return "range(%d)" % r.randint(0, 12)
        if p < 0.8:
            return self.some_name(local)
        return self.expr(depth + 1, local)

    def recordlike(self, depth, local):
        """A record-ish expression, the record mirror of `listlike` above
        (round 335): a literal with plausible field names, a bound name, or
        an ordinary expression. Used to feed `matches`/`typed` a value a
        STRUCTURAL spec can actually match."""
        r = self.r
        p = r.random()
        if p < 0.5:
            names = r.sample(FIELD_POOL, r.randint(0, 3))
            return "@{%s}" % ", ".join(
                "%s: %s" % (nm, self.expr(depth + 1, local)) for nm in names)
        if p < 0.7:
            return "@{a: %s, b: %s}" % (r.choice(["1", '"s"', "true", "[1]"]),
                                        r.choice(["2", '"t"', "false"]))
        if p < 0.85:
            return self.some_name(local)
        return self.expr(depth + 1, local)

    def call(self, depth, local):
        r = self.r
        if self.nested_field_alias_boxes and r.random() < 0.06:
            # v0.14.7 fuzz coverage: `box.outer.inner(...)` -- a tracked
            # field-alias reached through a NESTED record literal
            # (`_resolve_effectful_field_nested`), one container hop past
            # v0.14.4's own `box.field(...)` shape below.
            box_name, outer_field, inner_field = r.choice(self.nested_field_alias_boxes)
            return "%s.%s.%s(%s)" % (box_name, outer_field, inner_field,
                                     self.expr(depth + 1, local))
        if self.field_return_alias_boxes and r.random() < 0.06:
            # v0.14.6 fuzz coverage: `box.field()(...)` -- TWO applications,
            # the first hop through a tracked field-return alias
            # (`_resolve_effectful_field_return`), exactly `get_x()(1)`
            # (v0.14.3) with the callee routed through a field instead of a
            # bare name.
            box_name, field_name = r.choice(self.field_return_alias_boxes)
            inner = "%s.%s()" % (box_name, field_name)
            return "%s(%s)" % (inner, self.expr(depth + 1, local))
        if self.field_alias_boxes and r.random() < 0.06:
            # v0.14.4 fuzz coverage: `box.field(...)` through a tracked
            # record-literal field alias (`_resolve_effectful_field`).
            box_name, field_name = r.choice(self.field_alias_boxes)
            return "%s.%s(%s)" % (box_name, field_name, self.expr(depth + 1, local))
        if self.return_alias_fns and r.random() < 0.06:
            # v0.14.3 fuzz coverage: `get_x()(...)` -- a chained call
            # directly on a call whose CALLEE resolves via
            # `_resolve_effectful_return`, no intermediate `let` needed
            # (`_check_effect_call`'s `Call`-callee branch).
            fn_name, fn_arity = r.choice(self.return_alias_fns)
            inner = "%s(%s)" % (fn_name, ", ".join(self.expr(depth + 1, local) for _ in range(fn_arity)))
            return "%s(%s)" % (inner, self.expr(depth + 1, local))
        if self.return_param_fns and r.random() < 0.06:
            # v0.14.12 fuzz coverage (round 311): `apply(print)(1)` -- a
            # chained call with NO intermediate `let`, the callee's INNER
            # application passing an effectful arg at the RETURNED param's
            # own position (`_check_effect_call`'s own `Call`-callee
            # branch, `_resolve_return_param_passthrough`) -- the argument-
            # DEPENDENT analogue of `return_alias_fns`'s own chained-call
            # shape just above.
            fn_name, fn_arity, ridx = r.choice(self.return_param_fns)
            cargs = []
            for i in range(fn_arity):
                if i == ridx and r.random() < 0.7:
                    cargs.append(self._alias_source())
                else:
                    cargs.append(self.expr(depth + 1, local))
            inner = "%s(%s)" % (fn_name, ", ".join(cargs))
            return "%s(%s)" % (inner, self.expr(depth + 1, local))
        if self.alias_names and r.random() < 0.08:
            # Call THROUGH a tracked alias rather than `print` directly —
            # the one shape v0.14.2's effect check treats identically to a
            # direct call (`Parser._resolve_effectful_alias`).
            return "%s(%s)" % (r.choice(self.alias_names), self.expr(depth + 1, local))
        if self.param_call_fns and r.random() < 0.06:
            # v0.14.9/v0.14.10 fuzz coverage: call a tracked fn (NAMED or
            # `let`-bound anonymous, both land in the same `param_call_fns`
            # pool — see `__init__`'s own docstring) passing `print`/`rand`/
            # an existing alias for the EXACT argument position its body
            # calls directly, so `_check_call_site_param_effects` (round
            # 300/302) actually fires its own ParseError path some of the
            # time, not just the ordinary per-callee effects check every
            # other call in this method already exercises.
            fn_name, arity, idx = r.choice(self.param_call_fns)
            args = []
            for i in range(arity):
                if i == idx and r.random() < 0.7:
                    args.append(self._alias_source())
                else:
                    args.append(self.expr(depth + 1, local))
            return "%s(%s)" % (fn_name, ", ".join(args))
        if self.fns and r.random() < 0.35:
            name, arity = r.choice(self.fns)
            if r.random() < 0.1:
                arity += 1
            return "%s(%s)" % (name, ", ".join(self.expr(depth + 1, local) for _ in range(arity)))
        name = r.choice(list(BUILTIN_ARITY))
        ar = BUILTIN_ARITY[name]
        n = r.randint(*ar) if isinstance(ar, tuple) else ar
        if r.random() < 0.06:
            n += 1
        if name in ("map", "filter"):
            args = [self.fnlike(depth, local), self.listlike(depth, local)]
        elif name == "fold":
            args = [self.fnlike(depth, local), self.expr(depth + 1, local),
                    self.listlike(depth, local)]
        elif name == "at" or (name == "steps" and n == 2):
            args = [self.expr(depth + 1, local), '"%s"' % r.choice(STEP_NAMES)]
        elif name in ("diverge", "contrast"):
            a1 = self.some_name(local)
            if n == 1:      # n-way form: a list of runs (v0.4 diverge, v0.6 contrast)
                args = ["[%s, %s]" % (a1, self.some_name(local))]
            else:
                args = [a1, r.choice([a1, self.some_name(local), self.expr(depth + 1, local)])]
        elif name == "note":
            args = ['"%s"' % r.choice(["k", "note"]), self.expr(depth + 1, local)]
        elif name == "range":
            args = [str(r.randint(-2, 15)) for _ in range(n)]
        elif name == "join":
            args = [self.listlike(depth, local), '"%s"' % r.choice([",", "", "-"])]
        elif name in ("push", "contains"):
            args = [self.listlike(depth, local), self.expr(depth + 1, local)]
        elif name in ("get", "has"):
            # half the time a plausible field name, so present/absent both fire
            args = [self.expr(depth + 1, local),
                    r.choice(['"%s"' % r.choice(FIELD_POOL),
                              self.expr(depth + 1, local)])]
        elif name == "guess":
            # confidence/source pools mix valid and invalid so both the
            # success path and the "confidence/source must be a str/num
            # in [0, 1]" propagated-miss path fire.
            args = [self.expr(depth + 1, local), r.choice(GUESS_CONFIDENCES),
                    r.choice(GUESS_SOURCES)]
        elif name == "sure":
            args = [self.expr(depth + 1, local), r.choice(GUESS_CONFIDENCES)]
        elif name in ("matches", "typed"):
            # Bias the VALUE toward a record: a structural spec can only
            # ever MATCH a record, and a generic `expr()` produces one
            # rarely enough (~5%) that the pass path would be near-dead.
            args = [self.recordlike(depth, local) if r.random() < 0.4
                    else self.expr(depth + 1, local),
                    self.spec_arg(depth, local)]
            if name == "typed":
                args.append(r.choice(TYPED_LABELS))
        else:
            args = [self.expr(depth + 1, local) for _ in range(n)]
        return "%s(%s)" % (name, ", ".join(args[:n] if n <= len(args) else args + [self.literal()]))

    def expr(self, depth, local):
        r = self.r
        if depth >= self.max_depth:
            return self.literal() if r.random() < 0.6 else self.some_name(local)
        p = r.random()
        d = depth + 1
        if p < 0.14:
            return self.literal()
        if p < 0.26:
            return self.some_name(local)
        if p < 0.32:
            return "[%s]" % ", ".join(self.expr(d, local) for _ in range(r.randint(0, 3)))
        if p < 0.37:
            names = r.sample(FIELD_POOL, r.randint(0, 3))
            return "@{%s}" % ", ".join("%s: %s" % (nm, self.expr(d, local)) for nm in names)
        if p < 0.42:
            if r.random() < 0.5:
                return "-%s" % self.expr(d, local)
            # Pre-existing generator/grammar mismatch, exposed (not caused)
            # by this round's RNG-sequence changes above: SPEC.md's own
            # documented precedence table ("rescue, or, and, not,
            # comparisons, ...") puts `not` BELOW comparisons/arithmetic,
            # so an unparenthesized `not EXPR` used as the operand of any
            # binop/index/field access other than `and`/`or` (e.g. `1 >=
            # not "a"`) is a genuine ParseError -- `parser.py`'s
            # `comparison`/`additive`/`multiplicative`/`unary` chain never
            # calls back up to `not_expr`. Explicit parens make it a
            # primary instead, valid at any precedence level (`(1 >= (not
            # "a"))` parses fine, confirmed directly against the parser).
            return "(not %s)" % self.expr(d, local)
        if p < 0.60:
            return "(%s %s %s)" % (self.expr(d, local), r.choice(BINOPS), self.expr(d, local))
        if p < 0.66:
            return "if %s { %s } else { %s }" % (self.expr(d, local), self.expr(d, local), self.expr(d, local))
        if p < 0.82:
            return self.call(d, local)
        if p < 0.86:
            return "%s[%s]" % (self.expr(d, local), r.choice(["0", "1", "-1", "2", '"a"', self.expr(d, local)]))
        if p < 0.89:
            return "%s.%s" % (self.expr(d, local), r.choice(FIELD_POOL))
        if p < 0.93:
            return "%s %s" % (r.choice(["why", "snip", "miss"]),
                              '"boom"' if r.random() < 0.5 else self.expr(d, local))
        if p < 0.97:
            return "(%s rescue %s)" % (self.expr(d, local), self.expr(d, local))
        return self.fnlike(depth, local)


# ------------------------------------------------------------------ oracle --

def _instrument():
    """`harness.swe.instrument`, imported lazily (round 401).

    Everything else in this package imports `fuzz` at module load; keeping
    the dependency one-way means adding the guard cannot change any import
    order, which is the kind of change that shows up as a different fuzz
    corpus three rounds later.
    """
    from . import instrument
    return instrument


class FuzzTimeout(Exception):
    pass


def _alarm(signum, frame):
    raise FuzzTimeout("program exceeded time budget")


class Outcome(object):
    """kind: ok | lex_error | parse_error | crash | timeout | invariant"""
    __slots__ = ("kind", "exc_type", "message", "frames", "seconds", "out", "phase")

    def __init__(self, kind, exc_type="", message="", frames=(), seconds=0.0,
                 out=(), phase=""):
        self.kind = kind
        self.exc_type = exc_type
        self.message = message
        self.frames = tuple(frames)   # innermost-last (function, lineno, file)
        self.seconds = seconds
        self.out = tuple(out)
        self.phase = phase

    def as_dict(self):
        return {"kind": self.kind, "exc_type": self.exc_type,
                "message": self.message, "frames": list(self.frames),
                "seconds": round(self.seconds, 4), "phase": self.phase}


def _whence_frames(tb, root):
    out = []
    for fr in traceback.extract_tb(tb):
        if os.sep + "whence" + os.sep in fr.filename or fr.filename.startswith(root):
            out.append((fr.name, fr.lineno, os.path.basename(fr.filename)))
    return out


def run_program(src, max_depth=2000, timeout_s=3.0, root=WHENCE_ROOT,
                check_invariants=True):
    """Run one program in-process under a wall-clock budget."""
    Interpreter, LexError, ParseError, Value, full_show = _import_whence(root)
    out = []
    interp = Interpreter(out=out.append, max_depth=max_depth)
    old = signal.signal(signal.SIGALRM, _alarm)
    signal.setitimer(signal.ITIMER_REAL, timeout_s)
    t0 = time.time()
    phase = "parse"
    try:
        try:
            from whence.parser import parse
            program = parse(src)
        except (LexError, ParseError) as e:
            kind = "lex_error" if isinstance(e, LexError) else "parse_error"
            return Outcome(kind, type(e).__name__, str(e), seconds=time.time() - t0,
                           out=out, phase=phase)
        phase = "run"
        from whence.interp import Env
        env = Env(interp.globals)
        for stmt in program.stmts:
            interp.exec_stmt(stmt, env)
        if check_invariants:
            phase = "invariant"
            for name, v in env.vars.items():
                if not isinstance(v, Value):
                    return Outcome("invariant", "NotAValue", "%s bound to %r" % (name, v),
                                   seconds=time.time() - t0, out=out, phase=phase)
                if v.prov.value is not v.payload:
                    return Outcome("invariant", "ProvValueMismatch",
                                   "%s: prov.value is not payload (%s vs %s)"
                                   % (name, full_show(v.prov.value)[:40],
                                      full_show(v.payload)[:40]),
                                   seconds=time.time() - t0, out=out, phase=phase)
        return Outcome("ok", seconds=time.time() - t0, out=out, phase="run")
    except FuzzTimeout:
        return Outcome("timeout", "FuzzTimeout", "exceeded %.1fs" % timeout_s,
                       seconds=time.time() - t0, out=out, phase=phase)
    except MemoryError:
        return Outcome("crash", "MemoryError", "out of memory",
                       seconds=time.time() - t0, out=out, phase=phase)
    except Exception as e:  # noqa: BLE001 — this is the oracle: any escape is a bug
        frames = _whence_frames(e.__traceback__, root)
        return Outcome("crash", type(e).__name__, str(e)[:200], frames=frames,
                       seconds=time.time() - t0, out=out, phase=phase)
    finally:
        signal.setitimer(signal.ITIMER_REAL, 0)
        signal.signal(signal.SIGALRM, old)


def signature(o):
    """Stable key for grouping crashes by root cause."""
    if o.kind not in ("crash", "invariant"):
        return (o.kind,)
    if o.exc_type == "RecursionError" and o.frames:
        # The innermost frame is wherever the cycle happened to be cut, which
        # depends on the caller's stack depth. Key on the cycle's dominant
        # function instead (ties broken by name -> deterministic).
        counts = {}
        for name, _, _ in o.frames:
            counts[name] = counts.get(name, 0) + 1
        # only functions that recur are part of the cycle; single-occurrence
        # frames (entry path, or the leaf helper the cut landed in) are noise
        cycle = sorted(n for n, c in counts.items() if c >= 2)
        return (o.kind, o.exc_type, "cycle:" + "+".join(cycle), o.phase)
    inner = o.frames[-1][0] if o.frames else "?"
    return (o.kind, o.exc_type, inner, o.message[:40])


# ----------------------------------------------------------------- shrinker --

def ddmin_lines(lines, keep):
    """Classic delta debugging over a list of lines; `keep(lines)` must be
    True for the input and stays True for the result."""
    n = 2
    while len(lines) >= 2:
        chunk = max(1, len(lines) // n)
        removed = False
        i = 0
        while i < len(lines):
            candidate = lines[:i] + lines[i + chunk:]
            if candidate and keep(candidate):
                lines = candidate
                n = max(n - 1, 2)
                removed = True
            else:
                i += chunk
        if not removed:
            if n >= len(lines):
                break
            n = min(n * 2, len(lines))
    return lines


def _minimize_ints(line, keep_line):
    """Binary-search every integer literal in `line` toward 0 while
    keep_line(new_line) stays True."""
    import re
    spans = [(m.start(), m.end()) for m in re.finditer(r"(?<![\w.])\d+(?![\w.])", line)]
    for start, end in reversed(spans):     # right to left keeps earlier spans valid
        value = int(line[start:end])
        lo, hi = 0, value
        best = value
        while lo < hi:
            mid = (lo + hi) // 2
            cand = line[:start] + str(mid) + line[end:]
            if keep_line(cand):
                best = mid
                hi = mid
            else:
                lo = mid + 1
        line = line[:start] + str(best) + line[end:]
    return line


def _minimize_repeats(line, keep_line):
    """Shrink runs of a repeated token by binary search on the run length:
    balanced bracket runs `(((x)))` / `[[[]]]` shrink both sides together;
    prefix runs (`- - -`, `why why`, `not not`) and ` + 1 + 1` chains shrink
    alone."""
    import re

    def search(count, build):
        lo, hi, best = 1, count, count
        while lo < hi:
            mid = (lo + hi) // 2
            if keep_line(build(mid)):
                best, hi = mid, mid
            else:
                lo = mid + 1
        return build(best)

    for open_c, close_c in (("(", ")"), ("[", "]")):
        m = re.search(r"(\%s{4,})([^%s%s]*)(\%s{4,})" % (open_c, open_c, close_c, close_c), line)
        if m and len(m.group(1)) == len(m.group(3)):
            n = len(m.group(1))
            mid_text = m.group(2)
            line = search(n, lambda k, m=m, mid_text=mid_text: line[:m.start()] + open_c * k + mid_text + close_c * k + line[m.end():])
    for unit in ("- ", "why ", "not ", "snip "):
        m = re.search(r"((?:%s){4,})" % re.escape(unit), line)
        if m:
            n = len(m.group(1)) // len(unit)
            line = search(n, lambda k, m=m: line[:m.start()] + unit * k + line[m.end():])
    m = re.search(r"((?: \+ 1){4,})", line)
    if m:
        n = len(m.group(1)) // 4
        line = search(n, lambda k, m=m: line[:m.start()] + " + 1" * k + line[m.end():])
    return line


def shrink(src, keep, max_rounds=3):
    """Minimise `src` while keep(src) stays True. Line ddmin first, then
    per-line integer and repeat-run minimisation, repeated to a fixpoint."""
    lines = [ln for ln in src.split("\n") if ln.strip()]
    if not keep("\n".join(lines) + "\n"):
        return None   # flaky reproducer (non-deterministic); leave unminimised
    for _ in range(max_rounds):
        before = list(lines)
        lines = ddmin_lines(lines, lambda ls: keep("\n".join(ls) + "\n"))
        new_lines = []
        for i, ln in enumerate(lines):
            def keep_line(cand, i=i):
                trial = lines[:i] + [cand] + lines[i + 1:]
                return keep("\n".join(trial) + "\n")
            ln = _minimize_repeats(ln, keep_line)
            ln = _minimize_ints(ln, keep_line)
            new_lines.append(ln)
            lines = lines[:i] + [ln] + lines[i + 1:]
        lines = new_lines
        if lines == before:
            break
    return "\n".join(lines) + "\n"


# ----------------------------------------------------------------- campaign --

class Crasher(object):
    def __init__(self, sig, seed, src, outcome, minimized=None):
        self.sig = sig
        self.seed = seed
        self.src = src
        self.outcome = outcome
        self.minimized = minimized

    def as_dict(self):
        return {"signature": list(self.sig), "seed": self.seed,
                "outcome": self.outcome.as_dict(),
                "src_lines": self.src.count("\n"),
                "minimized": self.minimized,
                "minimized_lines": self.minimized.count("\n") if self.minimized else None}


class Campaign(object):
    def __init__(self):
        self.counts = {}
        self.crashers = {}   # sig -> Crasher (first seen)
        self.programs = 0
        self.seconds = 0.0
        # (round 401) Round 389's item 4. A campaign is one object, so the
        # guard is start-vs-end rather than row-vs-row: if `fuzz.py` or the
        # whence tree moved while the campaign ran, the programs before the
        # edit and the programs after it are two populations.
        self.instrument = None
        self.instrument_end = None

    def summary(self):
        lines = ["fuzz: %d programs in %.1fs" % (self.programs, self.seconds)]
        for k in sorted(self.counts):
            lines.append("  %-12s %d" % (k, self.counts[k]))
        lines.append("  unique crash signatures: %d" % len(self.crashers))
        for sig, c in sorted(self.crashers.items(), key=lambda kv: kv[0]):
            lines.append("  - %s  (seed %d, %d lines%s)" % (
                " | ".join(sig), c.seed, c.src.count("\n"),
                ", minimized to %d" % c.minimized.count("\n") if c.minimized else ""))
        return "\n".join(lines)

    def instrument_moved(self):
        """Parts of the instrument that differ between the campaign's start
        and its end. Empty list = one population."""
        start, end = self.instrument or {}, self.instrument_end or {}
        return sorted(k for k in start
                      if k != "lane" and end.get(k, start[k]) != start[k])

    def as_dict(self):
        return {"programs": self.programs, "seconds": round(self.seconds, 2),
                "counts": self.counts,
                "instrument": self.instrument,
                "instrument_end": self.instrument_end,
                "instrument_moved": self.instrument_moved(),
                "crashers": [c.as_dict() for c in self.crashers.values()]}


def fuzz(seed=0, n=200, max_depth=2000, timeout_s=3.0, root=WHENCE_ROOT,
         do_shrink=True, stress_rate=0.5, on_program=None):
    camp = Campaign()
    camp.instrument = _instrument().stamp("fuzz.fuzz")
    t0 = time.time()
    for i in range(n):
        s = seed * 1000003 + i
        src = ProgramGen(s, stress_rate=stress_rate).program()
        o = run_program(src, max_depth=max_depth, timeout_s=timeout_s, root=root)
        camp.programs += 1
        camp.counts[o.kind] = camp.counts.get(o.kind, 0) + 1
        if on_program:
            on_program(i, src, o)
        sig = signature(o)
        if o.kind in ("crash", "invariant") and sig not in camp.crashers:
            cr = Crasher(sig, s, src, o)
            if do_shrink:
                def keep(cand, sig=sig):
                    return signature(run_program(cand, max_depth=max_depth,
                                                 timeout_s=timeout_s, root=root)) == sig
                cr.minimized = shrink(src, keep)
            camp.crashers[sig] = cr
    camp.seconds = time.time() - t0
    camp.instrument_end = _instrument().stamp("fuzz.fuzz")
    return camp


if __name__ == "__main__":
    import argparse
    ap = argparse.ArgumentParser()
    ap.add_argument("--seed", type=int, default=0)
    ap.add_argument("-n", type=int, default=200)
    ap.add_argument("--no-shrink", action="store_true")
    ap.add_argument("--show", action="store_true", help="print minimized crashers")
    ap.add_argument("--limit", type=int, default=0,
                    help="host recursion limit (run.py uses 6000; the default "
                         "limit's reserve hides linear frame undercounts — "
                         "round 108)")
    a = ap.parse_args()
    if a.limit:
        sys.setrecursionlimit(a.limit)
    c = fuzz(a.seed, a.n, do_shrink=not a.no_shrink)
    print(c.summary())
    if a.show:
        for sig, cr in c.crashers.items():
            print("\n### %s\n%s" % (" | ".join(sig), cr.minimized or cr.src))
