"""Re-pin `tests/test_generated_killers.py` when a deliberate language change
moves what it pinned -- and PROVE that nothing else moved with it.

Round 450 (language C). That file opens *"GENERATED by harness/swe/killers.py
-- do not edit by hand"*, and each test is an ORACLE:
`assert run(src) == <the original interpreter's behaviour>`, kept because a
mutant the hand-written suite let survive produced something else. Two things
about it are true at once:

  * regenerating it needs the mutation JSONs those killers came from, which
    are not kept, so a deliberate change to the language leaves the file red
    with no supported way to make it green again; and
  * the expectation is not decoration, it is the entire kill. Paste in
    whatever the interpreter prints today and the test still passes, still
    looks like a regression pin, and nothing in the repo would ever say the
    discrimination had been thrown away.

MEASURED, and the reason this module does not do the obvious thing. The
obvious verification is "rebuild the mutant from its id and check the test
still separates it". `--audit-ids` scores that: at round 450, **0 of 64** pins
have a mutant id whose (file, line, description) still names a mutation site
in the tree. A mutant id is a LINE NUMBER plus a generation counter, both of
which move whenever the mutated file is edited, and `whence/interp.py` and
`whence/values.py` have been edited in most rounds since. Matching on
description alone is not a fallback -- `interp.py:486:ifneg#150`'s description
is `negate if-condition`, which describes **486** distinct sites in today's
interp.py. The kill each test encodes is not recoverable from the file.

So the obligation this module CAN discharge, exactly:

    the difference between the old pin and the new pin is fully explained
    by the diff between `--baseline-ref` and the working tree.

It re-runs each pinned program twice -- once against the tree as of
`--baseline-ref` (default HEAD) and once against the working tree -- and
re-pins only when the baseline run REPRODUCES the pinned expectation exactly.
That is what makes the rewrite safe: if anything other than the declared
change had moved the oracle, the baseline run would not reproduce the old pin
either, and the pin is reported `stale` and left alone. It is a differential
re-pin, not a "paste in what it prints now".

    python3 -m swe.killerrepin --check                  # verdicts, no writes
    python3 -m swe.killerrepin --write                  # re-pin the movers
    python3 -m swe.killerrepin --audit-ids              # mutant-id decay

Verdicts:

  `holds`   the pinned expectation still matches the working tree.
  `repin`   it moved, AND the baseline tree reproduces the OLD pin exactly.
            The movement is attributable to the working-tree diff. Written.
  `stale`   it moved and the BASELINE does not reproduce it either, so the pin
            was already wrong before this change, or the program is not
            deterministic. Never written; reported for a human.
"""

import argparse
import ast
import os
import re
import shutil
import subprocess
import sys
import tempfile

HERE = os.path.dirname(os.path.abspath(__file__))
if __package__ in (None, ""):                    # run as a script
    sys.path.insert(0, os.path.dirname(HERE))

from swe import killers, mutation                                # noqa: E402

WHENCE_ROOT = killers.WHENCE_ROOT
TEST_PATH = os.path.join(WHENCE_ROOT, "tests", "test_generated_killers.py")

#: `mutant <id>: <description> (line <n>) — mutant gave <json prefix>`, the
#: docstring `killers.render_tests` writes. The tail is `docstring_safe`'d and
#: cut at 120 chars, so it is a lossy prefix and is parsed but not trusted.
_DOC = re.compile(
    r'^mutant (?P<id>[^\s:]+:\d+:\w+#\d+): (?P<desc>.*?) \(line (?P<line>\d+)\)'
    r'(?: — mutant gave (?P<gave>.*))?$', re.S)


class Pin(object):
    """One `def test_kill_*():` block of the generated file."""

    def __init__(self, name, mutant_id, path, lineno, desc, src, expected,
                 assert_lo, assert_hi):
        self.name = name
        self.mutant_id = mutant_id
        self.path = path            # basename of the mutated file, per the id
        self.lineno = lineno
        self.desc = desc            # already `docstring_safe`'d
        self.src = src              # the Whence program
        self.expected = expected    # the pinned behaviour dict
        self.assert_lo = assert_lo  # 0-based line range of the assert stmt
        self.assert_hi = assert_hi

    def __repr__(self):
        return "<Pin %s>" % self.name


def parse_pins(text):
    """Every `test_kill_*` in the generated file, as `Pin`s.

    Parsed with `ast`, not a regex over the source: `src` and the expectation
    are `repr()` output full of quotes, backslashes and newlines, and a regex
    that gets those right is a second Python parser.
    """
    tree = ast.parse(text)
    out = []
    for node in tree.body:
        if not isinstance(node, ast.FunctionDef):
            continue
        if not node.name.startswith("test_kill_"):
            continue
        m = _DOC.match(ast.get_docstring(node) or "")
        if not m:
            continue
        src = expected = lo = hi = None
        for stmt in node.body:
            if (isinstance(stmt, ast.Assign) and len(stmt.targets) == 1
                    and isinstance(stmt.targets[0], ast.Name)
                    and stmt.targets[0].id == "src"):
                src = ast.literal_eval(stmt.value)
            elif isinstance(stmt, ast.Assert) and isinstance(stmt.test, ast.Compare):
                cmp_ = stmt.test
                if (len(cmp_.ops) == 1 and isinstance(cmp_.ops[0], ast.Eq)
                        and len(cmp_.comparators) == 1):
                    expected = ast.literal_eval(cmp_.comparators[0])
                    lo, hi = stmt.lineno - 1, stmt.end_lineno - 1
        if src is None or expected is None:
            continue
        path, lineno, _ = m.group("id").split(":", 2)
        out.append(Pin(node.name, m.group("id"), path, int(lineno),
                       m.group("desc"), src, expected, lo, hi))
    return out


# --- mutant-id decay ------------------------------------------------------

def audit_ids(pins, project_root=WHENCE_ROOT):
    """`{name: (n_exact, n_by_description)}` -- can each pin's mutant still be
    found in the tree? `n_exact == 1` means the id's (line, description) still
    names exactly one site. Anything else means the kill is not rebuildable
    from what the file records."""
    cache = {}
    out = {}
    for pin in pins:
        if pin.path not in cache:
            full = os.path.join(project_root, "whence", pin.path)
            if not os.path.exists(full):
                cache[pin.path] = []
            else:
                with open(full, encoding="utf-8") as f:
                    cache[pin.path] = mutation.generate(f.read(), pin.path)
        ms = cache[pin.path]
        by_desc = [m for m in ms
                   if killers.docstring_safe(m.description) == pin.desc]
        exact = [m for m in by_desc if m.lineno == pin.lineno]
        out[pin.name] = (len(exact), len(by_desc))
    return out


# --- the differential re-pin ---------------------------------------------

def _tracked_whence_files(project_root, ref):
    rel = subprocess.run(["git", "ls-files", "whence"], cwd=project_root,
                         capture_output=True, text=True, check=True)
    return [p for p in rel.stdout.split() if p.endswith(".py")]


def build_baseline(project_root, ref, dst):
    """A copy of `project_root` whose `whence/` package is the one at `ref`.

    Only the package is rewound. Tests, examples and tooling stay as they are
    in the working tree, because the question is what the INTERPRETER did, not
    what the repo looked like.
    """
    mutation._copy_project(project_root, dst)
    for rel in _tracked_whence_files(project_root, ref):
        # `./` matters: in `git show REF:PATH` a bare PATH is resolved from the
        # REPO ROOT, and `project_root` is a subdirectory of one.
        blob = subprocess.run(["git", "show", "%s:./%s" % (ref, rel)],
                              cwd=project_root, capture_output=True, check=True)
        target = os.path.join(dst, rel)
        os.makedirs(os.path.dirname(target), exist_ok=True)
        with open(target, "wb") as f:
            f.write(blob.stdout)
    return dst


def moved_keys(old, new, prefix=""):
    """Dotted paths of the leaves that differ between two behaviour dicts --
    the shape of a re-pin, so a reviewer sees `vals.v1` rather than a wall of
    rendered text."""
    if isinstance(old, dict) and isinstance(new, dict):
        out = []
        for k in sorted(set(old) | set(new)):
            out.extend(moved_keys(old.get(k), new.get(k), prefix + "." + str(k)))
        return out
    if isinstance(old, list) and isinstance(new, list) and len(old) == len(new):
        out = []
        for i, (a, b) in enumerate(zip(old, new)):
            out.extend(moved_keys(a, b, "%s[%d]" % (prefix, i)))
        return out
    return [] if old == new else [prefix.lstrip(".") or "<root>"]


def judge_all(pins, project_root=WHENCE_ROOT, ref="HEAD", timeout_s=8.0):
    """`[(pin, verdict, new_behaviour, moved)]`, one per pin.

    Two package loads for the whole run, not two per pin: `load_whence` costs
    an import of the whole interpreter and the baseline copy costs a project
    copytree, and neither depends on the pin.
    """
    head = killers.load_whence(project_root, "repin_head")
    tmp = tempfile.mkdtemp(prefix="repin-base-")
    try:
        base_root = build_baseline(project_root, ref, os.path.join(tmp, "proj"))
        base = killers.load_whence(base_root, "repin_base")
        out = []
        for pin in pins:
            new = killers.behaviour(head, pin.src, timeout_s=timeout_s)
            if new == pin.expected:
                out.append((pin, "holds", new, []))
                continue
            was = killers.behaviour(base, pin.src, timeout_s=timeout_s)
            verdict = "repin" if was == pin.expected else "stale"
            out.append((pin, verdict, new, moved_keys(pin.expected, new)))
        return out
    finally:
        shutil.rmtree(tmp, ignore_errors=True)
        for tag in ("repin_base",):
            name = "whence_" + tag
            for k in [k for k in sys.modules
                      if k == name or k.startswith(name + ".")]:
                del sys.modules[k]


def rewrite(text, updates):
    """Replace the `assert` line of each `(pin, new)` in `updates`.

    Bottom-up so an earlier rewrite cannot move a later pin's line numbers,
    and rendered exactly the way `killers.render_tests` renders it, so a
    re-pinned file is byte-identical to a freshly generated one.
    """
    lines = text.splitlines(keepends=True)
    for pin, new in sorted(updates, key=lambda pv: -pv[0].assert_lo):
        lines[pin.assert_lo:pin.assert_hi + 1] = [
            "    assert run(src) == %r\n" % (new,)]
    return "".join(lines)


def main(argv=None):
    ap = argparse.ArgumentParser(description=__doc__.splitlines()[0])
    ap.add_argument("--project", default=WHENCE_ROOT)
    ap.add_argument("--tests", default=TEST_PATH)
    ap.add_argument("--ref", default="HEAD",
                    help="git ref whose whence/ package is the baseline")
    ap.add_argument("--only", action="append", default=None)
    ap.add_argument("--timeout", type=float, default=8.0)
    g = ap.add_mutually_exclusive_group(required=True)
    g.add_argument("--check", action="store_true")
    g.add_argument("--write", action="store_true")
    g.add_argument("--audit-ids", action="store_true")
    args = ap.parse_args(argv)

    with open(args.tests, encoding="utf-8") as f:
        text = f.read()
    pins = parse_pins(text)
    if args.only:
        pins = [p for p in pins if p.name in set(args.only)]

    if args.audit_ids:
        scores = audit_ids(pins, args.project)
        exact = sum(1 for v in scores.values() if v[0] == 1)
        uniq = sum(1 for v in scores.values() if v[0] != 1 and v[1] == 1)
        for name in sorted(scores):
            n_exact, n_desc = scores[name]
            if n_exact != 1:
                print("decayed  %-44s exact %d, by-description %d"
                      % (name, n_exact, n_desc))
        print("\n%d pin(s): %d rebuildable by (line, description), "
              "%d more by a UNIQUE description, %d not rebuildable"
              % (len(pins), exact, uniq, len(pins) - exact - uniq))
        return 0

    results = judge_all(pins, args.project, args.ref, args.timeout)
    counts = {}
    updates = []
    for pin, verdict, new, moved in results:
        counts[verdict] = counts.get(verdict, 0) + 1
        if verdict != "holds":
            print("%-6s %-44s moved: %s" % (verdict, pin.name, ", ".join(moved)))
        if verdict == "repin":
            updates.append((pin, new))
    print("\n%d pin(s) against %s: %s" % (
        len(results), args.ref,
        ", ".join("%s %d" % (k, counts[k]) for k in sorted(counts))))
    if args.write and updates:
        with open(args.tests, "w", encoding="utf-8") as f:
            f.write(rewrite(text, updates))
        print("wrote %d re-pinned assertion(s) to %s" % (len(updates), args.tests))
    elif args.write:
        print("nothing to write")
    return 1 if counts.get("stale") else 0


if __name__ == "__main__":
    sys.exit(main())
