"""A RECORDED, resumable view of the slow test tier (round 341, SWE-loop D).

Why this exists
---------------
`harness/tests/conftest.py` splits the suite into a fast core tier and a slow
`swe_slow` tier (every `test_swe_*.py`), and `run_tests_fast.sh` — the health
check the driver runs every round — deselects the slow tier entirely. That
was the right call for round 223's problem (six consecutive rounds could not
finish a synchronous full run inside a round's budget) but it left a
coverage gap of exactly the shape round 283 named for `git_committed`: **a
green round report is not evidence the slow tier passes.** Round 338 found
five real failures sitting in it, and found them only because round 336's
backgrounded `nohup` run happened to still be alive for someone to read.

The standing `nohup ... &` convention is not a fix for that: it produces an
orphaned process whose output nobody reads, on a ONE-CPU box where the full
tier takes 76 minutes against a 55-minute round timeout. Worse — see
`checkout_digest` below — it produces results computed against a checkout
that a LATER round is concurrently editing.

What this module provides
-------------------------
An append-only ledger (`state/slow-tier-ledger.jsonl`) of per-file outcomes,
each stamped with the digest of the whence checkout it was computed against,
plus a planner that spends a bounded time budget on whatever is least
covered. Over several rounds the tier gets covered incrementally, and — the
part that actually matters — **what is NOT covered is visible**, instead of
being indistinguishable from green.

Fail-closed rules, all three load-bearing (cf. round 340's `gap_continuity`):
  1. A file with no ledger entry is `unknown`, never `pass`. Absence of
     evidence is recorded as absence of evidence.
  2. An entry whose `checkout_digest` differs from the current tree is
     `stale_checkout`. Its pass said something true about a tree that no
     longer exists.
  3. An entry whose digest CHANGED WHILE THE RUN WAS IN FLIGHT
     (`checkout_stable: false`) can never be fresh, whatever it reported.
     This is round 341's own finding made mechanical: four of round 338's
     five failures are caused by exactly that race, and a PASS produced
     under it is no more trustworthy than the FAIL.

Everything here is offline-testable: `run_slice` takes an injectable
`runner`, so no test in `test_slowtier.py` shells out to pytest.
"""
import hashlib
import json
import os
import subprocess
import sys
import time

HERE = os.path.dirname(os.path.abspath(__file__))
HARNESS_ROOT = os.path.dirname(HERE)
REPO_ROOT = os.path.dirname(HARNESS_ROOT)
TESTS_DIR = os.path.join(HARNESS_ROOT, "tests")
DEFAULT_LEDGER = os.path.join(REPO_ROOT, "state", "slow-tier-ledger.jsonl")
DEFAULT_WHENCE = os.path.join(REPO_ROOT, "languages", "whence")

# Mirrors `swe.mutation._copy_project`'s own ignore list — the digest must
# cover exactly what a test's scratch copy would see, and nothing that is
# regenerated by merely RUNNING the suite (`__pycache__`, `.pytest_cache`),
# which would otherwise make every run invalidate its own predecessor.
_IGNORED_DIRS = ("__pycache__", ".pytest_cache", ".venv", "research-env", ".git")


def _is_ignored(rel):
    parts = rel.replace(os.sep, "/").split("/")
    return any(p in _IGNORED_DIRS or p.endswith(".egg-info") for p in parts)


def checkout_digest(root=DEFAULT_WHENCE):
    """A stable content digest of every `.py` file in the checkout.

    `.py` only, deliberately: these tests read, mutate, unparse and diff
    Python sources of the interpreter. A `SPEC.md` edit does not move a
    line number in `whence/interp.py`, and counting it would mark results
    stale for a change that cannot affect them — a false alarm is as
    corrosive here as a false pass (round 339's rule: a checker nobody
    watches must not cry wolf).
    """
    h = hashlib.sha256()
    files = []
    for dirpath, dirnames, names in os.walk(root):
        dirnames[:] = [d for d in dirnames
                       if d not in _IGNORED_DIRS and not d.endswith(".egg-info")]
        for n in sorted(names):
            if not n.endswith(".py"):
                continue
            full = os.path.join(dirpath, n)
            rel = os.path.relpath(full, root)
            if _is_ignored(rel):
                continue
            files.append((rel.replace(os.sep, "/"), full))
    for rel, full in sorted(files):
        h.update(rel.encode("utf-8"))
        h.update(b"\0")
        try:
            with open(full, "rb") as f:
                h.update(hashlib.sha256(f.read()).digest())
        except (IOError, OSError):
            # A file that vanished mid-walk is itself a change; fold the
            # fact (not a crash) into the digest.
            h.update(b"<unreadable>")
    return h.hexdigest()[:16]


def slow_tier_files(tests_dir=TESTS_DIR):
    """The files `conftest.py` marks `swe_slow` — its rule verbatim:
    `item.fspath.basename.startswith("test_swe_")`."""
    return sorted(n for n in os.listdir(tests_dir)
                  if n.startswith("test_swe_") and n.endswith(".py"))


# ------------------------------------------------------------------ ledger --

def append_entry(path, entry):
    d = os.path.dirname(path)
    if d and not os.path.isdir(d):
        os.makedirs(d)
    with open(path, "a", encoding="utf-8") as f:
        f.write(json.dumps(entry, sort_keys=True) + "\n")


def read_entries(path):
    if not os.path.exists(path):
        return []
    out = []
    with open(path, encoding="utf-8") as f:
        for line in f:
            line = line.strip()
            if not line:
                continue
            try:
                out.append(json.loads(line))
            except ValueError:
                # A torn last line (a round killed mid-append) is skipped,
                # not fatal: the ledger is evidence, and an unreadable
                # record is simply absent evidence — rule 1 then applies.
                continue
    return out


def latest_by_file(entries):
    """Most recent entry per file, by `finished_at` (ties -> later line)."""
    best = {}
    for e in entries:
        f = e.get("file")
        if not f:
            continue
        cur = best.get(f)
        if cur is None or e.get("finished_at", 0) >= cur.get("finished_at", 0):
            best[f] = e
    return best


# ------------------------------------------------------------------ status --

def classify(entry, digest):
    """The fail-closed state machine. See this module's docstring."""
    if entry is None:
        return "unknown"
    if not entry.get("checkout_stable", False):
        return "raced"
    if entry.get("checkout_digest") != digest:
        return "stale_checkout"
    if entry.get("outcome") == "passed":
        return "fresh_pass"
    if entry.get("outcome") == "failed":
        return "fresh_fail"
    return "unknown"


#: States that are genuine evidence about the CURRENT checkout.
CONCLUSIVE = ("fresh_pass", "fresh_fail")


def status(ledger_path=DEFAULT_LEDGER, tests_dir=TESTS_DIR, whence_root=DEFAULT_WHENCE,
           digest=None):
    digest = checkout_digest(whence_root) if digest is None else digest
    best = latest_by_file(read_entries(ledger_path))
    rows = []
    for f in slow_tier_files(tests_dir):
        e = best.get(f)
        rows.append({
            "file": f,
            "state": classify(e, digest),
            "outcome": (e or {}).get("outcome"),
            "finished_at": (e or {}).get("finished_at"),
            "seconds": (e or {}).get("seconds"),
            "checkout_digest": (e or {}).get("checkout_digest"),
        })
    covered = [r for r in rows if r["state"] in CONCLUSIVE]
    return {
        "digest": digest,
        "rows": rows,
        "n_files": len(rows),
        "n_conclusive": len(covered),
        "n_failing": len([r for r in rows if r["state"] == "fresh_fail"]),
        # The recall this view has on the CURRENT tree. Round 339's rule:
        # a checker must report its own recall so the gap stays visible.
        "coverage": (float(len(covered)) / len(rows)) if rows else 0.0,
    }


def plan(st, budget_s, default_s=300.0):
    """Which files to run next, in order, inside `budget_s`.

    Order: never-conclusive first (worst evidence first), then oldest
    `finished_at`. Estimated cost is the file's own last measured
    `seconds`, `default_s` when unmeasured. A file whose estimate ALONE
    exceeds the budget is still returned as the sole entry when nothing
    else fits — otherwise a file slower than every budget would never run
    again, which is precisely the silent-truncation failure this module
    exists to prevent.
    """
    def key(r):
        conclusive = r["state"] in CONCLUSIVE
        return (1 if conclusive else 0, r["finished_at"] or 0, r["file"])

    ordered = sorted(st["rows"], key=key)
    picked, spent = [], 0.0
    for r in ordered:
        est = r["seconds"] or default_s
        if picked and spent + est > budget_s:
            continue
        picked.append(r["file"])
        spent += est
        if spent >= budget_s:
            break
    return picked


# --------------------------------------------------------------------- run --

def pytest_runner(test_file, tests_dir=TESTS_DIR, timeout_s=3000):
    """The real runner: one pytest process per file, cwd at the repo root.

    `PYTHONDONTWRITEBYTECODE` is set for round 340's reason — a `.pyc`
    whose cache key (source size, source mtime truncated to whole seconds)
    collides with a since-edited source makes a run test the WRONG
    bytecode. The whence tree is edited by other rounds between slices, so
    this is not hypothetical here.
    """
    env = dict(os.environ)
    env["PYTHONDONTWRITEBYTECODE"] = "1"
    cmd = [sys.executable, "-m", "pytest", "-q", "-p", "no:randomly",
           os.path.join(tests_dir, test_file)]
    try:
        p = subprocess.Popen(cmd, cwd=REPO_ROOT, env=env,
                             stdout=subprocess.PIPE, stderr=subprocess.STDOUT)
        out, _ = p.communicate(timeout=timeout_s)
        rc = p.returncode
        timed_out = False
    except subprocess.TimeoutExpired:
        p.kill()
        out, _ = p.communicate()
        rc, timed_out = -9, True
    text = (out or b"").decode("utf-8", "replace")
    return {"returncode": rc, "timed_out": timed_out, "tail": text[-800:]}


def run_slice(files, ledger_path=DEFAULT_LEDGER, whence_root=DEFAULT_WHENCE,
              runner=pytest_runner, clock=time.time, log=None):
    """Run each file, recording one ledger entry apiece.

    The digest is read BEFORE and AFTER each file. If it moved, the entry
    is stamped `checkout_stable: false` and can never be counted as
    evidence (rule 3) — the run overlapped another round editing the tree,
    which is exactly how four of round 338's five failures are produced.
    """
    log = log or (lambda s: None)
    written = []
    for f in files:
        before = checkout_digest(whence_root)
        t0 = clock()
        r = runner(f)
        t1 = clock()
        after = checkout_digest(whence_root)
        stable = (before == after)
        outcome = ("timeout" if r.get("timed_out") else
                   "passed" if r.get("returncode") == 0 else "failed")
        entry = {
            "file": f,
            "outcome": outcome,
            "returncode": r.get("returncode"),
            "seconds": round(t1 - t0, 2),
            "finished_at": t1,
            "checkout_digest": before,
            "checkout_digest_after": after,
            "checkout_stable": stable,
            "tail": r.get("tail", "")[-800:],
        }
        append_entry(ledger_path, entry)
        written.append(entry)
        log("%-34s %-8s %6.1fs%s" % (f, outcome, entry["seconds"],
                                     "" if stable else "  [CHECKOUT CHANGED MID-RUN]"))
    return written


# ------------------------------------------------------------------ report --

def report_text(st):
    lines = ["slow tier: %d files, %d conclusive against checkout %s (%.0f%% recall), %d failing"
             % (st["n_files"], st["n_conclusive"], st["digest"],
                100.0 * st["coverage"], st["n_failing"])]
    for r in sorted(st["rows"], key=lambda r: (r["state"] != "fresh_fail", r["file"])):
        age = ""
        if r["finished_at"]:
            age = "  %.1fh ago" % ((time.time() - r["finished_at"]) / 3600.0)
        lines.append("  %-34s %-14s %s%s"
                     % (r["file"], r["state"],
                        ("%.0fs" % r["seconds"]) if r["seconds"] else "-", age))
    if st["n_conclusive"] < st["n_files"]:
        lines.append("  NOTE: %d file(s) are NOT evidence about this checkout."
                     % (st["n_files"] - st["n_conclusive"]))
    return "\n".join(lines)


def main(argv=None):
    import argparse
    ap = argparse.ArgumentParser(description=__doc__.splitlines()[0])
    ap.add_argument("cmd", choices=["status", "plan", "run"])
    ap.add_argument("--ledger", default=DEFAULT_LEDGER)
    ap.add_argument("--budget-s", type=float, default=900.0)
    a = ap.parse_args(argv)
    st = status(ledger_path=a.ledger)
    if a.cmd == "status":
        print(report_text(st))
        return 1 if st["n_failing"] else 0
    picked = plan(st, a.budget_s)
    if a.cmd == "plan":
        print("\n".join(picked) or "(nothing to run)")
        return 0
    run_slice(picked, ledger_path=a.ledger, log=lambda s: print(s))
    print(report_text(status(ledger_path=a.ledger)))
    return 0


if __name__ == "__main__":
    sys.exit(main())
