"""Auto-registers the `whence_slow` marker (round 242) and fixes up
sys.path so `tests/` can `import whence` from a bare checkout with no
install step.

`whence_slow` is hand-placed on the ~35 individual test functions (out of
875) that dominate this suite's wall-clock — measured live via
`pytest --durations=0` (round 241: 875 tests / 404.61s total; the top 2
alone, `test_v10.py::test_three_way_on_big_examples[meta.lang]` and
`test_v09.py::test_three_way_on_examples_that_recurse`, are 92.91s+71.19s,
40% of the whole suite by themselves). Unlike harness/tests/'s
`test_swe_*.py` filename convention (round 235), Whence's slow tests are
scattered across shared, version-numbered files (test_v09.py, test_v10.py,
test_self_hosting.py, ...) that also hold plenty of fast tests, so there is
no filename prefix to key off — the marker has to sit on the individual
`def test_...():` line. Run `run_tests_fast.sh` (or
`pytest -m "not whence_slow" tests/`) for a synchronous, complete signal
that finishes in seconds instead of ~7 minutes; a bare `pytest tests/`
still runs everything, unchanged. See knowledge/round-242-whence-tests-
fast-slow-tiering.md for the full derivation and the regenerate recipe.
"""

import os
import sys

sys.path.insert(0, os.path.dirname(os.path.dirname(os.path.abspath(__file__))))


def pytest_configure(config):
    config.addinivalue_line(
        "markers",
        "whence_slow: individually-marked slow test (self-hosting/guest-"
        "evaluator/three-way-differential/bench-in-fresh-process) — real "
        "cost from running the actual interpreter over large programs, not "
        "a flake. Deselect with `-m \"not whence_slow\"` for a fast smoke "
        "run (see run_tests_fast.sh).",
    )


# ---------------------------------------------------------------------------
# Round 452 (language C), closing round 450's next-step 3.
#
# `tests/test_generated_killers.py` opens "GENERATED by harness/swe/killers.py
# — do not edit by hand", and it CANNOT be regenerated: the mutation JSONs its
# 64 oracles came from are not kept. So a deliberate language change leaves it
# red with no supported way to make it green, and round 450 built
# `harness/swe/killerrepin.py` for exactly that — a differential re-pin that
# rewrites an expectation only when the tree at a baseline ref reproduces the
# OLD one, so the movement is attributable to the working-tree diff and to
# nothing else.
#
# Round 450 then wrote down the gap it had left: "`killerrepin` can re-pin,
# and nothing schedules it. The tool exists ... but the next deliberate
# language change will still surface as eleven mystery reds unless someone
# knows to run it. Either the whence tier should fail with a pointer, or
# `killers.py`'s generated header should name it."
#
# This is the first half. It fires only when a killer actually fails, names
# the tool and the two commands, and says the thing a reader most needs to
# hear — that `--check` can REFUSE, and a `stale` verdict means the pin was
# already wrong and must not be rewritten. Round 452 was the first deliberate
# language change after round 450 (v0.44, decision 53) and hit this exact
# situation one round later: 2 of 64 killers red, `holds 62, repin 2, stale 0`.
# The generator's own header carries the same pointer for the day the file can
# be regenerated.

_KILLER_FILE = "test_generated_killers"


def pytest_terminal_summary(terminalreporter, exitstatus, config):
    failed = terminalreporter.stats.get("failed", ())
    hits = [r for r in failed if _KILLER_FILE in getattr(r, "nodeid", "")]
    if not hits:
        return
    w = terminalreporter.write_line
    w("")
    w("%d generated killer(s) failed. That file cannot be regenerated —"
      % len(hits))
    w("do NOT paste in what the interpreter prints today; the expectation IS")
    w("the kill. Re-pin differentially instead:")
    w("")
    w("    cd harness && python3 -m swe.killerrepin --check   # verdicts only")
    w("    cd harness && python3 -m swe.killerrepin --write   # re-pin movers")
    w("")
    w("`repin` = the baseline tree reproduces the OLD pin, so this diff")
    w("explains the move. `stale` = it does not, and the pin was already")
    w("wrong; killerrepin never writes those and neither should you.")
