"""GENERATED by harness/swe/killers.py — do not edit by hand.

Each test pins the behaviour of a program that distinguished the original
interpreter from a mutant that the hand-written suite let survive. The
docstring names the mutant (file:line:operator) and what it changed.
"""

from whence.interp import Interpreter, Env
from whence.lexer import LexError
from whence.parser import ParseError
from whence.values import full_show


def canonical(src, Interpreter, Env, LexError, ParseError, full_show, max_depth=500):
    """Behaviour of a program as plain data: kind, printed lines, check
    results, and the rendering of every top-level binding."""
    out = []
    interp = Interpreter(out=out.append, max_depth=max_depth)
    try:
        from_parse = __import__(Interpreter.__module__.rsplit(".", 1)[0] + ".parser",
                                fromlist=["parse"])
        program = from_parse.parse(src)
    except (LexError, ParseError) as e:
        return {"kind": type(e).__name__, "message": str(e)}
    env = Env(interp.globals)
    try:
        for stmt in program.stmts:
            interp.exec_stmt(stmt, env)
    except Exception as e:  # noqa: BLE001 — a crash is behaviour too
        return {"kind": "crash", "exc": type(e).__name__, "out": out}
    return {
        "kind": "ok",
        "out": out,
        "checks": [[c["label"], c["ok"]] for c in interp.checks],
        "vals": dict((k, full_show(v.payload)) for k, v in env.vars.items()),
    }


def run(src):
    return canonical(src, Interpreter, Env, LexError, ParseError, full_show)



def test_kill_interp_py_230_bool_223():
    """mutant interp.py:230:bool#223: Or -> And (line 230) — mutant gave {'kind': 'crash', 'exc': 'TypeError', 'out': []}"""
    src = 'let v1 = (contrast(even, even)[steps(even, "fold")] rescue sqrt(odd).b)\n'
    assert run(src) == {'kind': 'ok', 'out': [], 'checks': [], 'vals': {'v1': "miss: unbound name 'odd' (line 1)"}}


def test_kill_interp_py_2111_const_632():
    """mutant interp.py:2111:const#632: 2 -> 3 (line 2111) — mutant gave {'kind': 'ok', 'out': [], 'checks': [], 'vals': {'v1': 'miss: 'and' needs true/false, got [@{count: 1, /u2026] (line 1)'"""
    src = 'let v1 = ((steps(0, q, q) and (true % undefined_name)) % reasons)\n'
    assert run(src) == {'kind': 'ok', 'out': [], 'checks': [], 'vals': {'v1': 'miss: steps expects 1..2 args, got 3 (line 1)'}}


def test_kill_interp_py_231_arith_651():
    """mutant interp.py:231:arith#651: Mod -> Mult (line 231) — mutant gave {'kind': 'crash', 'exc': 'TypeError', 'out': []}"""
    src = 'let v1 = (contrast(even, even)[steps(even, "fold")] rescue sqrt(odd).b)\n'
    assert run(src) == {'kind': 'ok', 'out': [], 'checks': [], 'vals': {'v1': "miss: unbound name 'odd' (line 1)"}}


def test_kill_interp_py_2219_const_834():
    """mutant interp.py:2219:const#834: 1 -> 2 (line 2219) — mutant gave {'kind': 'ok', 'out': [], 'checks': [], 'vals': {'v1': 'no divergence'}}"""
    src = 'let v1 = contrast([zz, q])\n'
    assert run(src) == {'kind': 'ok', 'out': [], 'checks': [], 'vals': {'v1': 'run 1 vs run 0:\norigin 1 of 1 (step):\n▶ miss ← name zz  (line 1) │ ▶ miss ← name q  (line 1)'}}


def test_kill_interp_py_586_arith_953():
    """mutant interp.py:586:arith#953: Mod -> Mult (line 586) — mutant gave {'kind': 'crash', 'exc': 'TypeError', 'out': []}"""
    src = 'fold(blame, reasons("0x1f"), [1.5.b, @{name: v1, b: v3, x: v3}, str(0), "0.5"])\n'
    assert run(src) == {'kind': 'ok', 'out': [], 'checks': [], 'vals': {}}


def test_kill_interp_py_1685_const_1049():
    """mutant interp.py:1685:const#1049: False -> True (line 1685) — mutant gave {'kind': 'ok', 'out': [], 'checks': [], 'vals': {'v2': 'true'}}"""
    src = 'let v2 = ((@{name: v1, v: v1} == @{c: false, v: v1}) or (@{v: 0, x: v1, b: v1} * v1))\n'
    assert run(src) == {'kind': 'ok', 'out': [], 'checks': [], 'vals': {'v2': "miss: unbound name 'v1' (line 1)"}}
